# Supplementary Fig. S2 — Rendering dependence and limits of MIDD additivity

Ten official pretrained models (000–009), 21 canonical pairs per model and rendering. Historical `highres_232` is a seven-field layout, distinct from the eight-field rendering in main Fig.3. Scalar fits are descriptive; the full-field extension is unregistered exploratory. High fitted scalar R² does not establish identity of vector fields.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [name for name in ("numpy", "pandas", "matplotlib")
               if importlib.util.find_spec(name) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = 'S2'

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/supplementary/figS2/source_re...,bbada09f9eef597abd04d7e697ab602bbd81fe25bb060c...,18416
1,data/precomputed/supplementary/figS2/scalar_ru...,b46f500547b60b038f190757167e66fddb2ead0e2790e5...,170
2,data/precomputed/supplementary/figS2/scalar_ad...,60f2120934bb87ce6fac81635a1d45e182050e4b6b30bd...,2374
3,data/precomputed/supplementary/figS2/metadata....,f8edddc042edf68681e5902de82d74bbff61d61673d54f...,21611
4,data/precomputed/supplementary/figS2/field_01_...,c491c9f53213e8e1cb03190da4e817d62ace29c90eeb3b...,109179
5,data/precomputed/supplementary/figS2/scalar_gl...,6fad350407205aa016cdba624b18d5c68894b0a48dc8b8...,476
6,data/precomputed/supplementary/figS2/scalar_02...,2f10b7df3f999bf098c315f804ec25da752f060f72b551...,6282
7,data/precomputed/supplementary/figS2/scalar_03...,fec13d94d2753ce344347a88041d36462115f143a1e1c1...,116257
8,data/precomputed/supplementary/figS2/scalar_05...,c628fcd2f0961849458b98705308132ef1947a17447c42...,5269
9,data/precomputed/supplementary/figS2/scalar_06...,df6cfd4c6963acb86510adb2f13ecebd4e65c8ade2f433...,133
10,data/precomputed/supplementary/figS2/field_02_...,6682bc3bb5f79f8320a147248028f1640b6bc36b836003...,3410
11,data/precomputed/supplementary/figS2/field_04_...,90143d7ab8ddd281fd96a42417054d8401f06a07439c98...,128
12,data/precomputed/supplementary/figS2/field_run...,9b72fe469602585be7e47a09fa55d8686da73173d10d19...,166

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 7

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

Empty DataFrame
Columns: [check, passed]
Index: []

## 5. Primary analysis
For Fig3/S7, affine fits and both held-out splits are recomputed from saved A3/A4. Native and multi-field definitions remain separate.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

data/precomputed/supplementary/figS2/field_01_vector_field_metrics.csv

,model_id,rendering,c1,c2,analysis_status,vector_rmse,normalized_vector_rmse,cosine_similarity,vector_correlation,explained_variance,local_tangent_rmse,local_tangent_correlation,global_tangent_observed,global_tangent_predicted,global_tangent_residual
0,flow/0000/000,boxeye,48,80,unregistered_exploratory,0.018870,1.724308,-0.324908,-0.286243,-1.480479,0.019376,-0.324950,0.000787,-0.002894,0.003682
1,flow/0000/001,boxeye,48,80,unregistered_exploratory,0.004088,1.423813,-0.284534,-0.284181,-2.437036,0.004925,-0.413972,0.000807,-0.000147,0.000954
2,flow/0000/002,boxeye,48,80,unregistered_exploratory,0.015841,1.906315,-0.345144,-0.344101,-1.107646,0.018778,-0.628183,0.004726,-0.000721,0.005447
3,flow/0000/003,boxeye,48,80,unregistered_exploratory,0.019143,1.145846,0.177449,0.183779,-1.257021,0.019569,0.256638,0.007120,0.005890,0.001230
4,flow/0000/004,boxeye,48,80,unregistered_exploratory,0.025759,1.333766,-0.003574,-0.003471,-1.302383,0.032207,-0.245167,-0.003502,-0.010412,0.006911
5,flow/0000/005,boxeye,48,80,unregistered_exploratory,0.019838,1.204666,0.094051,0.098662,-1.445240,0.019600,0.224229,-0.003903,-0.013751,0.009848
6,flow/0000/006,boxeye,48,80,unregistered_exploratory,0.014592,1.366164,0.161766,0.142870,-0.535788,0.014394,0.118675,0.005674,0.004445,0.001229
7,flow/0000/007,boxeye,48,80,unregistered_exploratory,0.014764,1.247820,0.159967,0.169383,-0.826754,0.014449,0.170883,-0.002776,-0.006111,0.003335
8,flow/0000/008,boxeye,48,80,unregistered_exploratory,0.022922,1.574210,-0.092312,-0.093791,-0.963009,0.026446,-0.226095,0.001576,0.006007,-0.004431
9,flow/0000/009,boxeye,48,80,unregistered_exploratory,0.019817,1.512722,-0.299766,-0.304784,-1.994412,0.024277,-0.390588,0.002224,-0.008818,0.011042
10,flow/0000/000,boxeye,48,112,unregistered_exploratory,0.032496,1.599730,-0.254764,-0.216465,-1.540393,0.033478,-0.143441,0.000448,-0.008011,0.008459
11,flow/0000/001,boxeye,48,112,unregistered_exploratory,0.008815,1.170706,-0.186836,-0.187840,-5.820686,0.009569,-0.165871,0.000268,-0.003534,0.003802
12,flow/0000/002,boxeye,48,112,unregistered_exploratory,0.028948,1.749004,-0.434763,-0.434150,-1.703317,0.035865,-0.686078,0.007248,-0.006777,0.014026
13,flow/0000/003,boxeye,48,112,unregistered_exploratory,0.040958,1.460500,-0.270442,-0.268136,-2.120592,0.047023,-0.138632,0.010662,-0.008497,0.019159
14,flow/0000/004,boxeye,48,112,unregistered_exploratory,0.047726,1.307543,-0.008617,-0.007834,-1.458980,0.058345,-0.177693,-0.007316,-0.020072,0.012756
15,flow/0000/005,boxeye,48,112,unregistered_exploratory,0.037225,1.029260,0.299639,0.304834,-1.256280,0.038523,0.386535,-0.012340,-0.032975,0.020635
16,flow/0000/006,boxeye,48,112,unregistered_exploratory,0.032406,1.682976,-0.255053,-0.283992,-1.267733,0.036666,-0.368410,0.009227,-0.005165,0.014392
17,flow/0000/007,boxeye,48,112,unregistered_exploratory,0.029788,1.329444,-0.025317,-0.020051,-1.441368,0.028669,-0.005387,-0.003388,-0.012982,0.009594
18,flow/0000/008,boxeye,48,112,unregistered_exploratory,0.040886,1.529456,-0.193657,-0.194557,-1.479640,0.048648,-0.269478,0.001209,0.005844,-0.004635
19,flow/0000/009,boxeye,48,112,unregistered_exploratory,0.038813,1.436784,-0.340674,-0.349866,-2.712495,0.049495,-0.506971,0.003166,-0.017505,0.020672

data/precomputed/supplementary/figS2/scalar_02_model_level_statistics.csv

,model_id,rendering,slope,intercept,normalized_intercept,r2,pearson_r,mae,rmse,normalized_mae,normalized_rmse,mean_normalized_residual,n_sign_evaluable,sign_accuracy,a3_dynamic_range,cycle_mean,cycle_mae,cycle_rmse
0,flow/0000/000,boxeye,0.319433,0.001928,0.220881,0.816538,0.903625,0.003778,0.004585,0.432823,0.525255,0.432823,18,0.555556,0.008728,0.210981,0.210981,0.235830
1,flow/0000/000,highres_232,0.464634,-0.003727,-0.032382,0.962368,0.981003,0.027855,0.034861,0.241992,0.302862,0.233547,18,1.000000,0.115106,-0.048108,0.048209,0.061064
2,flow/0000/001,boxeye,0.070326,0.002235,0.185833,0.053822,0.231995,0.007695,0.008870,0.639823,0.737572,0.639823,19,0.157895,0.012026,0.102349,0.102349,0.124788
3,flow/0000/001,highres_232,0.625605,-0.006241,-0.087340,0.803505,0.896384,0.008679,0.013690,0.121456,0.191583,0.099303,20,1.000000,0.071456,-0.144247,0.145660,0.188271
4,flow/0000/002,boxeye,-0.073299,0.003076,0.252399,0.072301,-0.268889,0.008506,0.010271,0.697968,0.842804,0.697968,20,0.250000,0.012186,0.303617,0.303617,0.364263
5,flow/0000/002,highres_232,0.603298,-0.002839,-0.058927,0.917720,0.957977,0.007335,0.009794,0.152260,0.203308,0.128898,20,1.000000,0.048174,-0.108363,0.112682,0.142080
6,flow/0000/003,boxeye,-0.048688,0.008029,0.142555,0.198663,-0.445717,0.036837,0.043059,0.654033,0.764496,0.654033,20,0.150000,0.056323,0.136076,0.136076,0.151743
7,flow/0000/003,highres_232,0.659596,-0.001318,-0.011802,0.965226,0.982459,0.017204,0.023176,0.154006,0.207467,0.148391,20,1.000000,0.111708,-0.059840,0.066270,0.089956
8,flow/0000/004,boxeye,0.329438,0.001887,0.077264,0.752004,0.867182,0.007342,0.009155,0.300603,0.374868,0.213736,21,0.809524,0.024423,-0.038390,0.081662,0.097285
9,flow/0000/004,highres_232,0.744877,-0.001697,-0.020812,0.975163,0.987503,0.009151,0.011484,0.112218,0.140834,0.102032,20,1.000000,0.081544,-0.043146,0.051849,0.072738
10,flow/0000/005,boxeye,0.342124,0.012402,0.174844,0.502227,0.708680,0.032263,0.037167,0.454860,0.523989,0.454860,20,0.600000,0.070931,0.086046,0.086046,0.106273
11,flow/0000/005,highres_232,0.786505,-0.000566,-0.005674,0.957921,0.978734,0.009973,0.013260,0.099897,0.132819,0.092051,19,1.000000,0.099836,-0.040177,0.041038,0.053864
12,flow/0000/006,boxeye,-0.270952,0.004656,0.150259,0.699436,-0.836323,0.024297,0.028191,0.784072,0.909738,0.784072,18,0.055556,0.030989,0.136515,0.136845,0.171340
13,flow/0000/006,highres_232,0.600148,-0.004569,-0.057317,0.949532,0.974439,0.013287,0.015905,0.166687,0.199529,0.116213,19,1.000000,0.079715,-0.077088,0.090361,0.117038
14,flow/0000/007,boxeye,0.254497,0.002802,0.143890,0.509432,0.713745,0.008224,0.009842,0.422362,0.505464,0.403484,20,0.650000,0.019471,0.035310,0.048133,0.065546
15,flow/0000/007,highres_232,0.670941,0.001884,0.094576,0.927292,0.962960,0.003329,0.004354,0.167111,0.218536,0.124012,20,0.900000,0.019921,-0.032245,0.060802,0.084560
16,flow/0000/008,boxeye,0.263681,-0.000167,-0.006451,0.758304,0.870807,0.009327,0.011221,0.359901,0.432977,0.326586,19,1.000000,0.025916,-0.060995,0.075502,0.090917
17,flow/0000/008,highres_232,0.850491,-0.002202,-0.057818,0.904245,0.950918,0.004591,0.005383,0.120530,0.141302,-0.015780,20,0.950000,0.038093,0.011178,0.024640,0.029482
18,flow/0000/009,boxeye,0.036852,0.005335,0.218071,0.031578,0.177703,0.012334,0.015156,0.504194,0.619554,0.477063,20,0.350000,0.024463,0.116917,0.116917,0.134520
19,flow/0000/009,highres_232,0.741164,-0.004634,-0.107441,0.974047,0.986938,0.003632,0.004618,0.084226,0.107083,-0.015273,20,0.900000,0.043127,-0.106426,0.107149,0.135997

data/precomputed/supplementary/figS2/scalar_03_canonical_pair_predictions.csv

,model_id,rendering,c1,c2,mirror,negative,original,a4_observed,a3_c1,a3_c2,a4_predicted,residual,a3_dynamic_range,normalized_residual,diagonal,canonical,normalized_abs_prediction,sign_evaluable,sign_correct
0,flow/0000/000,boxeye,48,80,0.003324,0.003471,0.004898,0.000787,-0.001933,0.000961,-0.002894,0.003682,0.008728,0.421794,False,True,0.331617,True,False
1,flow/0000/000,boxeye,48,112,0.004959,0.000780,0.005855,0.000448,-0.001933,0.006078,-0.008011,0.008459,0.008728,0.969146,False,True,0.917807,True,False
2,flow/0000/000,boxeye,48,143,0.006583,-0.002540,0.004836,-0.000874,-0.001933,0.006795,-0.008728,0.007855,0.008728,0.899920,False,True,1.000000,True,True
3,flow/0000/000,boxeye,48,175,0.007826,-0.001851,0.004003,-0.001912,-0.001933,0.006040,-0.007974,0.006062,0.008728,0.694481,False,True,0.913528,True,True
4,flow/0000/000,boxeye,48,191,0.007002,-0.001345,0.004648,-0.001177,-0.001933,0.005698,-0.007632,0.006455,0.008728,0.739561,False,True,0.874362,True,True
5,flow/0000/000,boxeye,48,207,0.005619,-0.000676,0.005137,-0.000241,-0.001933,0.004435,-0.006368,0.006127,0.008728,0.701990,False,True,0.729567,True,True
6,flow/0000/000,boxeye,80,112,0.005444,0.004960,0.006589,0.000572,0.000961,0.006078,-0.005117,0.005689,0.008728,0.651738,False,True,0.586190,True,False
7,flow/0000/000,boxeye,80,143,0.006367,0.003507,0.007819,0.000726,0.000961,0.006795,-0.005834,0.006560,0.008728,0.751563,False,True,0.668383,True,False
8,flow/0000/000,boxeye,80,175,0.006363,0.000139,0.007041,0.000339,0.000961,0.006040,-0.005079,0.005418,0.008728,0.620713,False,True,0.581911,True,False
9,flow/0000/000,boxeye,80,191,0.006111,0.000249,0.007819,0.000854,0.000961,0.005698,-0.004737,0.005591,0.008728,0.640594,False,True,0.542745,True,False
10,flow/0000/000,boxeye,80,207,0.005578,0.001550,0.008806,0.001614,0.000961,0.004435,-0.003473,0.005088,0.008728,0.582870,False,True,0.397950,True,False
11,flow/0000/000,boxeye,112,143,0.006838,0.006705,0.009164,0.001163,0.006078,0.006795,-0.000717,0.001881,0.008728,0.215450,False,True,0.082193,True,False
12,flow/0000/000,boxeye,112,175,0.006415,0.004648,0.009392,0.001488,0.006078,0.006040,0.000037,0.001451,0.008728,0.166233,False,True,0.004279,False,False
13,flow/0000/000,boxeye,112,191,0.005735,0.003533,0.009723,0.001994,0.006078,0.005698,0.000379,0.001615,0.008728,0.185034,False,True,0.043445,False,False
14,flow/0000/000,boxeye,112,207,0.004910,0.003955,0.010660,0.002875,0.006078,0.004435,0.001643,0.001232,0.008728,0.141160,False,True,0.188240,True,True
15,flow/0000/000,boxeye,143,175,0.006878,0.007533,0.010380,0.001751,0.006795,0.006040,0.000755,0.000996,0.008728,0.114151,False,True,0.086472,True,True
16,flow/0000/000,boxeye,143,191,0.005930,0.006121,0.011185,0.002628,0.006795,0.005698,0.001097,0.001531,0.008728,0.175404,False,True,0.125638,True,True
17,flow/0000/000,boxeye,143,207,0.005092,0.005454,0.011542,0.003225,0.006795,0.004435,0.002360,0.000865,0.008728,0.099098,False,True,0.270433,True,True
18,flow/0000/000,boxeye,175,191,0.008562,0.009474,0.011578,0.001508,0.006040,0.005698,0.000342,0.001166,0.008728,0.133572,False,True,0.039166,False,False
19,flow/0000/000,boxeye,175,207,0.006742,0.008371,0.012236,0.002747,0.006040,0.004435,0.001606,0.001142,0.008728,0.130791,False,True,0.183962,True,True

data/precomputed/supplementary/figS2/scalar_05_global_model_metrics.csv

,model_id,rendering,slope,intercept,normalized_intercept,r2,pearson_r,mae,rmse,normalized_mae,normalized_rmse,mean_normalized_residual,n_sign_evaluable,sign_accuracy,a3_dynamic_range
0,flow/0000/000,boxeye,0.319433,0.001928,0.220881,0.816538,0.903625,0.003778,0.004585,0.432823,0.525255,0.432823,18,0.555556,0.008728
1,flow/0000/000,highres_232,0.464634,-0.003727,-0.032382,0.962368,0.981003,0.027855,0.034861,0.241992,0.302862,0.233547,18,1.000000,0.115106
2,flow/0000/001,boxeye,0.070326,0.002235,0.185833,0.053822,0.231995,0.007695,0.008870,0.639823,0.737572,0.639823,19,0.157895,0.012026
3,flow/0000/001,highres_232,0.625605,-0.006241,-0.087340,0.803505,0.896384,0.008679,0.013690,0.121456,0.191583,0.099303,20,1.000000,0.071456
4,flow/0000/002,boxeye,-0.073299,0.003076,0.252399,0.072301,-0.268889,0.008506,0.010271,0.697968,0.842804,0.697968,20,0.250000,0.012186
5,flow/0000/002,highres_232,0.603298,-0.002839,-0.058927,0.917720,0.957977,0.007335,0.009794,0.152260,0.203308,0.128898,20,1.000000,0.048174
6,flow/0000/003,boxeye,-0.048688,0.008029,0.142555,0.198663,-0.445717,0.036837,0.043059,0.654033,0.764496,0.654033,20,0.150000,0.056323
7,flow/0000/003,highres_232,0.659596,-0.001318,-0.011802,0.965226,0.982459,0.017204,0.023176,0.154006,0.207467,0.148391,20,1.000000,0.111708
8,flow/0000/004,boxeye,0.329438,0.001887,0.077264,0.752004,0.867182,0.007342,0.009155,0.300603,0.374868,0.213736,21,0.809524,0.024423
9,flow/0000/004,highres_232,0.744877,-0.001697,-0.020812,0.975163,0.987503,0.009151,0.011484,0.112218,0.140834,0.102032,20,1.000000,0.081544
10,flow/0000/005,boxeye,0.342124,0.012402,0.174844,0.502227,0.708680,0.032263,0.037167,0.454860,0.523989,0.454860,20,0.600000,0.070931
11,flow/0000/005,highres_232,0.786505,-0.000566,-0.005674,0.957921,0.978734,0.009973,0.013260,0.099897,0.132819,0.092051,19,1.000000,0.099836
12,flow/0000/006,boxeye,-0.270952,0.004656,0.150259,0.699436,-0.836323,0.024297,0.028191,0.784072,0.909738,0.784072,18,0.055556,0.030989
13,flow/0000/006,highres_232,0.600148,-0.004569,-0.057317,0.949532,0.974439,0.013287,0.015905,0.166687,0.199529,0.116213,19,1.000000,0.079715
14,flow/0000/007,boxeye,0.254497,0.002802,0.143890,0.509432,0.713745,0.008224,0.009842,0.422362,0.505464,0.403484,20,0.650000,0.019471
15,flow/0000/007,highres_232,0.670941,0.001884,0.094576,0.927292,0.962960,0.003329,0.004354,0.167111,0.218536,0.124012,20,0.900000,0.019921
16,flow/0000/008,boxeye,0.263681,-0.000167,-0.006451,0.758304,0.870807,0.009327,0.011221,0.359901,0.432977,0.326586,19,1.000000,0.025916
17,flow/0000/008,highres_232,0.850491,-0.002202,-0.057818,0.904245,0.950918,0.004591,0.005383,0.120530,0.141302,-0.015780,20,0.950000,0.038093
18,flow/0000/009,boxeye,0.036852,0.005335,0.218071,0.031578,0.177703,0.012334,0.015156,0.504194,0.619554,0.477063,20,0.350000,0.024463
19,flow/0000/009,highres_232,0.741164,-0.004634,-0.107441,0.974047,0.986938,0.003632,0.004618,0.084226,0.107083,-0.015273,20,0.900000,0.043127

data/precomputed/supplementary/figS2/scalar_06_final_QA.csv

                              check  pass
0                     model_rows_20  True
1                    cycle_rows_700  True
2  canonical_21_per_model_rendering  True
3              finite_model_metrics  True
4                     reports_saved  True

data/precomputed/supplementary/figS2/field_02_representation_level_summary.csv

,model_id,rendering,mean_normalized_vector_rmse,mean_vector_cosine,mean_vector_correlation,mean_local_tangent_correlation,global_tangent_r2,global_tangent_slope,global_tangent_rmse
0,flow/0000/000,boxeye,1.426345,-0.023541,-0.015728,0.044322,0.816538,0.319433,0.004585
1,flow/0000/000,highres_232,0.876872,0.507710,0.508914,0.381486,0.962368,0.464634,0.034861
2,flow/0000/001,boxeye,1.234326,-0.123463,-0.125741,-0.073801,0.053822,0.070326,0.008870
3,flow/0000/001,highres_232,0.811553,0.631477,0.631835,0.564183,0.803505,0.625605,0.013690
4,flow/0000/002,boxeye,1.462773,-0.124004,-0.118746,-0.243891,0.072301,-0.073299,0.010271
5,flow/0000/002,highres_232,1.010752,0.452201,0.452224,0.416515,0.917720,0.603298,0.009794
6,flow/0000/003,boxeye,1.445067,-0.319811,-0.318147,-0.310156,0.198663,-0.048688,0.043059
7,flow/0000/003,highres_232,0.993363,0.477257,0.477285,0.309583,0.965226,0.659596,0.023176
8,flow/0000/004,boxeye,1.448549,-0.049990,-0.046131,-0.080293,0.752004,0.329438,0.009155
9,flow/0000/004,highres_232,1.027079,0.431810,0.432401,0.308124,0.975163,0.744877,0.011484
10,flow/0000/005,boxeye,1.205314,0.074460,0.070383,0.036434,0.502227,0.342124,0.037167
11,flow/0000/005,highres_232,1.119509,0.453356,0.453468,0.297039,0.957921,0.786505,0.013260
12,flow/0000/006,boxeye,1.443540,-0.317005,-0.338066,-0.423789,0.699436,-0.270952,0.028191
13,flow/0000/006,highres_232,0.988469,0.385261,0.385365,0.361028,0.949532,0.600148,0.015905
14,flow/0000/007,boxeye,1.560532,-0.206975,-0.207553,-0.224749,0.509432,0.254497,0.009842
15,flow/0000/007,highres_232,1.112020,0.310088,0.309783,0.207913,0.927292,0.670941,0.004354
16,flow/0000/008,boxeye,1.507700,-0.152600,-0.154530,-0.217818,0.758304,0.263681,0.011221
17,flow/0000/008,highres_232,1.149884,0.309064,0.308456,0.286334,0.904245,0.850491,0.005383
18,flow/0000/009,boxeye,1.417608,-0.199579,-0.200098,-0.340388,0.031578,0.036852,0.015156
19,flow/0000/009,highres_232,1.141725,0.339862,0.339492,0.330212,0.974047,0.741164,0.004618

data/precomputed/supplementary/figS2/field_04_vector_field_QA.csv

                    check  pass
0         metric_rows_420  True
1  representation_rows_20  True
2                  finite  True
3  global_scalar_identity  True
4  primary_eligible_false  True

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

## 7. Statistics
Model/seed is the unit. Stored intervals retain the original inference choices. Fig3/S7 additionally replay the exact original bootstrap seed and RNG consumption order; cached null draws are not regenerated or tuned.

In [7]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

## 8. Retained source analysis and figure generation
The established native calibration/rendering/classical-detector cells below preserve original metrics and plot geometry.

## Load bundled source data and verify provenance

Only small saved artifacts are loaded. No FlyVis inference, training, or source-repository access is needed.

In [8]:
import json, hashlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
plt.rcParams.update({'font.size':8,'axes.spines.top':False,'axes.spines.right':False,'figure.dpi':140})
DATA=ROOT/'data/precomputed/supplementary/figS2'
OUT=ROOT/'figures/supplementary/figS2'
OUT.mkdir(parents=True,exist_ok=True)
meta=json.loads((DATA/'metadata.json').read_text())
qa=[]
def check(name,passed,detail=''):
    qa.append({'check':name,'pass':bool(passed),'detail':str(detail)})
def read(name):
    return pd.read_csv(DATA/name,dtype={'model_id':str})
def finite(table):
    return np.isfinite(table.select_dtypes('number').to_numpy()).all()
for record in meta['sources']:
    check('SHA256 '+record['filename'],hashlib.sha256((DATA/record['filename']).read_bytes()).hexdigest()==record.get('copied_sha256', record['source_sha256']))
print(meta['analysis_contract'])
metrics=read('scalar_02_model_level_statistics.csv')
pairs=read('scalar_03_canonical_pair_predictions.csv')
global_metrics=read('scalar_05_global_model_metrics.csv')
field=read('field_01_vector_field_metrics.csv')
representation=read('field_02_representation_level_summary.csv')
renderings=['boxeye','highres_232']
ids=[f'flow/0000/{i:03d}' for i in range(10)]
for table in [metrics,pairs,global_metrics,field,representation]:
    check('model/rendering coverage '+str(table.shape),set(table.model_id)==set(ids) and set(table.rendering)==set(renderings))
    check('finite '+str(table.shape),finite(table))
check('scalar source QA',read('scalar_06_final_QA.csv')['pass'].all())
check('field source QA',read('field_04_vector_field_QA.csv')['pass'].all())
check('exploratory field status',field.analysis_status.eq('unregistered_exploratory').all())
check('canonical pair coverage',len(pairs)==420 and not pairs.duplicated(['model_id','rendering','c1','c2']).any() and (pairs.c1<pairs.c2).all() and pairs.groupby(['model_id','rendering']).size().eq(21).all())
check('full-field pair coverage',len(field)==420 and not field.duplicated(['model_id','rendering','c1','c2']).any() and field.groupby(['model_id','rendering']).size().eq(21).all())

{'model_cohort': 'official pretrained flow/0000/000–009 (N=10)', 'rendering': ['boxeye', 'highres_232 (2,3,2; seven fields), distinct from main Fig.3 centered (3,2,3; eight fields)'], 'statistical_unit': 'trained model; 21 canonical luminance pairs within each model', 'status': 'descriptive rendering comparison; full-field metrics unregistered exploratory', 'scalar': 'A4,pred=A3(C1)-A3(C2); model-wise OLS with intercept; identity RMSE normalized by within-model A3 range', 'field': 'Stable time-mean antisymmetric vector fields; overlap merging and source spatial mask. Identity vector RMSE normalized by prediction RMS; no fitted field gain.', 'sign_gate': 'abs(prediction)>=0.05*within-model A3 range'}

## Reproduce source summaries and QA

The source model and rendering contracts remain separate. Calculations below verify saved results; no new inferential tests are introduced.

In [9]:
rows=[]
for (mid,rendering),q in pairs.groupby(['model_id','rendering']):
    x=q.a4_predicted.to_numpy();y=q.a4_observed.to_numpy()
    slope,intercept=np.linalg.lstsq(np.c_[x,np.ones(len(x))],y,rcond=None)[0]
    r2=1-np.sum((y-slope*x-intercept)**2)/np.sum((y-y.mean())**2)
    rmse=np.sqrt(np.mean((y-x)**2))/q.a3_dynamic_range.iloc[0]
    gate=np.abs(x)/q.a3_dynamic_range.to_numpy()>=.05
    check('sign gate '+mid+' '+rendering,np.array_equal(gate,q.sign_evaluable.to_numpy()))
    check('sign flags '+mid+' '+rendering,np.array_equal(gate&(np.sign(x)==np.sign(y)),q.sign_correct.to_numpy()))
    rows.append(dict(model_id=mid,rendering=rendering,slope=slope,intercept=intercept,r2=r2,normalized_rmse=rmse,sign_accuracy=np.mean(np.sign(x[gate])==np.sign(y[gate]))))
reproduced=pd.DataFrame(rows)
for source in [metrics,global_metrics]:
    j=reproduced.merge(source,on=['model_id','rendering'],suffixes=('_new','_source'),validate='one_to_one')
    check('scalar reproduction '+str(source.shape),all(np.allclose(j[c+'_new'],j[c+'_source'],atol=1e-10,rtol=1e-8) for c in ['slope','intercept','r2','normalized_rmse','sign_accuracy']))
agg=field.groupby(['model_id','rendering']).agg(mean_normalized_vector_rmse=('normalized_vector_rmse','mean'),mean_vector_cosine=('cosine_similarity','mean'),mean_vector_correlation=('vector_correlation','mean'),mean_local_tangent_correlation=('local_tangent_correlation','mean')).reset_index()
j=agg.merge(representation,on=['model_id','rendering'],suffixes=('_new','_source'),validate='one_to_one')
check('field summary reproduction',all(np.allclose(j[c+'_new'],j[c+'_source'],atol=1e-10) for c in agg.columns if c not in ['model_id','rendering']))
j=field.merge(pairs,on=['model_id','rendering','c1','c2'],validate='one_to_one')
check('field/global scalar consistency',np.allclose(j.global_tangent_observed,j.a4_observed,atol=1e-8) and np.allclose(j.global_tangent_predicted,j.a4_predicted,atol=1e-8))
summary=metrics.groupby('rendering')[['r2','sign_accuracy','normalized_rmse','slope']].agg(['mean','sem'])
display(summary)
summary.to_csv(OUT/'figS2_scalar_summary.csv')
agg.to_csv(OUT/'figS2_field_model_summary.csv',index=False)

                   r2           sign_accuracy           normalized_rmse  \
                 mean       sem          mean       sem            mean
rendering
boxeye       0.439430  0.101425      0.457853  0.099202        0.623672
highres_232  0.933702  0.016369      0.975000  0.013437        0.184532

                          slope
                  sem      mean       sem
rendering
boxeye       0.057207  0.122341  0.066642
highres_232  0.017877  0.674726  0.034989

## Generate and save the supplementary figure

QA must pass before final figure files are saved.

In [10]:
fig=plt.figure(figsize=(11.2,7.8),constrained_layout=True)
gs=fig.add_gridspec(2,2)
colors=['#4c78a8','#f58518'];labels=['BoxEye','highres_232']
a=fig.add_subplot(gs[0,0]);b=fig.add_subplot(gs[0,1])
for k,(ax,col,title) in enumerate([(a,'r2','A  Fitted scalar R²'),(b,'sign_accuracy','B  Scalar sign agreement')]):
    pivot=metrics.pivot(index='model_id',columns='rendering',values=col)[renderings]
    for row in pivot.to_numpy():ax.plot([0,1],row,color='0.75',lw=.7,zorder=0)
    for i,r in enumerate(renderings):
        v=pivot[r];ax.scatter(np.full(10,i)+np.linspace(-.06,.06,10),v,s=20,color=colors[i]);ax.errorbar(i,v.mean(),yerr=v.sem(),fmt='D',color='black',capsize=3)
        ax.text(i,1.025,f'{v.mean():.3f}',ha='center',fontsize=8)
    ax.set(xticks=[0,1],xticklabels=labels,ylim=(-.03,1.09),title=title,ylabel=col.replace('_',' '))
# Fixed illustrative model, selected independently of goodness of fit.
sub=gs[1,0].subgridspec(1,2)
for i,r in enumerate(renderings):
    ax=fig.add_subplot(sub[0,i]);q=pairs[(pairs.model_id=='flow/0000/000')&(pairs.rendering==r)]
    ax.scatter(q.a4_predicted,q.a4_observed,color=colors[i],s=20)
    lo=min(q.a4_predicted.min(),q.a4_observed.min());hi=max(q.a4_predicted.max(),q.a4_observed.max())
    ax.plot([lo,hi],[lo,hi],ls='--',color='0.5',lw=1)
    m=metrics[(metrics.model_id=='flow/0000/000')&(metrics.rendering==r)].iloc[0]
    x=np.array([lo,hi]);ax.plot(x,m.slope*x+m.intercept,color=colors[i],lw=1)
    ax.set(xlabel='A₄ predicted',ylabel='A₄ observed',title=('C  ' if i==0 else '')+labels[i]+' / model 000')
    ax.ticklabel_format(style='sci',axis='both',scilimits=(-2,2))
    from matplotlib.ticker import MaxNLocator
    ax.xaxis.set_major_locator(MaxNLocator(3))
ax=fig.add_subplot(gs[1,1]);ax2=ax.twinx()
for i,r in enumerate(renderings):
    q=agg[agg.rendering==r];x=i*3
    ax.scatter(np.full(10,x)+np.linspace(-.12,.12,10),q.mean_normalized_vector_rmse,color=colors[i],s=20)
    ax.errorbar(x,q.mean_normalized_vector_rmse.mean(),yerr=q.mean_normalized_vector_rmse.sem(),fmt='D',color='black',capsize=3)
    ax2.scatter(np.full(10,x+1)+np.linspace(-.12,.12,10),q.mean_vector_cosine,color=colors[i],marker='s',s=20)
    ax2.errorbar(x+1,q.mean_vector_cosine.mean(),yerr=q.mean_vector_cosine.sem(),fmt='D',color='black',capsize=3)
ax.set(xticks=[0,1,3,4],xticklabels=['BoxEye\nRMSE','BoxEye\ncosine','highres_232\nRMSE','highres_232\ncosine'],ylabel='Identity vector RMSE / prediction RMS',title='D  Full-field extension (exploratory)')
ax2.set(ylabel='Vector cosine similarity',ylim=(-.35,1.1));ax.axhline(0,color='0.5',lw=.6);ax2.axhline(1,color='0.7',ls=':',lw=.8)
fig.suptitle('S2  Rendering affects scalar composition; scalar fits do not imply field identity',fontsize=11)

qa_table=pd.DataFrame(qa)
qa_table.to_csv(OUT/'figS2_QA.csv',index=False)
display(qa_table)
assert qa_table['pass'].all(), 'QA failed: inspect saved QA before using figure.'
import matplotlib
for text_item in fig.findobj(matplotlib.text.Text):
    if text_item.get_fontsize() < 10:
        text_item.set_fontsize(10)
fig.savefig(OUT/'figS2_main.png',dpi=250,bbox_inches='tight')
fig.savefig(OUT/'figS2_main.pdf',bbox_inches='tight')
plt.show()
plt.close(fig)
print('Saved PNG/PDF and',len(qa_table),'passing QA checks.')

                                              check  pass detail
0       SHA256 scalar_02_model_level_statistics.csv  True
1   SHA256 scalar_03_canonical_pair_predictions.csv  True
2         SHA256 scalar_05_global_model_metrics.csv  True
3                     SHA256 scalar_06_final_QA.csv  True
4            SHA256 scalar_global_run_metadata.json  True
..                                              ...   ...    ...
66             sign flags flow/0000/009 highres_232  True
67                     scalar reproduction (20, 18)  True
68                     scalar reproduction (20, 15)  True
69                       field summary reproduction  True
70                  field/global scalar consistency  True

[71 rows x 3 columns]

Saved PNG/PDF and 71 passing QA checks.

<temporary-kernel-path>/ipykernel.py:46: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [11]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: S2 primary tables: 7 adopted tables: 0

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [12]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/supplementary/fig_S2.ipynb
Model inference: False