# Figure S5

Official-50 same-operator controls, phase context and fixed diagnostic EPE are separate estimands. Uniform gray is an unpaired tangent measurement.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [name for name in ("numpy", "pandas", "matplotlib")
               if importlib.util.find_spec(name) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = 'S5'

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/fig02/...,9710de8c00486c3893aa07a50b46db579d0a12a3bd7bcf...,8680
1,data/precomputed/fig04/phase_pa...,c9506a3fd02d96fbc8c8af4bb8d7bdf16dd8b7c3b6e17b...,97940
2,data/precomputed/fig04/...,f2db5ddf8dfdadc4e2e8fe6084ab635bd96741e8c525a0...,67604
3,data/precomputed/fig01/fig1_midd_per_model.csv,ea64ba2c8b5d1bee163f70c30901bf6063849957771137...,28361
4,data/precomputed/fig02/...,3fd2de4b6f4c9a0d5f0ca278d24304733c128049edf5a1...,1522
5,data/precomputed/fig04/phase_mo...,aeef2462b3e27bfc7fb83f44dfa17bc298f5070ae8e3d5...,6938
6,data/precomputed/fig04/phase_bo...,25e7129e521532e862e8f8118130224e592fbd0e5fb1f1...,2594
7,data/precomputed/fig04/...,e778aa90ae6c4ec8259ee99258c946945aaa168b6183fe...,62149
8,data/precomputed/fig04/...,92f40880f62c25915baf08e045b7e867f0e7ce12d94ae5...,12338
9,data/precomputed/fig02/official50...,6812c7d5121a127dd5b732eec9daaec2a37374bc8ae1c9...,23822
10,data/precomputed/fig02/official50...,bde52ce47f40a748cc037dc8098f10bf54f473872b8f70...,193451
11,data/precomputed/fig02/official50...,0d10976a4a7fcecc8952348a688b388c75fe3ab387b0c5...,1693
12,data/precomputed/fig02/official50...,e328328a4b8e24e32476269f3d2f08b497b187fb381dc5...,46325
13,data/precomputed/fig02/official50...,45a7b1286da2fb6f1ea231671e2afdbeaf50eeffba2400...,933245
14,data/precomputed/fig02/official50...,0ae6279923d14a7e04349da39b3afb0653f32777bddea2...,20699
15,data/precomputed/fig02/official50...,c89eec320fb486f2f75626b727a581bbb0286fa7a7088e...,72230
16,data/precomputed/fig02/official50...,fbb228d8513e3ebd7ee114e759fc4d06be49431215dca3...,1057
17,data/precomputed/fig02/official50...,8f7a89e99bc57a3eba2196122bfeb4d1acd5b81fb2f3a6...,8180
18,data/precomputed/fig02/official50...,ab88b8290843650d162457bba8f177c21bae31cb741dcb...,395
19,data/precomputed/fig04/radial_receptor...,37d62da0b6c699edc8459f95e779c5226c94237dc19ebb...,75251
20,data/precomputed/fig04/radial_radial_m...,a2e7477fe49f5071eb78fcb26acb7abd488c5e7d9972e3...,515151
21,data/precomputed/fig04/radial_ROI_comp...,7ffbf95a097aa04110e41560e017f365fb9e846746664e...,3880
22,data/precomputed/fig04/phase_reliability_icc_bootstra...,5e02d01a3f9a30de719dde3c4d98b9103edff7bfdc191d...,2831

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 23

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

                                               check  passed
0  A/S identity: data/precomputed/fig04/...    True
1  A/S identity: data/precomputed/fig01/fig1_midd...    True
2  A/S identity: data/precomputed/fig04/...    True
3  A/S identity: data/precomputed/fig02/...    True
4  A/S identity: data/precomputed/fig04/...    True

## 5. Primary analysis
For Fig3/S7, affine fits and both held-out splits are recomputed from saved A3/A4. Native and multi-field definitions remain separate.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

official50_fixed_phase_pairs

,model_id,group,phase_index,T_original,T_mirror,A,S,G,actual_reversal
0,0,3MIDD_048,0,-0.001514,0.002210,-0.001862,0.000348,0.189787,True
1,0,3MIDD_048,1,0.008417,0.003819,0.002299,0.006118,0.186632,False
2,0,3MIDD_048,2,0.018111,-0.003000,0.010555,0.007556,0.195354,True
3,0,3MIDD_048,3,-0.001288,-0.004201,0.001457,-0.002745,0.206107,False
4,0,3MIDD_048,4,0.003467,-0.007005,0.005236,-0.001769,0.185331,True
5,0,3MIDD_048,5,0.015049,-0.004991,0.010020,0.005029,0.182951,True
6,0,3MIDD_048,6,0.007851,-0.001009,0.004430,0.003421,0.195866,True
7,0,3MIDD_048,7,0.012710,-0.012755,0.012732,-0.000023,0.206208,True
8,0,3MIDD_048,8,-0.000597,-0.003032,0.001217,-0.001814,0.188205,False
9,0,3MIDD_048,9,0.005577,0.006591,-0.000507,0.006084,0.181644,False
10,0,3MIDD_048,10,0.012503,-0.004343,0.008423,0.004080,0.193643,True
11,0,3MIDD_048,11,0.001909,-0.010398,0.006154,-0.004245,0.204491,True
12,1,3MIDD_048,0,-0.002747,0.000110,-0.001428,-0.001318,0.154596,True
13,1,3MIDD_048,1,-0.003373,-0.004265,0.000446,-0.003819,0.154457,False
14,1,3MIDD_048,2,-0.003188,-0.003999,0.000406,-0.003593,0.152628,False
15,1,3MIDD_048,3,-0.004005,0.003752,-0.003878,-0.000127,0.152722,True
16,1,3MIDD_048,4,-0.002400,0.001164,-0.001782,-0.000618,0.152363,True
17,1,3MIDD_048,5,-0.004648,-0.005055,0.000204,-0.004852,0.152713,False
18,1,3MIDD_048,6,-0.005965,0.001360,-0.003663,-0.002302,0.152586,True
19,1,3MIDD_048,7,-0.001456,0.001844,-0.001650,0.000194,0.153513,True

native_radial_metrics

,model_id,group,phase_index,ROI,n_receptors,T_original,T_mirror,A,S,G,M,raw_reversal
0,0,3MIDD_048,0,full,698,-0.001514,0.002210,-0.001862,0.000348,0.189787,0.001514,True
1,0,3MIDD_048,0,outer,532,-0.001988,-0.001133,-0.000427,-0.001561,0.182719,-0.001133,False
2,0,3MIDD_048,0,radial_0,38,-0.003957,0.011734,-0.007845,0.003888,0.188725,0.003957,True
3,0,3MIDD_048,0,radial_1,74,0.002283,0.017390,-0.007554,0.009836,0.220096,-0.002283,False
4,0,3MIDD_048,0,radial_2,94,-0.002477,0.004264,-0.003371,0.000893,0.210553,0.002477,True
5,0,3MIDD_048,0,radial_3,114,-0.013477,-0.012616,-0.000431,-0.013046,0.189891,-0.012616,False
6,0,3MIDD_048,0,radial_4,146,-0.016607,-0.013185,-0.001711,-0.014896,0.191257,-0.013185,False
7,0,3MIDD_048,0,radial_5,154,0.012185,0.010361,0.000912,0.011273,0.181476,-0.010361,False
8,0,3MIDD_048,0,radial_6,78,0.015923,0.015085,0.000419,0.015504,0.150031,-0.015085,False
9,0,3MIDD_048,1,full,698,0.008417,0.003819,0.002299,0.006118,0.186632,-0.003819,False
10,0,3MIDD_048,1,outer,532,0.011836,0.000861,0.005487,0.006348,0.175680,-0.000861,False
11,0,3MIDD_048,1,radial_0,38,-0.002970,0.009309,-0.006139,0.003170,0.204352,0.002970,True
12,0,3MIDD_048,1,radial_1,74,-0.002363,0.018761,-0.010562,0.008199,0.231707,0.002363,True
13,0,3MIDD_048,1,radial_2,94,-0.000129,0.004522,-0.002326,0.002196,0.209785,0.000129,True
14,0,3MIDD_048,1,radial_3,114,-0.004171,-0.011612,0.003720,-0.007891,0.182904,-0.004171,False
15,0,3MIDD_048,1,radial_4,146,0.001174,-0.009410,0.005292,-0.004118,0.180878,0.001174,True
16,0,3MIDD_048,1,radial_5,154,0.028596,0.016564,0.006016,0.022580,0.178289,-0.016564,False
17,0,3MIDD_048,1,radial_6,78,0.026604,0.008269,0.009168,0.017437,0.140021,-0.008269,False
18,0,3MIDD_048,2,full,698,0.018111,-0.003000,0.010555,0.007556,0.195354,0.003000,True
19,0,3MIDD_048,2,outer,532,0.024528,-0.006319,0.015423,0.009104,0.183899,0.006319,True

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig02/matched_control_specificity_modelwise.csv

,model_id,group,A,S,M,canonical_abs_A,canonical_abs_A_norm,original_image_reflection_A,negative_reflection_A,mean_random_reflection_abs_A,mean_random_normalized_abs_A,D_canonical_vs_random,D_reflection_matched,D_normalized
0,flow/0000/000,3MIDD_048,-0.001862,0.000348,0.001514,0.001862,0.009811,-0.001129,-0.004856,0.016890,0.082904,-0.015027,-0.015760,-0.073092
1,flow/0000/000,3MIDD_207,0.004825,0.013167,-0.008342,0.004825,0.033447,0.003804,0.007657,0.011317,0.069437,-0.006492,-0.007512,-0.035990
2,flow/0000/000,4MIDD_085_170,0.000724,0.007647,-0.006922,0.000724,0.004940,-0.002237,-0.002025,0.007703,0.045530,-0.006979,-0.005466,-0.040590
3,flow/0000/001,3MIDD_048,-0.001428,-0.001318,0.000110,0.001428,0.009239,-0.001365,-0.003875,0.005610,0.038850,-0.004182,-0.004245,-0.029611
4,flow/0000/001,3MIDD_207,0.008649,0.002362,0.006287,0.008649,0.053990,0.008472,0.003068,0.009948,0.065124,-0.001299,-0.001477,-0.011134
5,flow/0000/001,4MIDD_085_170,0.001099,-0.002203,-0.001104,0.001099,0.006962,0.000385,-0.002212,0.003599,0.024981,-0.002500,-0.003214,-0.018018
6,flow/0000/002,3MIDD_048,-0.011689,0.012277,-0.000588,0.011689,0.098050,-0.011630,-0.014156,0.010369,0.089339,0.001320,0.001261,0.008711
7,flow/0000/002,3MIDD_207,-0.001831,0.023789,-0.021958,0.001831,0.011482,-0.002170,0.003559,0.010202,0.074818,-0.008370,-0.008031,-0.063336
8,flow/0000/002,4MIDD_085_170,0.004159,0.007152,-0.002993,0.004159,0.034038,-0.003178,-0.010449,0.009466,0.068540,-0.005307,-0.006288,-0.034502
9,flow/0000/003,3MIDD_048,-0.030285,0.010152,0.020133,0.030285,0.262899,-0.030787,-0.005580,0.011831,0.086862,0.018454,0.018957,0.176037
10,flow/0000/003,3MIDD_207,0.016339,0.035065,-0.018726,0.016339,0.112074,0.017174,0.020664,0.015283,0.091273,0.001056,0.001891,0.020801
11,flow/0000/003,4MIDD_085_170,0.011651,0.022976,-0.011325,0.011651,0.085324,0.010300,-0.001328,0.011364,0.066526,0.000287,-0.001064,0.018798
12,flow/0000/004,3MIDD_048,0.000317,-0.016775,-0.016458,0.000317,0.001254,0.000079,-0.009725,0.014133,0.053799,-0.013815,-0.014054,-0.052545
13,flow/0000/004,3MIDD_207,0.012545,-0.012279,0.000265,0.012545,0.063492,0.012500,0.003891,0.014525,0.072135,-0.001981,-0.002025,-0.008642
14,flow/0000/004,4MIDD_085_170,-0.000782,-0.016950,-0.016168,0.000782,0.003370,0.000070,-0.025599,0.013541,0.063385,-0.012759,-0.013471,-0.060015
15,flow/0000/005,3MIDD_048,-0.007756,-0.008646,-0.000890,0.007756,0.065963,-0.009125,-0.016058,0.014500,0.088211,-0.006744,-0.005375,-0.022248
16,flow/0000/005,3MIDD_207,0.051553,-0.005572,0.045981,0.051553,0.290323,0.052997,0.006845,0.013287,0.076805,0.038266,0.039711,0.213518
17,flow/0000/005,4MIDD_085_170,-0.003303,-0.000900,0.002403,0.003303,0.023170,0.001193,0.002324,0.014022,0.092239,-0.010719,-0.012829,-0.069069
18,flow/0000/006,3MIDD_048,-0.020855,0.007618,0.013238,0.020855,0.160581,-0.021635,-0.005382,0.009947,0.079754,0.010908,0.011688,0.080827
19,flow/0000/006,3MIDD_207,0.006052,0.015287,-0.009236,0.006052,0.036751,0.005593,0.009665,0.013953,0.086541,-0.007902,-0.008361,-0.049790

data/precomputed/fig04/phase_paired.csv

,model_id,group,phase_index,phase_fraction,phase_deg,T_original,T_mirror,A,abs_A,S,abs_S,M,actual_reversal,T_negative,G,A_norm,S_norm
0,0,3MIDD_048,0,0.000000,0.00,-0.001514,0.002210,-0.001862,0.001862,0.000348,0.000348,0.001514,True,-0.007603,0.189787,-0.009811,0.001833
1,0,3MIDD_048,1,0.083333,1.25,0.008417,0.003819,0.002299,0.002299,0.006118,0.006118,-0.003819,False,-0.008375,0.186632,0.012319,0.032780
2,0,3MIDD_048,2,0.166667,2.50,0.018111,-0.003000,0.010555,0.010555,0.007556,0.007556,0.003000,True,0.008253,0.195354,0.054031,0.038676
3,0,3MIDD_048,3,0.250000,3.75,-0.001288,-0.004201,0.001457,0.001457,-0.002745,0.002745,-0.001288,False,0.005713,0.206107,0.007067,-0.013318
4,0,3MIDD_048,4,0.333333,5.00,0.003467,-0.007005,0.005236,0.005236,-0.001769,0.001769,0.003467,True,-0.017091,0.185331,0.028250,-0.009545
5,0,3MIDD_048,5,0.416667,6.25,0.015049,-0.004991,0.010020,0.010020,0.005029,0.005029,0.004991,True,-0.000625,0.182951,0.054767,0.027489
6,0,3MIDD_048,6,0.500000,7.50,0.007851,-0.001009,0.004430,0.004430,0.003421,0.003421,0.001009,True,0.001327,0.195866,0.022617,0.017464
7,0,3MIDD_048,7,0.583333,8.75,0.012710,-0.012755,0.012732,0.012732,-0.000023,0.000023,0.012710,True,-0.018812,0.206208,0.061746,-0.000111
8,0,3MIDD_048,8,0.666667,10.00,-0.000597,-0.003032,0.001217,0.001217,-0.001814,0.001814,-0.000597,False,-0.006172,0.188205,0.006468,-0.009640
9,0,3MIDD_048,9,0.750000,11.25,0.005577,0.006591,-0.000507,0.000507,0.006084,0.006084,-0.005577,False,0.002566,0.181644,-0.002792,0.033492
10,0,3MIDD_048,10,0.833333,12.50,0.012503,-0.004343,0.008423,0.008423,0.004080,0.004080,0.004343,True,-0.021030,0.193643,0.043499,0.021069
11,0,3MIDD_048,11,0.916667,13.75,0.001909,-0.010398,0.006154,0.006154,-0.004245,0.004245,0.001909,True,-0.015829,0.204491,0.030093,-0.020757
12,0,3MIDD_207,0,0.000000,0.00,0.017992,0.008342,0.004825,0.004825,0.013167,0.013167,-0.008342,False,0.023436,0.144257,0.033447,0.091277
13,0,3MIDD_207,1,0.083333,1.25,0.018227,0.004566,0.006830,0.006830,0.011396,0.011396,-0.004566,False,0.014651,0.146507,0.046621,0.077788
14,0,3MIDD_207,2,0.166667,2.50,0.012489,-0.004693,0.008591,0.008591,0.003898,0.003898,0.004693,True,0.015957,0.143457,0.059886,0.027173
15,0,3MIDD_207,3,0.250000,3.75,0.023320,0.000885,0.011218,0.011218,0.012102,0.012102,-0.000885,False,0.017500,0.141472,0.079291,0.085546
16,0,3MIDD_207,4,0.333333,5.00,0.016411,0.002652,0.006879,0.006879,0.009531,0.009531,-0.002652,False,0.024375,0.138124,0.049804,0.069007
17,0,3MIDD_207,5,0.416667,6.25,0.018496,0.003179,0.007658,0.007658,0.010837,0.010837,-0.003179,False,0.016133,0.142952,0.053573,0.075811
18,0,3MIDD_207,6,0.500000,7.50,0.019305,-0.003053,0.011179,0.011179,0.008126,0.008126,0.003053,True,0.004416,0.142107,0.078663,0.057182
19,0,3MIDD_207,7,0.583333,8.75,0.023813,-0.000406,0.012109,0.012109,0.011704,0.011704,0.000406,True,0.006504,0.143418,0.084433,0.081604

data/precomputed/fig04/geometry_geometry_contrasts.csv

,model_id,group,transform,A,S,delta_A,delta_S,equivariance_error_A,equivariance_error_S,abs_equivariance_A,...,normalized_error_S,D_robustness,relative_A,relative_S,A_raw_sign_flipped,S_raw_sign_flipped,A_equivariant_sign,S_equivariant_sign,reversal,baseline_reversal
0,0,3MIDD_048,identity,-0.001862,0.000348,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,False,False,True,True,True,True
1,0,3MIDD_048,LR,0.000415,0.000329,0.002277,-0.000019,0.001447,-0.000677,0.001447,...,0.003568,-0.004055,0.776936,1.946341,True,False,True,False,True,True
2,0,3MIDD_048,UD,0.000415,0.000329,0.002277,-0.000019,0.001447,-0.000677,0.001447,...,0.003568,-0.004055,0.776936,1.946341,True,False,True,False,True,True
3,0,3MIDD_048,rot180,-0.001862,0.000348,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,False,False,True,True,True,True
4,0,3MIDD_048,x_minus3,0.006537,0.005359,0.008399,0.005011,0.008399,0.005011,0.008399,...,0.026406,-0.017847,4.510299,14.403954,True,False,False,True,True,True
5,0,3MIDD_048,x_plus3,0.002283,-0.005331,0.004145,-0.005679,0.004145,-0.005679,0.004145,...,0.029921,0.008078,2.226202,16.321167,True,True,False,False,False,True
6,0,3MIDD_048,y_minus3,-0.005221,-0.008849,-0.003358,-0.009197,-0.003358,-0.009197,0.003358,...,0.048461,0.030765,1.803590,26.434611,False,True,True,False,False,True
7,0,3MIDD_048,y_plus3,0.005404,0.004929,0.007266,0.004582,0.007266,0.004582,0.007266,...,0.024141,-0.014146,3.902141,13.168268,True,False,False,True,True,True
8,0,3MIDD_207,identity,0.004825,0.013167,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,False,False,True,True,False,False
9,0,3MIDD_207,LR,-0.004291,0.014674,-0.009116,0.001507,-0.000534,-0.027842,0.000534,...,0.193001,0.189300,0.110644,2.114449,True,False,True,False,False,False
10,0,3MIDD_207,UD,-0.004291,0.014674,-0.009116,0.001507,-0.000534,-0.027842,0.000534,...,0.193001,0.189300,0.110644,2.114449,True,False,True,False,False,False
11,0,3MIDD_207,rot180,0.004825,0.013167,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,False,False,True,True,False,False
12,0,3MIDD_207,x_minus3,0.007279,0.013129,0.002454,-0.000039,0.002454,-0.000039,0.002454,...,0.000268,-0.016746,0.508686,0.002935,False,False,True,True,False,False
13,0,3MIDD_207,x_plus3,0.003013,0.008380,-0.001812,-0.004788,-0.001812,-0.004788,0.001812,...,0.033187,0.020625,0.375597,0.363590,False,False,True,True,False,False
14,0,3MIDD_207,y_minus3,0.003035,0.009840,-0.001790,-0.003327,-0.001790,-0.003327,0.001790,...,0.023063,0.010655,0.370996,0.252675,False,False,True,True,False,False
15,0,3MIDD_207,y_plus3,0.003273,0.014365,-0.001552,0.001198,-0.001552,0.001198,0.001552,...,0.008304,-0.002456,0.321705,0.090973,False,False,True,True,False,False
16,0,4MIDD_085_170,identity,0.000724,0.007647,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,False,False,True,True,False,False
17,0,4MIDD_085_170,LR,0.001006,0.011839,0.000281,0.004192,-0.001730,-0.019486,0.001730,...,0.132867,0.121070,2.388181,2.548267,False,False,False,False,False,False
18,0,4MIDD_085_170,UD,0.001006,0.011839,0.000281,0.004192,-0.001730,-0.019486,0.001730,...,0.132867,0.121070,2.388181,2.548267,False,False,False,False,False,False
19,0,4MIDD_085_170,rot180,0.000724,0.007647,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,False,False,True,True,False,False

data/precomputed/fig02/matched_control_bootstrap_summary.csv

,group,metric,mean,ci_low,ci_high,n_models
0,3MIDD_048,D_canonical_vs_random,-0.003473,-0.009431,0.003662,10
1,3MIDD_048,D_reflection_matched,-0.003265,-0.009456,0.003833,10
2,3MIDD_048,D_normalized,-0.001336,-0.041024,0.048952,10
3,3MIDD_048,canonical_abs_A,0.008979,0.003860,0.015081,10
4,3MIDD_048,mean_random_reflection_abs_A,0.012452,0.010301,0.014496,10
5,3MIDD_207,D_canonical_vs_random,-0.001748,-0.008364,0.008143,10
6,3MIDD_207,D_reflection_matched,-0.001670,-0.008413,0.008699,10
7,3MIDD_207,D_normalized,-0.007924,-0.045112,0.046552,10
8,3MIDD_207,canonical_abs_A,0.010494,0.003534,0.020799,10
9,3MIDD_207,mean_random_reflection_abs_A,0.012243,0.010540,0.013734,10
10,4MIDD_085_170,D_canonical_vs_random,-0.007615,-0.010706,-0.004469,10
11,4MIDD_085_170,D_reflection_matched,-0.008295,-0.011227,-0.005347,10
12,4MIDD_085_170,D_normalized,-0.040011,-0.057464,-0.020275,10
13,4MIDD_085_170,canonical_abs_A,0.003702,0.001336,0.006678,10
14,4MIDD_085_170,mean_random_reflection_abs_A,0.011317,0.009055,0.013245,10

data/precomputed/fig04/phase_model_phase_sensitivity.csv

,model_id,group,var_A,var_S,D,ratio,range_A,range_S,range_A_norm,range_S_norm,D_norm,A_sign_flips,S_sign_flips,reversal_phase_fraction
0,0,3MIDD_048,0.000020,0.000015,-5.339451e-06,0.733972,0.014595,0.011800,0.075612,0.061135,-0.000143,True,True,0.666667
1,0,3MIDD_207,0.000006,0.000007,1.068118e-06,1.178473,0.007998,0.010658,0.055914,0.074509,0.000052,False,False,0.333333
2,0,4MIDD_085_170,0.000009,0.000003,-5.330313e-06,0.382651,0.010277,0.006326,0.068191,0.041976,-0.000235,True,False,0.000000
3,1,3MIDD_048,0.000003,0.000003,7.476362e-08,1.024185,0.005995,0.005427,0.039151,0.035441,0.000003,True,True,0.500000
4,1,3MIDD_207,0.000002,0.000003,9.380659e-07,1.430048,0.004778,0.006356,0.029861,0.039722,0.000037,False,True,1.000000
5,1,4MIDD_085_170,0.000009,0.000002,-7.300602e-06,0.172742,0.008609,0.003994,0.054463,0.025266,-0.000292,True,True,0.750000
6,2,3MIDD_048,0.000032,0.000005,-2.630988e-05,0.172469,0.020118,0.009153,0.160170,0.072871,-0.001668,True,False,0.083333
7,2,3MIDD_207,0.000035,0.000019,-1.611182e-05,0.545316,0.016404,0.014529,0.107715,0.095403,-0.000695,True,False,0.000000
8,2,4MIDD_085_170,0.000027,0.000020,-6.920675e-06,0.744534,0.019232,0.014720,0.154914,0.118573,-0.000449,True,False,0.083333
9,3,3MIDD_048,0.000049,0.000005,-4.348288e-05,0.107683,0.025897,0.006818,0.226089,0.059525,-0.003314,False,False,0.583333
10,3,3MIDD_207,0.000039,0.000019,-2.071791e-05,0.475094,0.021572,0.017199,0.156962,0.125140,-0.001097,False,False,0.000000
11,3,4MIDD_085_170,0.000187,0.000025,-1.622633e-04,0.133885,0.035092,0.021592,0.257279,0.158304,-0.008722,True,False,0.000000
12,4,3MIDD_048,0.000113,0.000041,-7.203473e-05,0.361097,0.032256,0.021437,0.134592,0.089449,-0.001254,True,False,0.416667
13,4,3MIDD_207,0.000035,0.000038,2.465430e-06,1.069612,0.020697,0.020022,0.108502,0.104962,0.000068,False,True,0.916667
14,4,4MIDD_085_170,0.000063,0.000018,-4.477164e-05,0.287146,0.033409,0.014353,0.146866,0.063095,-0.000865,True,False,0.166667
15,5,3MIDD_048,0.000121,0.000033,-8.742763e-05,0.274800,0.034574,0.020099,0.260328,0.151337,-0.004957,True,True,0.666667
16,5,3MIDD_207,0.000088,0.000198,1.096809e-04,2.245132,0.032775,0.046814,0.196452,0.280603,0.003941,False,True,1.000000
17,5,4MIDD_085_170,0.000243,0.000063,-1.806472e-04,0.257124,0.048362,0.025712,0.347387,0.184692,-0.009321,True,True,0.666667
18,6,3MIDD_048,0.000043,0.000002,-4.176030e-05,0.039692,0.021806,0.005130,0.167163,0.039322,-0.002454,False,False,0.750000
19,6,3MIDD_207,0.000060,0.000024,-3.659646e-05,0.394322,0.024884,0.014903,0.149222,0.089370,-0.001316,True,False,0.333333

data/precomputed/fig04/phase_bootstrap.csv

,group,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,var_A,10,5.939411e-05,0.000043,0.000034,0.000087
1,3MIDD_048,var_S,10,1.397051e-05,0.000008,0.000007,0.000022
2,3MIDD_048,D,10,-4.542361e-05,-0.000037,-0.000071,-0.000024
3,3MIDD_048,ratio,10,3.548367e-01,0.263652,0.181106,0.559359
4,3MIDD_048,range_A_norm,10,1.443179e-01,0.150776,0.105462,0.185821
5,3MIDD_048,range_S_norm,10,6.826784e-02,0.060330,0.049608,0.091186
6,3MIDD_048,D_norm,10,-1.811257e-03,-0.001461,-0.002769,-0.000934
7,3MIDD_048,reversal_phase_fraction,10,5.833333e-01,0.625000,0.433333,0.725000
8,3MIDD_207,var_A,10,4.044602e-05,0.000037,0.000023,0.000059
9,3MIDD_207,var_S,10,3.955508e-05,0.000020,0.000016,0.000078
10,3MIDD_207,D,10,-8.909432e-07,-0.000008,-0.000020,0.000026
11,3MIDD_207,ratio,10,9.584036e-01,0.846509,0.655326,1.333661
12,3MIDD_207,range_A_norm,10,1.103596e-01,0.108108,0.078566,0.142078
13,3MIDD_207,range_S_norm,10,1.067394e-01,0.092386,0.074739,0.150716
14,3MIDD_207,D_norm,10,-4.139833e-06,-0.000175,-0.000683,0.000983
15,3MIDD_207,reversal_phase_fraction,10,5.500000e-01,0.500000,0.308333,0.791667
16,4MIDD_085_170,var_A,10,7.908426e-05,0.000048,0.000037,0.000130
17,4MIDD_085_170,var_S,10,1.906715e-05,0.000019,0.000009,0.000031
18,4MIDD_085_170,D,10,-6.001711e-05,-0.000031,-0.000101,-0.000025
19,4MIDD_085_170,ratio,10,3.238042e-01,0.267103,0.198287,0.469022

data/precomputed/fig04/geometry_paired.csv

,model_id,group,transform,T_original,T_mirror,A,abs_A,S,abs_S,M,actual_reversal,T_negative,G,A_norm,S_norm
0,0,3MIDD_048,identity,-0.001514,0.002210,-0.001862,0.001862,0.000348,0.000348,0.001514,True,-0.007603,0.189787,-0.009811,0.001833
1,0,3MIDD_048,LR,0.000745,-0.000086,0.000415,0.000415,0.000329,0.000329,0.000086,True,0.002110,0.188413,0.002205,0.001748
2,0,3MIDD_048,UD,0.000745,-0.000086,0.000415,0.000415,0.000329,0.000329,0.000086,True,0.002110,0.188413,0.002205,0.001748
3,0,3MIDD_048,rot180,-0.001514,0.002210,-0.001862,0.001862,0.000348,0.000348,0.001514,True,-0.007603,0.189787,-0.009811,0.001833
4,0,3MIDD_048,x_minus3,0.011896,-0.001177,0.006537,0.006537,0.005359,0.005359,0.001177,True,0.005245,0.190451,0.034321,0.028141
5,0,3MIDD_048,x_plus3,-0.003047,-0.007614,0.002283,0.002283,-0.005331,0.005331,-0.003047,False,0.002426,0.196674,0.011610,-0.027104
6,0,3MIDD_048,y_minus3,-0.014070,-0.003629,-0.005221,0.005221,-0.008849,0.008849,-0.003629,False,-0.013799,0.189911,-0.027490,-0.046597
7,0,3MIDD_048,y_plus3,0.010334,-0.000475,0.005404,0.005404,0.004929,0.004929,0.000475,True,-0.008697,0.194470,0.027789,0.025348
8,0,3MIDD_207,identity,0.017992,0.008342,0.004825,0.004825,0.013167,0.013167,-0.008342,False,0.023436,0.144257,0.033447,0.091277
9,0,3MIDD_207,LR,0.010383,0.018965,-0.004291,0.004291,0.014674,0.014674,-0.010383,False,0.008121,0.142916,-0.030025,0.102678
10,0,3MIDD_207,UD,0.010383,0.018965,-0.004291,0.004291,0.014674,0.014674,-0.010383,False,0.008121,0.142916,-0.030025,0.102678
11,0,3MIDD_207,rot180,0.017992,0.008342,0.004825,0.004825,0.013167,0.013167,-0.008342,False,0.023436,0.144257,0.033447,0.091277
12,0,3MIDD_207,x_minus3,0.020408,0.005849,0.007279,0.007279,0.013129,0.013129,-0.005849,False,0.013147,0.139719,0.052099,0.093965
13,0,3MIDD_207,x_plus3,0.011392,0.005367,0.003013,0.003013,0.008380,0.008380,-0.005367,False,0.015181,0.142218,0.021184,0.058922
14,0,3MIDD_207,y_minus3,0.012875,0.006805,0.003035,0.003035,0.009840,0.009840,-0.006805,False,0.030645,0.144027,0.021072,0.068322
15,0,3MIDD_207,y_plus3,0.017638,0.011092,0.003273,0.003273,0.014365,0.014365,-0.011092,False,0.020550,0.149739,0.021856,0.095935
16,0,4MIDD_085_170,identity,0.008371,0.006922,0.000724,0.000724,0.007647,0.007647,-0.006922,False,0.002033,0.146655,0.004940,0.052140
17,0,4MIDD_085_170,LR,0.012845,0.010833,0.001006,0.001006,0.011839,0.011839,-0.010833,False,0.006083,0.159343,0.006311,0.074299
18,0,4MIDD_085_170,UD,0.012845,0.010833,0.001006,0.001006,0.011839,0.011839,-0.010833,False,0.006083,0.159343,0.006311,0.074299
19,0,4MIDD_085_170,rot180,0.008371,0.006922,0.000724,0.000724,0.007647,0.007647,-0.006922,False,0.002033,0.146655,0.004940,0.052140

data/precomputed/fig04/geometry_bootstrap.csv

,group,transform,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,LR,delta_A,10,0.018279,0.015604,0.007655,0.030899
1,3MIDD_048,LR,delta_S,10,0.000326,0.000294,0.000006,0.000705
2,3MIDD_048,LR,normalized_error_A,10,0.004980,0.004213,0.002888,0.007156
3,3MIDD_048,LR,normalized_error_S,10,0.097151,0.111478,0.057734,0.137227
4,3MIDD_048,LR,D_robustness,10,0.092171,0.105838,0.052114,0.132773
5,3MIDD_048,UD,delta_A,10,0.018279,0.015604,0.007568,0.030984
6,3MIDD_048,UD,delta_S,10,0.000326,0.000294,0.000005,0.000706
7,3MIDD_048,UD,normalized_error_A,10,0.004980,0.004213,0.002898,0.007160
8,3MIDD_048,UD,normalized_error_S,10,0.097151,0.111478,0.057406,0.136478
9,3MIDD_048,UD,D_robustness,10,0.092171,0.105838,0.051676,0.133586
10,3MIDD_048,identity,delta_A,10,0.000000,0.000000,0.000000,0.000000
11,3MIDD_048,identity,delta_S,10,0.000000,0.000000,0.000000,0.000000
12,3MIDD_048,identity,normalized_error_A,10,0.000000,0.000000,0.000000,0.000000
13,3MIDD_048,identity,normalized_error_S,10,0.000000,0.000000,0.000000,0.000000
14,3MIDD_048,identity,D_robustness,10,0.000000,0.000000,0.000000,0.000000
15,3MIDD_048,rot180,delta_A,10,0.000000,0.000000,0.000000,0.000000
16,3MIDD_048,rot180,delta_S,10,0.000000,0.000000,0.000000,0.000000
17,3MIDD_048,rot180,normalized_error_A,10,0.000000,0.000000,0.000000,0.000000
18,3MIDD_048,rot180,normalized_error_S,10,0.000000,0.000000,0.000000,0.000000
19,3MIDD_048,rot180,D_robustness,10,0.000000,0.000000,0.000000,0.000000

data/precomputed/fig02/official50_shuffle_model_metrics.csv

,model_id,group,canonical_reflection_abs_A,canonical_reflection_abs_A_norm,shuffle_mean_abs_A,shuffle_median_abs_A,difference_mean,difference_median,canonical_rank,canonical_percentile
0,flow/0000/000,3MIDD_048,0.001129,0.005921,0.016890,0.013699,-0.015760,-0.012569,2,0.1
1,flow/0000/000,3MIDD_207,0.003804,0.026482,0.011317,0.010707,-0.007512,-0.006902,2,0.1
2,flow/0000/000,4MIDD_085_170,0.002237,0.014680,0.007703,0.006916,-0.005466,-0.004679,4,0.3
3,flow/0000/001,3MIDD_048,0.001365,0.008860,0.005610,0.004597,-0.004245,-0.003232,4,0.3
4,flow/0000/001,3MIDD_207,0.008472,0.052923,0.009948,0.009221,-0.001477,-0.000749,4,0.3
5,flow/0000/001,4MIDD_085_170,0.000385,0.002440,0.003599,0.002283,-0.003214,-0.001898,4,0.3
6,flow/0000/002,3MIDD_048,0.011630,0.097368,0.010369,0.008548,0.001261,0.003081,7,0.6
7,flow/0000/002,3MIDD_207,0.002170,0.013541,0.010202,0.008948,-0.008031,-0.006778,2,0.1
8,flow/0000/002,4MIDD_085_170,0.003178,0.024694,0.009466,0.009506,-0.006288,-0.006328,3,0.2
9,flow/0000/003,3MIDD_048,0.030787,0.267082,0.011831,0.010455,0.018957,0.020333,10,0.9
10,flow/0000/003,3MIDD_207,0.017174,0.117331,0.015283,0.014025,0.001891,0.003149,7,0.6
11,flow/0000/003,4MIDD_085_170,0.010300,0.075201,0.011364,0.009140,-0.001064,0.001160,7,0.6
12,flow/0000/004,3MIDD_048,0.000079,0.000312,0.014133,0.010652,-0.014054,-0.010573,1,0.0
13,flow/0000/004,3MIDD_207,0.012500,0.063237,0.014525,0.012045,-0.002025,0.000455,6,0.5
14,flow/0000/004,4MIDD_085_170,0.000070,0.000302,0.013541,0.012979,-0.013471,-0.012909,1,0.0
15,flow/0000/005,3MIDD_048,0.009125,0.077788,0.014500,0.017206,-0.005375,-0.008081,5,0.4
16,flow/0000/005,3MIDD_207,0.052997,0.294728,0.013287,0.010307,0.039711,0.042690,11,1.0
17,flow/0000/005,4MIDD_085_170,0.001193,0.008190,0.014022,0.012153,-0.012829,-0.010961,2,0.1
18,flow/0000/006,3MIDD_048,0.021635,0.166304,0.009947,0.009266,0.011688,0.012369,11,1.0
19,flow/0000/006,3MIDD_207,0.005593,0.034598,0.013953,0.009561,-0.008361,-0.003968,4,0.3

data/precomputed/fig02/official50_shuffle_draw_metrics.csv

,model_id,group,draw,A,S,G,abs_A,abs_A_norm
0,flow/0000/000,3MIDD_048,0,-0.016622,-0.000142,0.207586,0.016622,0.080072
1,flow/0000/000,3MIDD_048,1,-0.019614,0.012885,0.193637,0.019614,0.101294
2,flow/0000/000,3MIDD_048,2,-0.013826,0.005237,0.195764,0.013826,0.070628
3,flow/0000/000,3MIDD_048,3,0.012970,-0.001163,0.192636,0.012970,0.067328
4,flow/0000/000,3MIDD_048,4,0.022118,0.001387,0.204129,0.022118,0.108353
5,flow/0000/000,3MIDD_048,5,0.013571,-0.025748,0.197826,0.013571,0.068600
6,flow/0000/000,3MIDD_048,6,-0.000128,0.025088,0.178666,0.000128,0.000716
7,flow/0000/000,3MIDD_048,7,0.008200,-0.022246,0.203361,0.008200,0.040324
8,flow/0000/000,3MIDD_048,8,-0.053093,0.024083,0.213227,0.053093,0.248998
9,flow/0000/000,3MIDD_048,9,0.008753,-0.021729,0.204862,0.008753,0.042727
10,flow/0000/000,3MIDD_207,0,-0.007081,0.017555,0.170846,0.007081,0.041447
11,flow/0000/000,3MIDD_207,1,0.001806,0.003691,0.172619,0.001806,0.010461
12,flow/0000/000,3MIDD_207,2,-0.006974,0.010728,0.152180,0.006974,0.045830
13,flow/0000/000,3MIDD_207,3,-0.012328,0.014495,0.164971,0.012328,0.074726
14,flow/0000/000,3MIDD_207,4,-0.016358,0.018957,0.181451,0.016358,0.090152
15,flow/0000/000,3MIDD_207,5,-0.018341,0.011559,0.162434,0.018341,0.112914
16,flow/0000/000,3MIDD_207,6,0.009384,0.009253,0.162654,0.009384,0.057693
17,flow/0000/000,3MIDD_207,7,0.012029,-0.000939,0.156979,0.012029,0.076629
18,flow/0000/000,3MIDD_207,8,0.004684,0.006957,0.163191,0.004684,0.028703
19,flow/0000/000,3MIDD_207,9,0.024182,0.008380,0.155198,0.024182,0.155812

data/precomputed/fig02/official50_shuffle_summary.csv

,group,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,canonical_reflection_abs_A,50,0.010622,0.007087,0.007419,0.014431
1,3MIDD_048,shuffle_mean_abs_A,50,0.013307,0.012147,0.011744,0.015031
2,3MIDD_048,difference_mean,50,-0.002685,-0.003728,-0.005633,0.000589
3,3MIDD_048,difference_median,50,-0.001072,-0.003075,-0.004060,0.002438
4,3MIDD_048,canonical_percentile,50,0.390000,0.400000,0.312000,0.468000
5,3MIDD_207,canonical_reflection_abs_A,50,0.009395,0.006050,0.006979,0.012295
6,3MIDD_207,shuffle_mean_abs_A,50,0.012602,0.011247,0.010980,0.014304
7,3MIDD_207,difference_mean,50,-0.003206,-0.003694,-0.005870,-0.000308
8,3MIDD_207,difference_median,50,-0.001762,-0.001721,-0.004551,0.001175
9,3MIDD_207,canonical_percentile,50,0.414000,0.400000,0.334000,0.498000
10,4MIDD_085_170,canonical_reflection_abs_A,50,0.003400,0.002620,0.002584,0.004369
11,4MIDD_085_170,shuffle_mean_abs_A,50,0.011699,0.011433,0.010312,0.013183
12,4MIDD_085_170,difference_mean,50,-0.008299,-0.007550,-0.009766,-0.006922
13,4MIDD_085_170,difference_median,50,-0.007135,-0.006648,-0.008669,-0.005730
14,4MIDD_085_170,canonical_percentile,50,0.176000,0.100000,0.130000,0.228000

data/precomputed/fig02/official50_static_physical_context.csv

,model_id,group,condition,A,T,G
0,flow/0000/000,3MIDD_048,canonical image/LR,-0.001129,-0.001514,0.190749
1,flow/0000/000,3MIDD_048,canonical Original/Mirror,-0.001862,-0.001514,0.189787
2,flow/0000/000,3MIDD_207,canonical image/LR,0.003804,0.017992,0.143663
3,flow/0000/000,3MIDD_207,canonical Original/Mirror,0.004825,0.017992,0.144257
4,flow/0000/000,4MIDD_085_170,canonical image/LR,-0.002237,0.008371,0.152376
5,flow/0000/000,4MIDD_085_170,canonical Original/Mirror,0.000724,0.008371,0.146655
6,flow/0000/000,3MIDD_048,random image/LR,-0.005653,0.020206,0.254577
7,flow/0000/000,3MIDD_048,physical propeller,9.774848,9.830155,10.730623
8,flow/0000/000,3MIDD_048,uniform singleton,NaN,0.037707,0.159750
9,flow/0000/001,3MIDD_048,canonical image/LR,-0.001365,-0.002747,0.154042
10,flow/0000/001,3MIDD_048,canonical Original/Mirror,-0.001428,-0.002747,0.154596
11,flow/0000/001,3MIDD_207,canonical image/LR,0.008472,0.011011,0.160074
12,flow/0000/001,3MIDD_207,canonical Original/Mirror,0.008649,0.011011,0.160199
13,flow/0000/001,4MIDD_085_170,canonical image/LR,0.000385,-0.001104,0.157897
14,flow/0000/001,4MIDD_085_170,canonical Original/Mirror,0.001099,-0.001104,0.157871
15,flow/0000/001,3MIDD_048,random image/LR,-0.002013,0.004663,0.151669
16,flow/0000/001,3MIDD_048,physical propeller,10.814424,10.952406,11.563048
17,flow/0000/001,3MIDD_048,uniform singleton,NaN,-0.006854,0.200933
18,flow/0000/002,3MIDD_048,canonical image/LR,-0.011630,0.000588,0.119441
19,flow/0000/002,3MIDD_048,canonical Original/Mirror,-0.011689,0.000588,0.119211

data/precomputed/fig02/official50_controls_metrics.csv

,model_id,condition,reused,mean_flow_magnitude,mean_signed_tangent,mean_abs_tangent,signed_tangent_ratio,rotation_coherence,mean_signed_radial,annulus_positions,annulus_receptors
0,flow/0000/000,static:3MIDD_048__original,True,0.195674,-0.001514,0.113804,-0.007738,0.013305,0.027576,698,698
1,flow/0000/000,static:3MIDD_048__mirror,True,0.183901,0.002210,0.106631,0.012017,0.020726,0.047301,698,698
2,flow/0000/000,static:3MIDD_048__negative,True,0.166366,-0.007603,0.086875,-0.045701,0.087517,0.057086,698,698
3,flow/0000/000,static:3MIDD_048__original_LR,True,0.185824,0.000745,0.107399,0.004007,0.006933,0.048547,698,698
4,flow/0000/000,static:3MIDD_048__negative_LR,True,0.182567,0.002110,0.105662,0.011555,0.019966,0.043941,698,698
5,flow/0000/000,static:3MIDD_048__shuffle_00,True,0.240535,-0.016763,0.127533,-0.069692,0.131444,0.054855,698,698
6,flow/0000/000,static:3MIDD_048__shuffle_00_LR,True,0.174638,0.016480,0.097621,0.094367,0.168818,0.037354,698,698
7,flow/0000/000,static:3MIDD_048__shuffle_01,True,0.191411,-0.006729,0.112106,-0.035155,0.060023,0.040757,698,698
8,flow/0000/000,static:3MIDD_048__shuffle_01_LR,True,0.195862,0.032499,0.116214,0.165929,0.279650,0.045477,698,698
9,flow/0000/000,static:3MIDD_048__shuffle_02,True,0.200499,-0.008589,0.124009,-0.042841,0.069265,0.032057,698,698
10,flow/0000/000,static:3MIDD_048__shuffle_02_LR,True,0.191030,0.019063,0.098516,0.099792,0.193504,0.070848,698,698
11,flow/0000/000,static:3MIDD_048__shuffle_03,True,0.196776,0.011807,0.108188,0.060003,0.109135,0.023609,698,698
12,flow/0000/000,static:3MIDD_048__shuffle_03_LR,True,0.188496,-0.014132,0.104336,-0.074974,0.135450,0.030814,698,698
13,flow/0000/000,static:3MIDD_048__shuffle_04,True,0.207515,0.023505,0.108057,0.113268,0.217520,0.051826,698,698
14,flow/0000/000,static:3MIDD_048__shuffle_04_LR,True,0.200743,-0.020731,0.108550,-0.103272,0.190983,0.024290,698,698
15,flow/0000/000,static:3MIDD_048__shuffle_05,True,0.191325,-0.012177,0.109782,-0.063646,0.110921,0.056874,698,698
16,flow/0000/000,static:3MIDD_048__shuffle_05_LR,True,0.204328,-0.039319,0.135439,-0.192431,0.290307,0.064497,698,698
17,flow/0000/000,static:3MIDD_048__shuffle_06,True,0.190045,0.024960,0.102099,0.131339,0.244473,0.086644,698,698
18,flow/0000/000,static:3MIDD_048__shuffle_06_LR,True,0.167286,0.025216,0.097139,0.150737,0.259590,0.051186,698,698
19,flow/0000/000,static:3MIDD_048__shuffle_07,True,0.197699,-0.014046,0.139482,-0.071047,0.100700,0.039815,698,698

data/precomputed/fig04/official50_phase_model_metrics.csv

,model_id,group,n_phases,A_phase0,A_mean,A_median,A_SD,A_IQR,A_MAD,A_min,...,sign_consistency_with_phase_mean,phase0_vs_mean_sign_agreement,A_sign_changes,phasewise_reversal_count,phasewise_reversal_fraction,mean_T_original,mean_T_mirror,mean_S,reversal_of_phase_averaged_pair,phase0_reversal
0,flow/0000/000,3MIDD_048,12,-0.001862,0.005013,0.004833,0.004679,0.007426,0.003603,-0.001862,...,0.833333,False,True,8,0.666667,0.006849,-0.003176,0.001837,True,True
1,flow/0000/001,3MIDD_048,12,-0.001428,-0.000971,-0.001360,0.001836,0.002281,0.001664,-0.003878,...,0.583333,True,True,6,0.500000,-0.003006,-0.001064,-0.002035,False,True
2,flow/0000/002,3MIDD_048,12,-0.011689,-0.003915,-0.004202,0.005889,0.007038,0.004174,-0.015451,...,0.666667,True,True,1,0.083333,0.008221,0.016051,0.012136,False,False
3,flow/0000/003,3MIDD_048,12,-0.030285,-0.016562,-0.016445,0.007291,0.008280,0.005475,-0.030285,...,1.000000,True,False,7,0.583333,-0.002384,0.030739,0.014178,True,True
4,flow/0000/004,3MIDD_048,12,0.000317,0.007642,0.009909,0.011090,0.016802,0.008063,-0.009569,...,0.750000,True,True,5,0.416667,-0.006345,-0.021628,-0.013987,False,False
5,flow/0000/005,3MIDD_048,12,-0.007756,0.010906,0.011688,0.011468,0.017367,0.009138,-0.007756,...,0.750000,False,True,8,0.666667,0.005115,-0.016697,-0.005791,True,False
6,flow/0000/006,3MIDD_048,12,-0.020855,-0.013909,-0.011941,0.006888,0.012532,0.004648,-0.026407,...,1.000000,True,False,9,0.750000,-0.005243,0.022575,0.008666,True,True
7,flow/0000/007,3MIDD_048,12,-0.001204,0.008659,0.010896,0.006870,0.013250,0.004075,-0.001614,...,0.750000,False,True,9,0.750000,0.005399,-0.011919,-0.003260,True,False
8,flow/0000/008,3MIDD_048,12,-0.006437,-0.010506,-0.011198,0.006308,0.004753,0.002666,-0.021439,...,0.916667,True,True,12,1.000000,-0.011486,0.009527,-0.000980,True,True
9,flow/0000/009,3MIDD_048,12,-0.008111,0.008989,0.012840,0.012078,0.021836,0.008017,-0.008692,...,0.666667,False,True,5,0.416667,0.023215,0.005237,0.014226,False,False
10,flow/0000/010,3MIDD_048,12,0.000650,0.003447,0.003356,0.005733,0.007177,0.003678,-0.007282,...,0.750000,True,True,8,0.666667,0.003855,-0.003039,0.000408,True,False
11,flow/0000/011,3MIDD_048,12,-0.002349,-0.003805,-0.002103,0.003749,0.003629,0.001778,-0.012624,...,0.916667,True,True,0,0.000000,-0.023636,-0.016025,-0.019830,False,False
12,flow/0000/012,3MIDD_048,12,-0.019964,-0.016645,-0.017722,0.006396,0.008114,0.004268,-0.025292,...,1.000000,True,False,1,0.083333,0.009526,0.042815,0.026170,False,False
13,flow/0000/013,3MIDD_048,12,-0.008501,-0.003204,-0.001832,0.003937,0.005949,0.001762,-0.010290,...,0.916667,True,True,6,0.500000,-0.003715,0.002693,-0.000511,True,True
14,flow/0000/014,3MIDD_048,12,-0.018068,-0.017622,-0.018326,0.006620,0.008546,0.004532,-0.027172,...,1.000000,True,False,6,0.500000,0.001254,0.036498,0.018876,False,True
15,flow/0000/015,3MIDD_048,12,-0.008969,-0.006852,-0.006267,0.002084,0.002038,0.000778,-0.011853,...,1.000000,True,False,11,0.916667,-0.004417,0.009286,0.002434,True,True
16,flow/0000/016,3MIDD_048,12,-0.007842,0.015776,0.021940,0.014485,0.022049,0.007930,-0.007842,...,0.833333,False,True,10,0.833333,0.016062,-0.015491,0.000285,True,True
17,flow/0000/017,3MIDD_048,12,-0.033205,-0.025230,-0.022955,0.008613,0.015739,0.007481,-0.037930,...,1.000000,True,False,11,0.916667,-0.039005,0.011455,-0.013775,True,True
18,flow/0000/018,3MIDD_048,12,-0.011893,-0.003998,-0.003574,0.005181,0.007090,0.003976,-0.012857,...,0.666667,True,True,6,0.500000,-0.005286,0.002710,-0.001288,True,True
19,flow/0000/019,3MIDD_048,12,-0.013613,-0.000119,-0.000148,0.007028,0.005770,0.004160,-0.013613,...,0.500000,True,True,0,0.000000,0.030409,0.030646,0.030528,False,False

data/precomputed/fig04/official50_phase_pairs.csv

,model_id,group,phase_index,T_original,T_mirror,A,S,G,actual_reversal
0,0,3MIDD_048,0,-0.001514,0.002210,-0.001862,0.000348,0.189787,True
1,0,3MIDD_048,1,0.008417,0.003819,0.002299,0.006118,0.186632,False
2,0,3MIDD_048,2,0.018111,-0.003000,0.010555,0.007556,0.195354,True
3,0,3MIDD_048,3,-0.001288,-0.004201,0.001457,-0.002745,0.206107,False
4,0,3MIDD_048,4,0.003467,-0.007005,0.005236,-0.001769,0.185331,True
5,0,3MIDD_048,5,0.015049,-0.004991,0.010020,0.005029,0.182951,True
6,0,3MIDD_048,6,0.007851,-0.001009,0.004430,0.003421,0.195866,True
7,0,3MIDD_048,7,0.012710,-0.012755,0.012732,-0.000023,0.206208,True
8,0,3MIDD_048,8,-0.000597,-0.003032,0.001217,-0.001814,0.188205,False
9,0,3MIDD_048,9,0.005577,0.006591,-0.000507,0.006084,0.181644,False
10,0,3MIDD_048,10,0.012503,-0.004343,0.008423,0.004080,0.193643,True
11,0,3MIDD_048,11,0.001909,-0.010398,0.006154,-0.004245,0.204491,True
12,1,3MIDD_048,0,-0.002747,0.000110,-0.001428,-0.001318,0.154596,True
13,1,3MIDD_048,1,-0.003373,-0.004265,0.000446,-0.003819,0.154457,False
14,1,3MIDD_048,2,-0.003188,-0.003999,0.000406,-0.003593,0.152628,False
15,1,3MIDD_048,3,-0.004005,0.003752,-0.003878,-0.000127,0.152722,True
16,1,3MIDD_048,4,-0.002400,0.001164,-0.001782,-0.000618,0.152363,True
17,1,3MIDD_048,5,-0.004648,-0.005055,0.000204,-0.004852,0.152713,False
18,1,3MIDD_048,6,-0.005965,0.001360,-0.003663,-0.002302,0.152586,True
19,1,3MIDD_048,7,-0.001456,0.001844,-0.001650,0.000194,0.153513,True

data/precomputed/fig04/official50_phase_reliability.csv

,n_models,n_phases,icc_absolute,icc_consistency,SS_model,SS_phase,SS_residual,SS_total,SS_model_fraction,SS_phase_fraction,...,observed_within_to_between,ci_low,ci_high,phase0_mean_A,phase_average_mean_A,phase0_mean_sign_agreement,phase0_mean_spearman,sign_changing_models,mean_phasewise_reversal_fraction,reversal_of_phase_averaged_pair
0,50,12,0.764701,0.81718,0.096557,0.007843,0.019439,0.123838,0.779698,0.06333,...,0.302069,0.59631,0.867805,-0.009346,-0.003777,0.78,0.760384,34,0.435,23

data/precomputed/fig04/official50_performance_phase_join.csv

,model_id,fixed_eval_epe,n_samples,diagnostic_not_held_out,elapsed_seconds,A,S,M,actual_reversal,abs_A,normalized_SD
0,flow/0000/000,4.799515,15,True,6.478928,-0.001862,0.000348,0.001514,True,0.001862,0.024243
1,flow/0000/001,4.726934,15,True,6.439426,-0.001428,-0.001318,0.000110,True,0.001428,0.011992
2,flow/0000/002,4.721150,15,True,6.421438,-0.011689,0.012277,-0.000588,False,0.011689,0.046888
3,flow/0000/003,4.755511,15,True,6.472989,-0.030285,0.010152,0.020133,True,0.030285,0.063655
4,flow/0000/004,4.852283,15,True,6.395401,0.000317,-0.016775,-0.016458,False,0.000317,0.046277
5,flow/0000/005,4.841967,15,True,6.465468,-0.007756,-0.008646,-0.000890,False,0.007756,0.086349
6,flow/0000/006,4.725084,15,True,6.504832,-0.020855,0.007618,0.013238,True,0.020855,0.052799
7,flow/0000/007,4.745892,15,True,6.485099,-0.001204,-0.005489,-0.004285,False,0.001204,0.031762
8,flow/0000/008,4.843355,15,True,6.429967,-0.006437,-0.002472,0.003964,True,0.006437,0.037862
9,flow/0000/009,4.777329,15,True,6.919027,-0.008111,0.010010,-0.001899,False,0.008111,0.058605
10,flow/0000/010,4.770639,15,True,6.885167,0.000650,0.000824,-0.000174,False,0.000650,0.035664
11,flow/0000/011,4.828132,15,True,6.930237,-0.002349,-0.021973,-0.019623,False,0.002349,0.015087
12,flow/0000/012,4.794592,15,True,6.977913,-0.019964,0.025662,-0.005698,False,0.019964,0.022539
13,flow/0000/013,4.836042,15,True,7.227693,-0.008501,-0.001033,0.007469,True,0.008501,0.042826
14,flow/0000/014,4.799156,15,True,7.327815,-0.018068,0.016666,0.001403,True,0.018068,0.030629
15,flow/0000/015,4.807579,15,True,6.968568,-0.008969,0.001992,0.006977,True,0.008969,0.015025
16,flow/0000/016,4.796319,15,True,6.953803,-0.007842,-0.005353,0.002489,True,0.007842,0.057522
17,flow/0000/017,4.799662,15,True,7.105781,-0.033205,-0.005874,0.027331,True,0.033205,0.031056
18,flow/0000/018,4.813165,15,True,7.182000,-0.011893,-0.006215,0.005678,True,0.011893,0.041746
19,flow/0000/019,4.847108,15,True,7.334903,-0.013613,0.031374,-0.017761,False,0.013613,0.025298

data/precomputed/fig05/official50_performance_primary_relations.csv

,metric,n_models,spearman,p,ci_low,ci_high,holm_primary_three
0,A,50,0.283842,0.045761,-0.002557,0.533809,0.091522
1,abs_A,50,-0.214790,0.134153,-0.502454,0.096362,0.134153
2,normalized_SD,50,-0.326194,0.020787,-0.585733,-0.023088,0.062360

data/precomputed/fig04/receptor_geometry.csv

,receptor,y,x,radius,nearest_neighbor_spacing,period_arc,period_over_spacing,angular_spacing_rad,full_annulus,outer_ROI
0,0,-195.0,0.0,195.000000,13.0,51.050881,3.926991,0.066667,True,True
1,1,-188.0,13.0,188.448932,13.0,49.335815,3.795063,0.068984,True,True
2,2,-182.0,26.0,183.847763,13.0,48.131232,3.702402,0.070711,True,True
3,3,-175.0,39.0,179.293056,13.0,46.938812,3.610678,0.072507,True,True
4,4,-169.0,52.0,176.819117,13.0,46.291136,3.560857,0.073521,True,True
5,5,-162.0,65.0,174.553717,13.0,45.698056,3.515235,0.074476,True,True
6,6,-156.0,78.0,174.413302,13.0,45.661296,3.512407,0.074536,True,True
7,7,-149.0,91.0,174.590951,13.0,45.707804,3.515985,0.074460,True,True
8,8,-143.0,104.0,176.819117,13.0,46.291136,3.560857,0.073521,True,True
9,9,-136.0,117.0,179.401784,13.0,46.967277,3.612867,0.072463,True,True
10,10,-130.0,130.0,183.847763,13.0,48.131232,3.702402,0.070711,True,True
11,11,-123.0,143.0,188.621314,13.0,49.380944,3.798534,0.068921,True,True
12,12,-117.0,156.0,195.000000,13.0,51.050881,3.926991,0.066667,True,True
13,13,-110.0,169.0,201.645729,13.0,52.790728,4.060825,0.064470,True,True
14,14,-104.0,182.0,209.618701,13.0,54.878048,4.221388,0.062017,True,True
15,15,-97.0,195.0,217.793480,13.0,57.018200,4.386015,0.059690,False,False
16,16,-188.0,-13.0,188.448932,13.0,49.335815,3.795063,0.068984,True,True
17,17,-182.0,0.0,182.000000,13.0,47.647489,3.665191,0.071429,True,True
18,18,-175.0,13.0,175.482193,13.0,45.941131,3.533933,0.074082,True,True
19,19,-169.0,26.0,170.988304,13.0,44.764633,3.443433,0.076029,True,True

data/precomputed/fig04/radial_radial_model_phase_metrics.csv

,model_id,group,phase_index,ROI,n_receptors,T_original,T_mirror,A,S,G,M,raw_reversal
0,0,3MIDD_048,0,full,698,-0.001514,0.002210,-0.001862,0.000348,0.189787,0.001514,True
1,0,3MIDD_048,0,outer,532,-0.001988,-0.001133,-0.000427,-0.001561,0.182719,-0.001133,False
2,0,3MIDD_048,0,radial_0,38,-0.003957,0.011734,-0.007845,0.003888,0.188725,0.003957,True
3,0,3MIDD_048,0,radial_1,74,0.002283,0.017390,-0.007554,0.009836,0.220096,-0.002283,False
4,0,3MIDD_048,0,radial_2,94,-0.002477,0.004264,-0.003371,0.000893,0.210553,0.002477,True
5,0,3MIDD_048,0,radial_3,114,-0.013477,-0.012616,-0.000431,-0.013046,0.189891,-0.012616,False
6,0,3MIDD_048,0,radial_4,146,-0.016607,-0.013185,-0.001711,-0.014896,0.191257,-0.013185,False
7,0,3MIDD_048,0,radial_5,154,0.012185,0.010361,0.000912,0.011273,0.181476,-0.010361,False
8,0,3MIDD_048,0,radial_6,78,0.015923,0.015085,0.000419,0.015504,0.150031,-0.015085,False
9,0,3MIDD_048,1,full,698,0.008417,0.003819,0.002299,0.006118,0.186632,-0.003819,False
10,0,3MIDD_048,1,outer,532,0.011836,0.000861,0.005487,0.006348,0.175680,-0.000861,False
11,0,3MIDD_048,1,radial_0,38,-0.002970,0.009309,-0.006139,0.003170,0.204352,0.002970,True
12,0,3MIDD_048,1,radial_1,74,-0.002363,0.018761,-0.010562,0.008199,0.231707,0.002363,True
13,0,3MIDD_048,1,radial_2,94,-0.000129,0.004522,-0.002326,0.002196,0.209785,0.000129,True
14,0,3MIDD_048,1,radial_3,114,-0.004171,-0.011612,0.003720,-0.007891,0.182904,-0.004171,False
15,0,3MIDD_048,1,radial_4,146,0.001174,-0.009410,0.005292,-0.004118,0.180878,0.001174,True
16,0,3MIDD_048,1,radial_5,154,0.028596,0.016564,0.006016,0.022580,0.178289,-0.016564,False
17,0,3MIDD_048,1,radial_6,78,0.026604,0.008269,0.009168,0.017437,0.140021,-0.008269,False
18,0,3MIDD_048,2,full,698,0.018111,-0.003000,0.010555,0.007556,0.195354,0.003000,True
19,0,3MIDD_048,2,outer,532,0.024528,-0.006319,0.015423,0.009104,0.183899,0.006319,True

data/precomputed/fig04/radial_ROI_comparison.csv

,group,phase_index,full_mean_A,outer_mean_A,sign_agreement,spearman,full_reversal,outer_reversal,mean_absolute_delta
0,3MIDD_048,0,-0.008931,-0.011027,0.9,0.830303,5,5,0.003502
1,3MIDD_048,1,0.000923,0.000674,1.0,0.987879,4,4,0.002349
2,3MIDD_048,2,0.005980,0.005193,0.9,0.975758,6,8,0.003800
3,3MIDD_048,3,-0.008250,-0.012323,1.0,0.915152,5,5,0.004073
4,3MIDD_048,4,0.000978,0.001407,1.0,0.975758,7,5,0.002106
5,3MIDD_048,5,0.004380,0.006093,1.0,0.963636,6,7,0.003189
6,3MIDD_048,6,-0.006311,-0.007607,1.0,0.951515,7,5,0.002295
7,3MIDD_048,7,0.002511,0.002959,0.9,1.000000,8,7,0.002599
8,3MIDD_048,8,0.006606,0.007524,1.0,0.951515,6,7,0.002136
9,3MIDD_048,9,-0.007280,-0.010015,0.9,0.975758,4,4,0.003198
10,3MIDD_048,10,0.000244,0.001407,1.0,0.987879,6,6,0.003275
11,3MIDD_048,11,0.003564,0.005805,1.0,0.987879,6,8,0.003167
12,3MIDD_207,0,0.013239,0.017636,0.9,0.927273,5,3,0.004482
13,3MIDD_207,1,0.009323,0.012308,0.9,0.987879,6,5,0.003696
14,3MIDD_207,2,0.011879,0.015671,0.9,0.939394,7,7,0.003791
15,3MIDD_207,3,0.016870,0.021158,1.0,0.975758,6,7,0.004288
16,3MIDD_207,4,0.013162,0.015491,0.9,0.939394,5,5,0.002613
17,3MIDD_207,5,0.012668,0.014408,1.0,0.987879,4,5,0.003220
18,3MIDD_207,6,0.021212,0.025788,1.0,0.963636,8,9,0.004850
19,3MIDD_207,7,0.012229,0.014448,0.9,0.951515,5,4,0.002785

data/precomputed/fig04/phase_reliability_icc_bootstrap.csv

,group,metric,estimate,ci_low,ci_high,valid_draws,undefined_draws,bootstrap_unit,n_models,n_fixed_phases
0,3MIDD_048,icc_absolute,0.612969,0.323132,0.703770,10000,0,whole selected model,10,12
1,3MIDD_048,icc_consistency,0.740937,0.510491,0.889521,10000,0,whole selected model,10,12
2,3MIDD_048,model_variance,0.000103,0.000034,0.000144,10000,0,whole selected model,10,12
3,3MIDD_048,phase_variance,0.000029,0.000005,0.000068,10000,0,whole selected model,10,12
4,3MIDD_048,residual_variance,0.000036,0.000015,0.000055,10000,0,whole selected model,10,12
5,3MIDD_048,within_phase_total_variance,0.000065,0.000037,0.000095,10000,0,whole selected model,10,12
6,3MIDD_048,observed_within_to_between,0.613527,0.414160,1.959227,10000,0,whole selected model,10,12
7,3MIDD_207,icc_absolute,0.823459,0.331908,0.894904,10000,0,whole selected model,10,12
8,3MIDD_207,icc_consistency,0.848845,0.415716,0.921848,10000,0,whole selected model,10,12
9,3MIDD_207,model_variance,0.000206,0.000016,0.000452,10000,0,whole selected model,10,12
10,3MIDD_207,phase_variance,0.000007,0.000002,0.000025,10000,0,whole selected model,10,12
11,3MIDD_207,residual_variance,0.000037,0.000018,0.000048,10000,0,whole selected model,10,12
12,3MIDD_207,within_phase_total_variance,0.000044,0.000025,0.000064,10000,0,whole selected model,10,12
13,3MIDD_207,observed_within_to_between,0.211254,0.116571,1.811653,10000,0,whole selected model,10,12
14,4MIDD_085_170,icc_absolute,0.087136,0.022891,0.140219,10000,0,whole selected model,10,12
15,4MIDD_085_170,icc_consistency,0.143392,0.049842,0.211474,10000,0,whole selected model,10,12
16,4MIDD_085_170,model_variance,0.000008,0.000001,0.000015,10000,0,whole selected model,10,12
17,4MIDD_085_170,phase_variance,0.000037,0.000014,0.000086,10000,0,whole selected model,10,12
18,4MIDD_085_170,residual_variance,0.000049,0.000020,0.000072,10000,0,whole selected model,10,12
19,4MIDD_085_170,within_phase_total_variance,0.000086,0.000040,0.000142,10000,0,whole selected model,10,12

recomputed_phase_variance

    model_id          group     var_A     var_S
0          0      3MIDD_048  0.000020  0.000015
1          0      3MIDD_207  0.000006  0.000007
2          0  4MIDD_085_170  0.000009  0.000003
3          1      3MIDD_048  0.000003  0.000003
4          1      3MIDD_207  0.000002  0.000003
5          1  4MIDD_085_170  0.000009  0.000002
6          2      3MIDD_048  0.000032  0.000005
7          2      3MIDD_207  0.000035  0.000019
8          2  4MIDD_085_170  0.000027  0.000020
9          3      3MIDD_048  0.000049  0.000005
10         3      3MIDD_207  0.000039  0.000019
11         3  4MIDD_085_170  0.000187  0.000025
12         4      3MIDD_048  0.000113  0.000041
13         4      3MIDD_207  0.000035  0.000038
14         4  4MIDD_085_170  0.000063  0.000018
15         5      3MIDD_048  0.000121  0.000033
16         5      3MIDD_207  0.000088  0.000198
17         5  4MIDD_085_170  0.000243  0.000063
18         6      3MIDD_048  0.000043  0.000002
19         6      3MIDD_207  0.000060  0.000024

## 7. Statistics
Model/seed is the unit. Stored intervals retain the original inference choices. Fig3/S7 additionally replay the exact original bootstrap seed and RNG consumption order; cached null draws are not regenerated or tuned.

In [7]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

data/precomputed/fig02/matched_control_bootstrap_summary.csv

,group,metric,mean,ci_low,ci_high,n_models
0,3MIDD_048,D_canonical_vs_random,-0.003473,-0.009431,0.003662,10
1,3MIDD_048,D_reflection_matched,-0.003265,-0.009456,0.003833,10
2,3MIDD_048,D_normalized,-0.001336,-0.041024,0.048952,10
3,3MIDD_048,canonical_abs_A,0.008979,0.003860,0.015081,10
4,3MIDD_048,mean_random_reflection_abs_A,0.012452,0.010301,0.014496,10
5,3MIDD_207,D_canonical_vs_random,-0.001748,-0.008364,0.008143,10
6,3MIDD_207,D_reflection_matched,-0.001670,-0.008413,0.008699,10
7,3MIDD_207,D_normalized,-0.007924,-0.045112,0.046552,10
8,3MIDD_207,canonical_abs_A,0.010494,0.003534,0.020799,10
9,3MIDD_207,mean_random_reflection_abs_A,0.012243,0.010540,0.013734,10
10,4MIDD_085_170,D_canonical_vs_random,-0.007615,-0.010706,-0.004469,10
11,4MIDD_085_170,D_reflection_matched,-0.008295,-0.011227,-0.005347,10
12,4MIDD_085_170,D_normalized,-0.040011,-0.057464,-0.020275,10
13,4MIDD_085_170,canonical_abs_A,0.003702,0.001336,0.006678,10
14,4MIDD_085_170,mean_random_reflection_abs_A,0.011317,0.009055,0.013245,10

data/precomputed/fig04/phase_bootstrap.csv

,group,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,var_A,10,5.939411e-05,0.000043,0.000034,0.000087
1,3MIDD_048,var_S,10,1.397051e-05,0.000008,0.000007,0.000022
2,3MIDD_048,D,10,-4.542361e-05,-0.000037,-0.000071,-0.000024
3,3MIDD_048,ratio,10,3.548367e-01,0.263652,0.181106,0.559359
4,3MIDD_048,range_A_norm,10,1.443179e-01,0.150776,0.105462,0.185821
5,3MIDD_048,range_S_norm,10,6.826784e-02,0.060330,0.049608,0.091186
6,3MIDD_048,D_norm,10,-1.811257e-03,-0.001461,-0.002769,-0.000934
7,3MIDD_048,reversal_phase_fraction,10,5.833333e-01,0.625000,0.433333,0.725000
8,3MIDD_207,var_A,10,4.044602e-05,0.000037,0.000023,0.000059
9,3MIDD_207,var_S,10,3.955508e-05,0.000020,0.000016,0.000078
10,3MIDD_207,D,10,-8.909432e-07,-0.000008,-0.000020,0.000026
11,3MIDD_207,ratio,10,9.584036e-01,0.846509,0.655326,1.333661
12,3MIDD_207,range_A_norm,10,1.103596e-01,0.108108,0.078566,0.142078
13,3MIDD_207,range_S_norm,10,1.067394e-01,0.092386,0.074739,0.150716
14,3MIDD_207,D_norm,10,-4.139833e-06,-0.000175,-0.000683,0.000983
15,3MIDD_207,reversal_phase_fraction,10,5.500000e-01,0.500000,0.308333,0.791667
16,4MIDD_085_170,var_A,10,7.908426e-05,0.000048,0.000037,0.000130
17,4MIDD_085_170,var_S,10,1.906715e-05,0.000019,0.000009,0.000031
18,4MIDD_085_170,D,10,-6.001711e-05,-0.000031,-0.000101,-0.000025
19,4MIDD_085_170,ratio,10,3.238042e-01,0.267103,0.198287,0.469022
20,4MIDD_085_170,range_A_norm,10,1.522606e-01,0.135088,0.101978,0.211708
21,4MIDD_085_170,range_S_norm,10,8.465632e-02,0.064521,0.055774,0.117507
22,4MIDD_085_170,D_norm,10,-2.753473e-03,-0.000657,-0.005041,-0.000672
23,4MIDD_085_170,reversal_phase_fraction,10,3.833333e-01,0.416667,0.200000,0.566667

data/precomputed/fig04/geometry_bootstrap.csv

,group,transform,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,LR,delta_A,10,0.018279,0.015604,0.007655,0.030899
1,3MIDD_048,LR,delta_S,10,0.000326,0.000294,0.000006,0.000705
2,3MIDD_048,LR,normalized_error_A,10,0.004980,0.004213,0.002888,0.007156
3,3MIDD_048,LR,normalized_error_S,10,0.097151,0.111478,0.057734,0.137227
4,3MIDD_048,LR,D_robustness,10,0.092171,0.105838,0.052114,0.132773
...,...,...,...,...,...,...,...,...
115,4MIDD_085_170,y_plus3,delta_A,10,-0.005839,-0.004639,-0.008917,-0.003058
116,4MIDD_085_170,y_plus3,delta_S,10,0.000629,-0.000752,-0.003938,0.005904
117,4MIDD_085_170,y_plus3,normalized_error_A,10,0.038357,0.027443,0.019093,0.059968
118,4MIDD_085_170,y_plus3,normalized_error_S,10,0.025285,0.010704,0.009481,0.045516
119,4MIDD_085_170,y_plus3,D_robustness,10,-0.013073,-0.013583,-0.045576,0.021534

data/precomputed/fig02/official50_shuffle_summary.csv

,group,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,canonical_reflection_abs_A,50,0.010622,0.007087,0.007419,0.014431
1,3MIDD_048,shuffle_mean_abs_A,50,0.013307,0.012147,0.011744,0.015031
2,3MIDD_048,difference_mean,50,-0.002685,-0.003728,-0.005633,0.000589
3,3MIDD_048,difference_median,50,-0.001072,-0.003075,-0.004060,0.002438
4,3MIDD_048,canonical_percentile,50,0.390000,0.400000,0.312000,0.468000
5,3MIDD_207,canonical_reflection_abs_A,50,0.009395,0.006050,0.006979,0.012295
6,3MIDD_207,shuffle_mean_abs_A,50,0.012602,0.011247,0.010980,0.014304
7,3MIDD_207,difference_mean,50,-0.003206,-0.003694,-0.005870,-0.000308
8,3MIDD_207,difference_median,50,-0.001762,-0.001721,-0.004551,0.001175
9,3MIDD_207,canonical_percentile,50,0.414000,0.400000,0.334000,0.498000
10,4MIDD_085_170,canonical_reflection_abs_A,50,0.003400,0.002620,0.002584,0.004369
11,4MIDD_085_170,shuffle_mean_abs_A,50,0.011699,0.011433,0.010312,0.013183
12,4MIDD_085_170,difference_mean,50,-0.008299,-0.007550,-0.009766,-0.006922
13,4MIDD_085_170,difference_median,50,-0.007135,-0.006648,-0.008669,-0.005730
14,4MIDD_085_170,canonical_percentile,50,0.176000,0.100000,0.130000,0.228000

data/precomputed/fig04/official50_phase_reliability.csv

,n_models,n_phases,icc_absolute,icc_consistency,SS_model,SS_phase,SS_residual,SS_total,SS_model_fraction,SS_phase_fraction,...,observed_within_to_between,ci_low,ci_high,phase0_mean_A,phase_average_mean_A,phase0_mean_sign_agreement,phase0_mean_spearman,sign_changing_models,mean_phasewise_reversal_fraction,reversal_of_phase_averaged_pair
0,50,12,0.764701,0.81718,0.096557,0.007843,0.019439,0.123838,0.779698,0.06333,...,0.302069,0.59631,0.867805,-0.009346,-0.003777,0.78,0.760384,34,0.435,23

data/precomputed/fig05/official50_performance_primary_relations.csv

,metric,n_models,spearman,p,ci_low,ci_high,holm_primary_three
0,A,50,0.283842,0.045761,-0.002557,0.533809,0.091522
1,abs_A,50,-0.214790,0.134153,-0.502454,0.096362,0.134153
2,normalized_SD,50,-0.326194,0.020787,-0.585733,-0.023088,0.062360

data/precomputed/fig04/phase_reliability_icc_bootstrap.csv

,group,metric,estimate,ci_low,ci_high,valid_draws,undefined_draws,bootstrap_unit,n_models,n_fixed_phases
0,3MIDD_048,icc_absolute,0.612969,0.323132,0.703770,10000,0,whole selected model,10,12
1,3MIDD_048,icc_consistency,0.740937,0.510491,0.889521,10000,0,whole selected model,10,12
2,3MIDD_048,model_variance,0.000103,0.000034,0.000144,10000,0,whole selected model,10,12
3,3MIDD_048,phase_variance,0.000029,0.000005,0.000068,10000,0,whole selected model,10,12
4,3MIDD_048,residual_variance,0.000036,0.000015,0.000055,10000,0,whole selected model,10,12
5,3MIDD_048,within_phase_total_variance,0.000065,0.000037,0.000095,10000,0,whole selected model,10,12
6,3MIDD_048,observed_within_to_between,0.613527,0.414160,1.959227,10000,0,whole selected model,10,12
7,3MIDD_207,icc_absolute,0.823459,0.331908,0.894904,10000,0,whole selected model,10,12
8,3MIDD_207,icc_consistency,0.848845,0.415716,0.921848,10000,0,whole selected model,10,12
9,3MIDD_207,model_variance,0.000206,0.000016,0.000452,10000,0,whole selected model,10,12
10,3MIDD_207,phase_variance,0.000007,0.000002,0.000025,10000,0,whole selected model,10,12
11,3MIDD_207,residual_variance,0.000037,0.000018,0.000048,10000,0,whole selected model,10,12
12,3MIDD_207,within_phase_total_variance,0.000044,0.000025,0.000064,10000,0,whole selected model,10,12
13,3MIDD_207,observed_within_to_between,0.211254,0.116571,1.811653,10000,0,whole selected model,10,12
14,4MIDD_085_170,icc_absolute,0.087136,0.022891,0.140219,10000,0,whole selected model,10,12
15,4MIDD_085_170,icc_consistency,0.143392,0.049842,0.211474,10000,0,whole selected model,10,12
16,4MIDD_085_170,model_variance,0.000008,0.000001,0.000015,10000,0,whole selected model,10,12
17,4MIDD_085_170,phase_variance,0.000037,0.000014,0.000086,10000,0,whole selected model,10,12
18,4MIDD_085_170,residual_variance,0.000049,0.000020,0.000072,10000,0,whole selected model,10,12
19,4MIDD_085_170,within_phase_total_variance,0.000086,0.000040,0.000142,10000,0,whole selected model,10,12
20,4MIDD_085_170,observed_within_to_between,6.994394,4.535923,18.503661,10000,0,whole selected model,10,12

## 8. Figure generation
The shared plotting source preserves the adopted layout and labels; no manual PDF editing.

In [8]:
fig = render(FIGURE)
display(fig)

Saved S5 inputs 7 checks 1

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [9]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: S5 primary tables: 2 adopted tables: 23

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [10]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/supplementary/fig_S5.ipynb
Model inference: False