# Figure S8

Four common checkpoints in all fourteen seeds compare MIDD, one fixed shuffle, balanced negative and uniform controls. Checkpoints are repeated within seed.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [name for name in ("numpy", "pandas", "matplotlib")
               if importlib.util.find_spec(name) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = 'S8'

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/fig05/...,f3a6192ebb4c655d116515494ece65b5ade368015a1957...,3194
1,data/precomputed/fig05/...,dc778a2d7e432abc8ae4cc17e9f77b033c372a087da187...,2042049
2,data/precomputed/fig05/...,0d7810935770d873effd598c55f12cb74e48c89b59806b...,11091
3,data/precomputed/fig05/...,1ed4db3e4fe8080f3bc6b1835c496208d97742c30ca260...,49950
4,data/precomputed/fig05/...,53e2b210b0a7fa7186992150962d5207100d8fc1498662...,88333
5,data/precomputed/fig05/...,7c8a18621723942b97f1a0a4ae5e3747819a0762cdd5d8...,1822
6,data/precomputed/fig02/learning_f...,8a5b6af858656d8a2e1dc307b68ace340470128b3fd202...,23852
7,data/precomputed/fig04/phase_reliability_checkpoint_s...,09410cc5cbfd076673550baa532639ae713a32bd57b31f...,1113

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 8

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

Empty DataFrame
Columns: [check, passed]
Index: []

## 5. Primary analysis
For Fig3/S7, affine fits and both held-out splits are recomputed from saved A3/A4. Native and multi-field definitions remain separate.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

common_support_trajectories

,seed,optimizer_step,group,mean_signed_tangent_mirror,mean_signed_tangent_negative,mean_signed_tangent_original,mean_flow_magnitude_mirror,mean_flow_magnitude_negative,mean_flow_magnitude_original,A,S,M,G,zero_denominator,A_norm,abs_A_norm
0,0,0,3MIDD_048,-0.000025,-0.000025,-0.000025,0.101485,0.101485,0.101486,5.937108e-10,-0.000025,-0.000025,0.101485,False,5.850212e-09,5.850212e-09
1,0,0,3MIDD_207,-0.000025,-0.000025,-0.000025,0.101449,0.101449,0.101449,2.437839e-09,-0.000025,-0.000025,0.101449,False,2.403017e-08,2.403017e-08
2,0,0,4MIDD_085_170,-0.000025,-0.000025,-0.000025,0.101467,0.101468,0.101467,1.080582e-09,-0.000025,-0.000025,0.101467,False,1.064954e-08,1.064954e-08
3,0,1000,3MIDD_048,0.000491,0.000481,0.000493,0.133835,0.133849,0.133847,9.459996e-07,0.000492,-0.000491,0.133841,False,7.068093e-06,7.068093e-06
4,0,1000,3MIDD_207,0.000436,0.000426,0.000438,0.133296,0.133309,0.133308,8.464744e-07,0.000437,-0.000436,0.133302,False,6.350039e-06,6.350039e-06
5,0,1000,4MIDD_085_170,0.000464,0.000464,0.000465,0.133580,0.133589,0.133582,1.449340e-07,0.000465,-0.000464,0.133581,False,1.084988e-06,1.084988e-06
6,0,2000,3MIDD_048,-0.009409,-0.009340,-0.009396,0.192226,0.192257,0.191843,6.542919e-06,-0.009403,-0.009396,0.192034,False,3.407159e-05,3.407159e-05
7,0,2000,3MIDD_207,-0.009439,-0.009375,-0.009426,0.206964,0.206927,0.206621,6.659138e-06,-0.009432,-0.009426,0.206793,False,3.220199e-05,3.220199e-05
8,0,2000,4MIDD_085_170,-0.009404,-0.009392,-0.009398,0.199506,0.199419,0.199418,2.729487e-06,-0.009401,-0.009398,0.199462,False,1.368424e-05,1.368424e-05
9,0,3000,3MIDD_048,0.014081,0.014215,0.014003,0.215174,0.215161,0.214516,-3.903654e-05,0.014042,-0.014003,0.214845,False,-1.816963e-04,1.816963e-04
10,0,3000,3MIDD_207,0.016194,0.016325,0.016105,0.240143,0.240236,0.239503,-4.439831e-05,0.016149,-0.016105,0.239823,False,-1.851296e-04,1.851296e-04
11,0,3000,4MIDD_085_170,0.015000,0.015006,0.014983,0.227055,0.226876,0.226986,-8.532080e-06,0.014992,-0.014983,0.227021,False,-3.758285e-05,3.758285e-05
12,0,4000,3MIDD_048,-0.012155,-0.011910,-0.012055,0.221468,0.221449,0.220928,5.001823e-05,-0.012105,-0.012055,0.221198,False,2.261247e-04,2.261247e-04
13,0,4000,3MIDD_207,-0.012826,-0.012639,-0.012763,0.235488,0.235390,0.235029,3.148279e-05,-0.012795,-0.012763,0.235258,False,1.338221e-04,1.338221e-04
14,0,4000,4MIDD_085_170,-0.012487,-0.012438,-0.012421,0.227771,0.227728,0.227670,3.275660e-05,-0.012454,-0.012421,0.227720,False,1.438457e-04,1.438457e-04
15,0,5000,3MIDD_048,0.012870,0.013081,0.012875,0.249050,0.248746,0.248491,2.628813e-06,0.012873,-0.012870,0.248770,False,1.056723e-05,1.056723e-05
16,0,5000,3MIDD_207,0.014304,0.014478,0.014372,0.253897,0.253472,0.253473,3.432196e-05,0.014338,-0.014304,0.253685,False,1.352937e-04,1.352937e-04
17,0,5000,4MIDD_085_170,0.013767,0.013801,0.013749,0.250836,0.250744,0.250792,-8.806735e-06,0.013758,-0.013749,0.250814,False,-3.511259e-05,3.511259e-05
18,0,6000,3MIDD_048,0.002632,0.002995,0.002749,0.225684,0.225695,0.224710,5.839045e-05,0.002691,-0.002632,0.225197,False,2.592864e-04,2.592864e-04
19,0,6000,3MIDD_207,0.004247,0.004359,0.004268,0.249548,0.248521,0.248728,1.056218e-05,0.004258,-0.004247,0.249138,False,4.239487e-05,4.239487e-05

common_100k_endpoints

,seed,optimizer_step,group,mean_signed_tangent_mirror,mean_signed_tangent_negative,mean_signed_tangent_original,mean_flow_magnitude_mirror,mean_flow_magnitude_negative,mean_flow_magnitude_original,A,S,M,G,zero_denominator,A_norm,abs_A_norm
300,0,100000,3MIDD_048,0.057805,0.013554,0.029605,0.330112,0.215458,0.315342,-0.014100,0.043705,-0.029605,0.322727,False,-0.043690,0.043690
301,0,100000,3MIDD_207,0.064602,0.048176,0.068213,0.347235,0.245031,0.332441,0.001806,0.066407,-0.064602,0.339838,False,0.005313,0.005313
302,0,100000,4MIDD_085_170,0.042269,0.043815,0.060643,0.333941,0.319175,0.338325,0.009187,0.051456,-0.042269,0.336133,False,0.027331,0.027331
1053,1,100000,3MIDD_048,0.018359,-0.030660,-0.020989,0.254597,0.221515,0.260672,-0.019674,-0.001315,0.018359,0.257635,False,-0.076364,0.076364
1054,1,100000,3MIDD_207,-0.001410,0.028625,0.071321,0.432143,0.316924,0.396490,0.036365,0.034955,0.001410,0.414316,False,0.087772,0.087772
1055,1,100000,4MIDD_085_170,-0.006511,0.004453,0.017737,0.312255,0.293566,0.291143,0.012124,0.005613,0.006511,0.301699,False,0.040186,0.040186
1806,2,100000,3MIDD_048,0.022214,-0.026089,0.016064,0.248118,0.235712,0.251186,-0.003075,0.019139,-0.016064,0.249652,False,-0.012317,0.012317
1807,2,100000,3MIDD_207,-0.008229,0.013597,0.078070,0.288012,0.251983,0.296040,0.043149,0.034921,0.008229,0.292026,False,0.147758,0.147758
1808,2,100000,4MIDD_085_170,0.008344,0.004479,0.025983,0.266461,0.254530,0.272197,0.008820,0.017164,-0.008344,0.269329,False,0.032747,0.032747
2559,3,100000,3MIDD_048,0.001478,0.001973,0.000391,0.113082,0.083623,0.112177,-0.000543,0.000935,-0.000391,0.112630,False,-0.004824,0.004824
2560,3,100000,3MIDD_207,-0.020996,0.008625,-0.017260,0.151150,0.142385,0.149930,0.001868,-0.019128,-0.017260,0.150540,False,0.012410,0.012410
2561,3,100000,4MIDD_085_170,-0.015576,-0.013399,-0.009761,0.119225,0.111762,0.115747,0.002908,-0.012668,-0.009761,0.117486,False,0.024748,0.024748
3312,4,100000,3MIDD_048,0.015494,0.009055,0.011818,0.250450,0.257932,0.251480,-0.001838,0.013656,-0.011818,0.250965,False,-0.007324,0.007324
3313,4,100000,3MIDD_207,0.012775,0.002795,0.009012,0.249280,0.236077,0.250985,-0.001881,0.010894,-0.009012,0.250133,False,-0.007521,0.007521
3314,4,100000,4MIDD_085_170,0.010209,0.009168,0.023645,0.272251,0.278933,0.282284,0.006718,0.016927,-0.010209,0.277268,False,0.024229,0.024229
3615,5,100000,3MIDD_048,0.003055,0.016908,-0.016126,0.224156,0.207154,0.233393,-0.009591,-0.006536,0.003055,0.228774,False,-0.041921,0.041921
3616,5,100000,3MIDD_207,-0.004499,0.011727,0.011775,0.242044,0.208179,0.244426,0.008137,0.003638,0.004499,0.243235,False,0.033453,0.033453
3617,5,100000,4MIDD_085_170,-0.014828,0.006399,0.020371,0.199559,0.198733,0.216839,0.017600,0.002772,0.014828,0.208199,False,0.084533,0.084533
3918,6,100000,3MIDD_048,0.078515,0.041426,0.035173,0.401955,0.353871,0.420206,-0.021671,0.056844,-0.035173,0.411081,False,-0.052717,0.052717
3919,6,100000,3MIDD_207,-0.044024,0.012362,0.066025,0.560974,0.387064,0.508429,0.055024,0.011001,0.044024,0.534701,False,0.102907,0.102907

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig05/learning_threshold_summary.csv

,group,support,threshold,definition,n_seeds,n_crossed,median_crossing_among_crossers,n_censored,n_endpoint_unevaluable
0,3MIDD_048,common_100k,0.0005,first,14,14,26500.0,0,0
1,3MIDD_048,common_100k,0.0005,persistent_three_regular,14,14,29000.0,0,0
2,3MIDD_048,common_100k,0.0010,first,14,14,31500.0,0,0
3,3MIDD_048,common_100k,0.0010,persistent_three_regular,14,14,32500.0,0,0
4,3MIDD_048,common_100k,0.0020,first,14,14,33500.0,0,0
5,3MIDD_048,common_100k,0.0020,persistent_three_regular,14,14,34500.0,0,0
6,3MIDD_048,common_100k,0.0050,first,14,12,35000.0,2,0
7,3MIDD_048,common_100k,0.0050,persistent_three_regular,14,12,35000.0,2,0
8,3MIDD_048,full_followup,0.0005,first,14,14,26500.0,0,0
9,3MIDD_048,full_followup,0.0005,persistent_three_regular,14,14,29000.0,0,0
10,3MIDD_048,full_followup,0.0010,first,14,14,31500.0,0,0
11,3MIDD_048,full_followup,0.0010,persistent_three_regular,14,14,32500.0,0,0
12,3MIDD_048,full_followup,0.0020,first,14,14,33500.0,0,0
13,3MIDD_048,full_followup,0.0020,persistent_three_regular,14,14,34500.0,0,0
14,3MIDD_048,full_followup,0.0050,first,14,13,36000.0,1,0
15,3MIDD_048,full_followup,0.0050,persistent_three_regular,14,12,35000.0,2,0
16,3MIDD_207,common_100k,0.0005,first,14,14,25000.0,0,0
17,3MIDD_207,common_100k,0.0005,persistent_three_regular,14,14,28000.0,0,0
18,3MIDD_207,common_100k,0.0010,first,14,14,31500.0,0,0
19,3MIDD_207,common_100k,0.0010,persistent_three_regular,14,14,32500.0,0,0

data/precomputed/fig05/physical_motion_trajectory.csv

,seed,optimizer_step,A,abs_A,abs_A_norm,S,M,propeller_contrast,propeller_CW_ratio,propeller_CCW_ratio,propeller_CW_magnitude,propeller_CCW_magnitude,CW_moving_static,CCW_moving_static,edge_contrast,edge_right_ratio,edge_left_ratio,physical_pass,edge_pass,fixed_eval_epe
0,0,0,5.937108e-10,5.937108e-10,5.850212e-09,-0.000025,-0.000025,-7.291280e-09,-0.000244,-0.000243,0.101530,0.101530,0.999992,0.999992,9.760261e-07,0.707107,0.707107,False,False,5.425017
1,0,10000,1.896754e-05,1.896754e-05,9.804816e-05,-0.000973,-0.000954,7.144911e-05,-0.002055,-0.002865,0.177629,0.177277,0.945173,0.943300,-4.142821e-04,-0.236335,-0.305216,False,False,5.402174
2,0,20000,9.551594e-05,9.551594e-05,4.532788e-04,-0.003136,-0.003040,4.164538e-03,0.006045,-0.034922,0.202370,0.203479,0.883558,0.888403,1.398483e-02,-0.290930,-0.395291,False,False,5.387235
3,0,30000,-7.055089e-03,7.055089e-03,1.265049e-02,0.031852,-0.024797,2.120940e+00,0.818353,-0.827316,2.580359,2.574875,4.654435,4.644544,4.758168e-01,0.823684,-0.456804,True,True,5.211999
4,0,40000,-1.602633e-02,1.602633e-02,3.220671e-02,0.058168,-0.042142,4.588724e+00,0.857905,-0.873404,5.305259,5.296561,10.477657,10.460480,7.856001e-01,0.821838,-0.375108,True,True,4.991945
5,0,50000,-2.590978e-02,2.590978e-02,5.720569e-02,0.066552,-0.040642,5.817437e+00,0.886185,-0.904229,6.516383,6.480830,15.287371,15.203964,8.175794e-01,0.815167,-0.616368,True,True,4.968801
6,0,60000,-2.440318e-02,2.440318e-02,4.697779e-02,0.092038,-0.067635,7.879777e+00,0.907647,-0.925032,8.640963,8.558205,25.437506,25.193880,1.106099e+00,0.890754,-0.638296,True,True,4.895457
7,0,70000,-2.374023e-02,2.374023e-02,4.010056e-02,0.088377,-0.064637,8.825028e+00,0.923827,-0.938379,9.507817,9.448719,31.643073,31.446388,1.214261e+00,0.838428,-0.830234,True,True,4.919116
8,0,80000,-1.945152e-02,1.945152e-02,4.971111e-02,0.072103,-0.052652,9.598188e+00,0.935238,-0.944268,10.260401,10.167086,46.431113,46.008837,1.010525e+00,0.806643,-0.839545,True,True,4.887022
9,0,90000,-2.289125e-02,2.289125e-02,5.198646e-02,0.063255,-0.040364,9.479353e+00,0.928048,-0.942158,10.105212,10.168765,30.116850,30.306258,9.684215e-01,0.920905,-0.532432,True,True,4.844060
10,0,100000,-1.409995e-02,1.409995e-02,4.369004e-02,0.043705,-0.029605,8.169994e+00,0.930498,-0.935337,8.766743,8.748233,24.613346,24.561377,8.890093e-01,0.944477,-0.586121,True,True,4.986991
11,4,0,-1.063071e-10,1.063071e-10,1.053003e-09,-0.000028,-0.000028,-7.420910e-09,-0.000277,-0.000276,0.101000,0.101000,0.999992,0.999992,9.723008e-07,0.707107,0.707107,False,False,5.424898
12,4,10000,4.407798e-05,4.407798e-05,1.922529e-04,-0.026999,-0.026955,3.003414e-04,-0.105606,-0.107527,0.258328,0.259299,0.970344,0.973992,1.641672e-02,-0.150731,-0.327469,False,False,5.405832
13,4,20000,3.607232e-04,3.607232e-04,1.801947e-03,0.003256,-0.002895,4.356651e-01,0.618945,-0.615224,0.709090,0.702902,2.980822,2.954809,1.334321e-01,0.111045,-0.525329,False,True,5.356548
14,4,30000,3.104844e-03,3.104844e-03,6.979466e-03,0.005263,-0.002158,3.509034e+00,0.860150,-0.841099,4.163997,4.085615,9.253121,9.078942,1.094535e+00,0.505918,-0.884789,True,True,5.212973
15,4,40000,-1.376594e-02,1.376594e-02,3.378631e-02,-0.010606,0.003160,5.141372e+00,0.899647,-0.872007,5.782586,5.826164,11.784584,11.873393,1.254821e+00,0.794060,-0.839775,True,True,5.093257
16,4,50000,-4.394694e-03,4.394694e-03,1.805070e-02,0.004196,0.000199,6.347896e+00,0.934086,-0.907716,6.825582,6.962651,23.985619,24.467290,1.207282e+00,0.789286,-0.882357,True,True,5.046100
17,4,60000,-3.205731e-03,3.205731e-03,9.725140e-03,-0.013001,-0.009795,6.963203e+00,0.928493,-0.908883,7.490342,7.670598,14.044108,14.382082,1.081779e+00,0.793137,-0.677982,True,True,4.978983
18,4,70000,-5.533596e-03,5.533596e-03,1.903639e-02,-0.003784,0.001750,6.575047e+00,0.923632,-0.907659,7.057780,7.305946,20.134189,20.842147,1.120407e+00,0.684680,-0.935685,True,True,5.038331
19,4,80000,-9.787467e-03,9.787467e-03,3.631335e-02,-0.008519,0.001269,7.250981e+00,0.920193,-0.901025,7.844617,8.083464,14.473801,14.914488,1.172481e+00,0.839647,-0.699277,True,True,5.014834

data/precomputed/fig05/learning_sign_consistency.csv

,optimizer_step,group,n_seeds,positive_exact_fraction,negative_exact_fraction,zero_exact_fraction,positive_fraction,negative_fraction,near_zero_fraction,median_A,median_sign,sign_entropy_bits
0,0,3MIDD_048,14,0.928571,0.071429,0.0,0.0,0.0,1.0,9.299022e-10,1.0,-0.0
1,0,3MIDD_207,14,0.785714,0.214286,0.0,0.0,0.0,1.0,1.845110e-09,1.0,-0.0
2,0,4MIDD_085_170,14,0.642857,0.357143,0.0,0.0,0.0,1.0,4.331291e-10,1.0,-0.0
3,1000,3MIDD_048,14,0.714286,0.285714,0.0,0.0,0.0,1.0,5.977640e-07,1.0,-0.0
4,1000,3MIDD_207,14,0.857143,0.142857,0.0,0.0,0.0,1.0,4.976011e-07,1.0,-0.0
5,1000,4MIDD_085_170,14,0.714286,0.285714,0.0,0.0,0.0,1.0,9.345039e-08,1.0,-0.0
6,2000,3MIDD_048,14,0.500000,0.500000,0.0,0.0,0.0,1.0,6.076168e-07,1.0,-0.0
7,2000,3MIDD_207,14,0.500000,0.500000,0.0,0.0,0.0,1.0,2.936142e-07,1.0,-0.0
8,2000,4MIDD_085_170,14,0.357143,0.642857,0.0,0.0,0.0,1.0,-7.913602e-07,-1.0,-0.0
9,3000,3MIDD_048,14,0.357143,0.642857,0.0,0.0,0.0,1.0,-1.414679e-05,-1.0,-0.0
10,3000,3MIDD_207,14,0.357143,0.642857,0.0,0.0,0.0,1.0,-7.982192e-06,-1.0,-0.0
11,3000,4MIDD_085_170,14,0.500000,0.500000,0.0,0.0,0.0,1.0,3.976719e-07,1.0,-0.0
12,4000,3MIDD_048,14,0.785714,0.214286,0.0,0.0,0.0,1.0,1.031254e-05,1.0,-0.0
13,4000,3MIDD_207,14,0.714286,0.285714,0.0,0.0,0.0,1.0,9.280699e-06,1.0,-0.0
14,4000,4MIDD_085_170,14,0.714286,0.285714,0.0,0.0,0.0,1.0,1.240640e-05,1.0,-0.0
15,5000,3MIDD_048,14,0.785714,0.214286,0.0,0.0,0.0,1.0,2.205096e-05,1.0,-0.0
16,5000,3MIDD_207,14,0.714286,0.285714,0.0,0.0,0.0,1.0,2.032809e-05,1.0,-0.0
17,5000,4MIDD_085_170,14,0.642857,0.357143,0.0,0.0,0.0,1.0,1.000376e-05,1.0,-0.0
18,6000,3MIDD_048,14,0.571429,0.428571,0.0,0.0,0.0,1.0,1.630721e-05,1.0,-0.0
19,6000,3MIDD_207,14,0.571429,0.428571,0.0,0.0,0.0,1.0,5.900336e-06,1.0,-0.0

data/precomputed/fig05/physical_motion_onsets.csv

,seed,endpoint,definition,onset_step,lower_bracket,upper_bracket,censored,end_persistence_unevaluable,MIDD_dense_onset,physical_minus_MIDD,MIDD_dense_lower,lag_lower_bracket,lag_upper_bracket
0,0,propeller,first,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
1,0,propeller,persistent_three,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
2,0,moving_edge,first,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
3,0,moving_edge,persistent_three,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
4,0,MIDD_coarse,first,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
5,0,MIDD_coarse,persistent_three,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
6,4,propeller,first,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
7,4,propeller,persistent_three,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
8,4,moving_edge,first,20000.0,10000,20000.0,False,False,25000.0,-5000.0,24000.0,-15000.0,-4000.0
9,4,moving_edge,persistent_three,20000.0,10000,20000.0,False,False,25000.0,-5000.0,24000.0,-15000.0,-4000.0
10,4,MIDD_coarse,first,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
11,4,MIDD_coarse,persistent_three,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
12,7,propeller,first,40000.0,30000,40000.0,False,False,49000.0,-9000.0,48000.0,-19000.0,-8000.0
13,7,propeller,persistent_three,40000.0,30000,40000.0,False,False,52000.0,-12000.0,51000.0,-22000.0,-11000.0
14,7,moving_edge,first,50000.0,40000,50000.0,False,False,49000.0,1000.0,48000.0,-9000.0,2000.0
15,7,moving_edge,persistent_three,50000.0,40000,50000.0,False,False,52000.0,-2000.0,51000.0,-12000.0,-1000.0
16,7,MIDD_coarse,first,50000.0,40000,50000.0,False,False,49000.0,NaN,48000.0,NaN,NaN
17,7,MIDD_coarse,persistent_three,NaN,100000,NaN,True,True,52000.0,NaN,51000.0,NaN,NaN

data/precomputed/fig05/learning_fixed_control_pairs.csv

,seed,optimizer_step,condition,A,S,G,abs_A_norm,T
0,0,0,MIDD,1.122748e-09,-0.000025,0.101485,1.106315e-08,-0.000025
1,0,0,shuffle,-1.069079e-06,-0.000032,0.101485,1.053432e-05,-0.000033
2,0,0,negative,-6.624931e-11,-0.000025,0.101485,6.527991e-10,-0.000025
3,0,0,uniform singleton,NaN,NaN,0.101470,NaN,-0.000025
4,0,10000,MIDD,1.897190e-05,-0.000973,0.193451,9.807071e-05,-0.000954
5,0,10000,shuffle,-2.535998e-03,0.001107,0.199064,1.273962e-02,-0.001429
6,0,10000,negative,2.597579e-04,-0.000982,0.193791,1.340399e-03,-0.000722
7,0,10000,uniform singleton,NaN,NaN,0.194988,NaN,-0.000949
8,0,50000,MIDD,-2.590976e-02,0.066552,0.452923,5.720566e-02,0.040642
9,0,50000,shuffle,-1.553783e-02,0.039699,0.380535,4.083150e-02,0.024161
10,0,50000,negative,-2.639997e-03,0.029939,0.293939,8.981458e-03,0.027299
11,0,50000,uniform singleton,NaN,NaN,0.228568,NaN,0.039367
12,0,100000,MIDD,-1.409993e-02,0.043705,0.322727,4.368997e-02,0.029605
13,0,100000,shuffle,-3.293844e-03,0.018016,0.244548,1.346911e-02,0.014722
14,0,100000,negative,-9.292029e-03,0.022847,0.218655,4.249634e-02,0.013555
15,0,100000,uniform singleton,NaN,NaN,0.320115,NaN,0.004914
16,1,0,MIDD,8.130957e-10,-0.000025,0.101408,8.018034e-09,-0.000025
17,1,0,shuffle,-1.067745e-06,-0.000032,0.101408,1.052917e-05,-0.000033
18,1,0,negative,-3.853138e-10,-0.000025,0.101408,3.799639e-09,-0.000025
19,1,0,uniform singleton,NaN,NaN,0.101393,NaN,-0.000025

data/precomputed/fig05/learning_stability_checkpoint_summary.csv

,group,window,n_adjacent_comparisons,median_adjacent_pearson,median_adjacent_spearman,mean_adjacent_sign_agreement,median_relative_RMS_change,n_seeds,replication_unit
0,3MIDD_048,common0_100k,100,0.937165,0.887912,0.882143,0.319792,14,seed; comparisons are ordered and dependent
1,3MIDD_048,late_common80_100k,20,0.960266,0.958242,0.942857,0.231761,14,seed; comparisons are ordered and dependent
2,3MIDD_207,common0_100k,100,0.931616,0.925275,0.881429,0.324380,14,seed; comparisons are ordered and dependent
3,3MIDD_207,late_common80_100k,20,0.921104,0.940659,0.989286,0.395772,14,seed; comparisons are ordered and dependent
4,4MIDD_085_170,common0_100k,100,0.922781,0.887912,0.827143,0.378949,14,seed; comparisons are ordered and dependent
5,4MIDD_085_170,late_common80_100k,20,0.943305,0.938462,0.950000,0.287694,14,seed; comparisons are ordered and dependent

## 7. Statistics
Model/seed is the unit. Stored intervals retain the original inference choices. Fig3/S7 additionally replay the exact original bootstrap seed and RNG consumption order; cached null draws are not regenerated or tuned.

In [7]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

data/precomputed/fig05/learning_threshold_summary.csv

,group,support,threshold,definition,n_seeds,n_crossed,median_crossing_among_crossers,n_censored,n_endpoint_unevaluable
0,3MIDD_048,common_100k,0.0005,first,14,14,26500.0,0,0
1,3MIDD_048,common_100k,0.0005,persistent_three_regular,14,14,29000.0,0,0
2,3MIDD_048,common_100k,0.0010,first,14,14,31500.0,0,0
3,3MIDD_048,common_100k,0.0010,persistent_three_regular,14,14,32500.0,0,0
4,3MIDD_048,common_100k,0.0020,first,14,14,33500.0,0,0
5,3MIDD_048,common_100k,0.0020,persistent_three_regular,14,14,34500.0,0,0
6,3MIDD_048,common_100k,0.0050,first,14,12,35000.0,2,0
7,3MIDD_048,common_100k,0.0050,persistent_three_regular,14,12,35000.0,2,0
8,3MIDD_048,full_followup,0.0005,first,14,14,26500.0,0,0
9,3MIDD_048,full_followup,0.0005,persistent_three_regular,14,14,29000.0,0,0
10,3MIDD_048,full_followup,0.0010,first,14,14,31500.0,0,0
11,3MIDD_048,full_followup,0.0010,persistent_three_regular,14,14,32500.0,0,0
12,3MIDD_048,full_followup,0.0020,first,14,14,33500.0,0,0
13,3MIDD_048,full_followup,0.0020,persistent_three_regular,14,14,34500.0,0,0
14,3MIDD_048,full_followup,0.0050,first,14,13,36000.0,1,0
15,3MIDD_048,full_followup,0.0050,persistent_three_regular,14,12,35000.0,2,0
16,3MIDD_207,common_100k,0.0005,first,14,14,25000.0,0,0
17,3MIDD_207,common_100k,0.0005,persistent_three_regular,14,14,28000.0,0,0
18,3MIDD_207,common_100k,0.0010,first,14,14,31500.0,0,0
19,3MIDD_207,common_100k,0.0010,persistent_three_regular,14,14,32500.0,0,0
20,3MIDD_207,common_100k,0.0020,first,14,14,33000.0,0,0
21,3MIDD_207,common_100k,0.0020,persistent_three_regular,14,14,35500.0,0,0
22,3MIDD_207,common_100k,0.0050,first,14,13,35000.0,1,0
23,3MIDD_207,common_100k,0.0050,persistent_three_regular,14,13,36000.0,1,0
24,3MIDD_207,full_followup,0.0005,first,14,14,25000.0,0,0
25,3MIDD_207,full_followup,0.0005,persistent_three_regular,14,14,28000.0,0,0
26,3MIDD_207,full_followup,0.0010,first,14,14,31500.0,0,0
27,3MIDD_207,full_followup,0.0010,persistent_three_regular,14,14,32500.0,0,0
28,3MIDD_207,full_followup,0.0020,first,14,14,33000.0,0,0
29,3MIDD_207,full_followup,0.0020,persistent_three_regular,14,14,35500.0,0,0
30,3MIDD_207,full_followup,0.0050,first,14,14,35500.0,0,0
31,3MIDD_207,full_followup,0.0050,persistent_three_regular,14,14,37000.0,0,0
32,4MIDD_085_170,common_100k,0.0005,first,14,14,26000.0,0,0
33,4MIDD_085_170,common_100k,0.0005,persistent_three_regular,14,14,30500.0,0,0
34,4MIDD_085_170,common_100k,0.0010,first,14,14,28500.0,0,0
35,4MIDD_085_170,common_100k,0.0010,persistent_three_regular,14,14,31000.0,0,0
36,4MIDD_085_170,common_100k,0.0020,first,14,14,32000.0,0,0
37,4MIDD_085_170,common_100k,0.0020,persistent_three_regular,14,13,32000.0,1,0
38,4MIDD_085_170,common_100k,0.0050,first,14,11,35000.0,3,0
39,4MIDD_085_170,common_100k,0.0050,persistent_three_regular,14,11,40000.0,3,0
40,4MIDD_085_170,full_followup,0.0005,first,14,14,26000.0,0,0
41,4MIDD_085_170,full_followup,0.0005,persistent_three_regular,14,14,30500.0,0,0
42,4MIDD_085_170,full_followup,0.0010,first,14,14,28500.0,0,0
43,4MIDD_085_170,full_followup,0.0010,persistent_three_regular,14,14,31000.0,0,0
44,4MIDD_085_170,full_followup,0.0020,first,14,14,32000.0,0,0
45,4MIDD_085_170,full_followup,0.0020,persistent_three_regular,14,13,32000.0,1,0
46,4MIDD_085_170,full_followup,0.0050,first,14,11,35000.0,3,0
47,4MIDD_085_170,full_followup,0.0050,persistent_three_regular,14,11,40000.0,3,0

data/precomputed/fig05/physical_motion_onsets.csv

,seed,endpoint,definition,onset_step,lower_bracket,upper_bracket,censored,end_persistence_unevaluable,MIDD_dense_onset,physical_minus_MIDD,MIDD_dense_lower,lag_lower_bracket,lag_upper_bracket
0,0,propeller,first,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
1,0,propeller,persistent_three,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
2,0,moving_edge,first,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
3,0,moving_edge,persistent_three,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
4,0,MIDD_coarse,first,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
5,0,MIDD_coarse,persistent_three,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
6,4,propeller,first,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
7,4,propeller,persistent_three,30000.0,20000,30000.0,False,False,25000.0,5000.0,24000.0,-5000.0,6000.0
8,4,moving_edge,first,20000.0,10000,20000.0,False,False,25000.0,-5000.0,24000.0,-15000.0,-4000.0
9,4,moving_edge,persistent_three,20000.0,10000,20000.0,False,False,25000.0,-5000.0,24000.0,-15000.0,-4000.0
10,4,MIDD_coarse,first,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
11,4,MIDD_coarse,persistent_three,30000.0,20000,30000.0,False,False,25000.0,NaN,24000.0,NaN,NaN
12,7,propeller,first,40000.0,30000,40000.0,False,False,49000.0,-9000.0,48000.0,-19000.0,-8000.0
13,7,propeller,persistent_three,40000.0,30000,40000.0,False,False,52000.0,-12000.0,51000.0,-22000.0,-11000.0
14,7,moving_edge,first,50000.0,40000,50000.0,False,False,49000.0,1000.0,48000.0,-9000.0,2000.0
15,7,moving_edge,persistent_three,50000.0,40000,50000.0,False,False,52000.0,-2000.0,51000.0,-12000.0,-1000.0
16,7,MIDD_coarse,first,50000.0,40000,50000.0,False,False,49000.0,NaN,48000.0,NaN,NaN
17,7,MIDD_coarse,persistent_three,NaN,100000,NaN,True,True,52000.0,NaN,51000.0,NaN,NaN

data/precomputed/fig05/learning_stability_checkpoint_summary.csv

,group,window,n_adjacent_comparisons,median_adjacent_pearson,median_adjacent_spearman,mean_adjacent_sign_agreement,median_relative_RMS_change,n_seeds,replication_unit
0,3MIDD_048,common0_100k,100,0.937165,0.887912,0.882143,0.319792,14,seed; comparisons are ordered and dependent
1,3MIDD_048,late_common80_100k,20,0.960266,0.958242,0.942857,0.231761,14,seed; comparisons are ordered and dependent
2,3MIDD_207,common0_100k,100,0.931616,0.925275,0.881429,0.324380,14,seed; comparisons are ordered and dependent
3,3MIDD_207,late_common80_100k,20,0.921104,0.940659,0.989286,0.395772,14,seed; comparisons are ordered and dependent
4,4MIDD_085_170,common0_100k,100,0.922781,0.887912,0.827143,0.378949,14,seed; comparisons are ordered and dependent
5,4MIDD_085_170,late_common80_100k,20,0.943305,0.938462,0.950000,0.287694,14,seed; comparisons are ordered and dependent

## 8. Figure generation
The shared plotting source preserves the adopted layout and labels; no manual PDF editing.

In [8]:
fig = render(FIGURE)
display(fig)

Saved S8 inputs 5 checks 1

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [9]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: S8 primary tables: 2 adopted tables: 6

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [10]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/supplementary/fig_S8.ipynb
Model inference: False