# Figure S9

Stable-denominator common-gray results are separate from the 21-condition baseline and recurrent perturbation source families.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [name for name in ("numpy", "pandas", "matplotlib")
               if importlib.util.find_spec(name) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = 'S9'

from flyvis_midd.figure_analysis import table

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/fig06/...,e3ec244647fb0594d99b3c77763414b9ebfd3cdedfe3a7...,13238
1,data/precomputed/fig06/exp09_coupling_by_model...,f6f1580d8a91cbff04baef62344436e1574a038d6de7b1...,64412
2,data/precomputed/fig06/exp10_model_level_stati...,910f4744e05d4f4e6d8d5ed74478f5a9790f51d6674c75...,14886
3,data/precomputed/fig06/mve02_sintel_specificit...,c875c3fca4ee63e9713c362224ae598cd18af77fd41042...,1545
4,data/precomputed/fig06/exp09_activity_by_model...,bf42d6be9eb73bc07ece9f6ae8f5e5590a319549bf0666...,529438
5,data/precomputed/fig06/mve02_midd_matched_rand...,913fd9f63d771aab277d9b147c683a5683fa8a1fce7ee7...,10382124
6,data/precomputed/fig06/...,12f2b7195d111615289cad69ad4311af12cf563f4608df...,5329
7,data/precomputed/fig06/...,e1ea0c57a146da3423ca47a0a7715ee107d40116e883a4...,3249
8,data/precomputed/fig03/...,af9bcc64596db095eb3198ee30c11b2e4a120e988f4370...,29693
9,data/precomputed/fig03/...,ac03e9ec916b620975ac2b2132b72eb302221ab9b3d477...,9804
10,data/precomputed/fig03/...,9a47b34f9aaa631b25a39d3a351c789f3905fc43a05cfb...,2767
11,data/precomputed/fig06/...,36a4f61de1accd16dec753caa53a78e4ebb075658b85f2...,233951

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 12

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

                                               check  passed
0  A/S identity: data/precomputed/fig06/mve02_mid...    True

## 5. Primary analysis
For Fig3/S7, affine fits and both held-out splits are recomputed from saved A3/A4. Native and multi-field definitions remain separate.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

paired_noop_normalized_changes

,model_id,intervention,condition,baseline,intervention_value,G_noop,raw_delta,normalized_change,baseline_aligned_attenuation,projected_MIDD_gain,RMS_normalized_difference
0,0,T4,MIDD,-0.001862,-0.013206,0.189787,-0.011344,-0.059772,-0.059772,-1.112365,3.048947
1,0,T4,propeller,9.756061,6.612944,10.712049,-3.143117,-0.293419,0.293419,-1.112365,3.048947
2,0,T4,edge,0.832073,0.813430,1.153256,-0.018644,-0.016166,0.016166,-1.112365,3.048947
3,0,T4_T5,MIDD,-0.001862,-0.001399,0.189787,0.000463,0.002439,0.002439,0.183834,0.852881
4,0,T4_T5,propeller,9.756061,4.006075,10.712049,-5.749985,-0.536777,0.536777,0.183834,0.852881
5,0,T4_T5,edge,0.832073,0.761638,1.153256,-0.070436,-0.061075,0.061075,0.183834,0.852881
6,0,T4a,MIDD,-0.001862,-0.001900,0.189787,-0.000038,-0.000200,-0.000200,0.397955,0.703503
7,0,T4a,propeller,9.756061,8.184284,10.712049,-1.571777,-0.146730,0.146730,0.397955,0.703503
8,0,T4a,edge,0.832073,0.395950,1.153256,-0.436123,-0.378167,0.378167,0.397955,0.703503
9,0,T4b,MIDD,-0.001862,-0.005152,0.189787,-0.003290,-0.017334,-0.017334,0.975361,0.490710
10,0,T4b,propeller,9.756061,7.910101,10.712049,-1.845960,-0.172326,0.172326,0.975361,0.490710
11,0,T4b,edge,0.832073,0.856499,1.153256,0.024426,0.021180,-0.021180,0.975361,0.490710
12,0,all_input,MIDD,-0.001862,0.000000,0.189787,0.001862,0.009811,0.009811,0.000000,1.000000
13,0,all_input,propeller,9.756061,0.000000,10.712049,-9.756061,-0.910756,0.910756,0.000000,1.000000
14,0,all_input,edge,0.832073,0.000000,1.153256,-0.832073,-0.721499,0.721499,0.000000,1.000000
15,0,sham,MIDD,-0.001862,-0.001553,0.189787,0.000309,0.001631,0.001631,0.986491,0.075495
16,0,sham,propeller,9.756061,8.906586,10.712049,-0.849475,-0.079301,0.079301,0.986491,0.075495
17,0,sham,edge,0.832073,0.692714,1.153256,-0.139359,-0.120840,0.120840,0.986491,0.075495
18,1,T4,MIDD,-0.001428,-0.000064,0.154596,0.001364,0.008823,0.008823,0.243796,0.764560
19,1,T4,propeller,10.720002,2.583221,11.467406,-8.136781,-0.709557,0.709557,0.243796,0.764560

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig06/replacement_paired_losses.csv

,model_id,intervention,A_C48_noop,A_C48_intervention,MIDD_loss,propeller_loss,edge_loss,propeller_magnitude_loss,MIDD_absolute_loss,projected_MIDD_loss,D_primary,D_edge,D_projected,denominators_valid,A_sign_flip
0,0,T4,-0.001862,-0.013206,-6.092053,0.322171,0.022406,0.198639,-6.092053,2.112365,-6.414224,-6.114460,1.790194,True,False
1,0,T4_T5,-0.001862,-0.001399,0.248546,0.589376,0.084651,0.489372,0.248546,0.816166,-0.340830,0.163895,0.226791,True,False
2,0,T4a,-0.001862,-0.001900,-0.020419,0.161108,0.524140,0.055375,-0.020419,0.602045,-0.181527,-0.544560,0.440937,True,False
3,0,T4b,-0.001862,-0.005152,-1.766716,0.189212,-0.029355,-0.030239,-1.766716,0.024639,-1.955928,-1.737361,-0.164573,True,False
4,0,all_input,-0.001862,0.000000,1.000000,1.000000,1.000000,0.986147,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
5,0,sham,-0.001862,-0.001553,0.166192,0.087072,0.167484,0.079138,0.166192,0.013509,0.079120,-0.001293,-0.073562,True,False
6,1,T4,-0.001428,-0.000064,0.955027,0.759028,0.788907,0.298910,0.955027,0.756204,0.196000,0.166121,-0.002824,True,False
7,1,T4_T5,-0.001428,0.000092,1.064399,0.919804,0.853966,0.606969,0.935601,0.871811,0.144596,0.210434,-0.047993,True,True
8,1,T4a,-0.001428,-0.001835,-0.284621,0.190935,1.045217,0.021094,-0.284621,0.155034,-0.475556,-1.329838,-0.035901,True,False
9,1,T4b,-0.001428,-0.001422,0.004366,0.215717,0.021275,-0.017355,0.004366,0.316807,-0.211351,-0.016909,0.101089,True,False
10,1,all_input,-0.001428,0.000000,1.000000,1.000000,1.000000,0.982540,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
11,1,sham,-0.001428,-0.001424,0.003298,-0.034341,-0.018691,-0.031616,0.003298,0.000256,0.037639,0.021989,0.034597,True,False
12,2,T4,-0.011689,-0.000197,0.983119,0.692448,0.595581,0.472069,0.983119,0.959445,0.290672,0.387538,0.266998,True,False
13,2,T4_T5,-0.011689,-0.000422,0.963900,0.778919,0.861892,0.690834,0.963900,0.932324,0.184981,0.102008,0.153406,True,False
14,2,T4a,-0.011689,-0.008286,0.291120,0.245263,0.512111,0.040560,0.291120,0.255725,0.045857,-0.220991,0.010462,True,False
15,2,T4b,-0.011689,-0.010896,0.067844,0.098277,-0.212452,0.077199,0.067844,0.029200,-0.030432,0.280296,-0.069077,True,False
16,2,all_input,-0.011689,0.000000,1.000000,1.000000,1.000000,0.985785,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
17,2,sham,-0.011689,-0.009669,0.172802,-0.002202,0.029208,-0.000896,0.172802,0.147645,0.175004,0.143594,0.149848,True,False
18,3,T4,-0.030285,-0.006838,0.774211,0.700633,0.328959,0.381318,0.774211,0.744413,0.073578,0.445252,0.043780,True,False
19,3,T4_T5,-0.030285,-0.005673,0.812665,0.786315,0.855051,0.284888,0.812665,0.793785,0.026350,-0.042386,0.007470,True,False

data/precomputed/fig06/replacement_qa.csv

    model_id          group     max_error  passed                    check
0          0      3MIDD_048  6.355295e-08    True  pre_extension_canonical
1          0      3MIDD_207  2.538126e-08    True  pre_extension_canonical
2          0  4MIDD_085_170  2.009836e-08    True  pre_extension_canonical
3          0            NaN           NaN    True              noop_Static
4          0            NaN           NaN    True                  noop_CW
5          0            NaN           NaN    True                 noop_CCW
6          0            NaN           NaN    True               noop_Right
7          0            NaN           NaN    True                noop_Left
8          0            NaN           NaN    True     noop_MIDD_0_original
9          0            NaN           NaN    True       noop_MIDD_0_mirror
10         0            NaN           NaN    True    noop_MIDD_48_original
11         0            NaN           NaN    True      noop_MIDD_48_mirror
12         0            NaN           NaN    True    noop_MIDD_85_original
13         0            NaN           NaN    True      noop_MIDD_85_mirror
14         0            NaN           NaN    True   noop_MIDD_128_original
15         0            NaN           NaN    True     noop_MIDD_128_mirror
16         0            NaN           NaN    True   noop_MIDD_170_original
17         0            NaN           NaN    True     noop_MIDD_170_mirror
18         0            NaN           NaN    True   noop_MIDD_207_original
19         0            NaN           NaN    True     noop_MIDD_207_mirror

data/precomputed/fig06/replacement_bootstrap.csv

,intervention,metric,n_models,mean,median,ci_low,ci_high
0,T4,MIDD_loss,10,-0.819937,0.864619,-3.453122,1.103754
1,T4,propeller_loss,10,0.596824,0.599281,0.520820,0.661208
2,T4,edge_loss,10,0.458687,0.566652,0.100500,0.752396
3,T4,propeller_magnitude_loss,10,0.286890,0.261829,0.216857,0.360765
4,T4,D_primary,10,-1.416760,0.203123,-3.987315,0.479301
5,T4,D_edge,10,-1.278624,0.291629,-3.951124,0.735470
6,T4,D_projected,10,0.255264,0.179512,-0.019905,0.638554
7,T4,MIDD_absolute_loss,10,-1.042770,0.742496,-3.582718,0.790762
8,T4_T5,MIDD_loss,10,-0.147103,1.014150,-2.753953,1.327386
9,T4_T5,propeller_loss,10,0.709927,0.696193,0.649792,0.776163
10,T4_T5,edge_loss,10,0.816967,0.854508,0.596886,1.035659
11,T4_T5,propeller_magnitude_loss,10,0.444166,0.460585,0.342795,0.542837
12,T4_T5,D_primary,10,-0.857030,0.196899,-3.450746,0.616261
13,T4_T5,D_edge,10,-0.964070,0.134982,-3.538832,0.473123
14,T4_T5,D_projected,10,0.021974,0.068554,-0.146255,0.143973
15,T4_T5,MIDD_absolute_loss,10,-0.544858,0.816775,-3.029925,0.814393
16,T4a,MIDD_loss,10,0.424107,0.174111,0.016532,1.049922
17,T4a,propeller_loss,10,0.181795,0.176829,0.156547,0.207859
18,T4a,edge_loss,10,0.450430,0.518126,0.230587,0.662403
19,T4a,propeller_magnitude_loss,10,0.051751,0.030827,0.011005,0.098153

data/precomputed/fig06/robust_intervention_model_metrics.csv

,model_id,intervention,condition,baseline,intervention_value,G_noop,raw_delta,normalized_change,baseline_aligned_attenuation,projected_MIDD_gain,RMS_normalized_difference
0,0,T4,MIDD,-0.001862,-0.013206,0.189787,-0.011344,-0.059772,-0.059772,-1.112365,3.048947
1,0,T4,propeller,9.756061,6.612944,10.712049,-3.143117,-0.293419,0.293419,-1.112365,3.048947
2,0,T4,edge,0.832073,0.813430,1.153256,-0.018644,-0.016166,0.016166,-1.112365,3.048947
3,0,T4_T5,MIDD,-0.001862,-0.001399,0.189787,0.000463,0.002439,0.002439,0.183834,0.852881
4,0,T4_T5,propeller,9.756061,4.006075,10.712049,-5.749985,-0.536777,0.536777,0.183834,0.852881
5,0,T4_T5,edge,0.832073,0.761638,1.153256,-0.070436,-0.061075,0.061075,0.183834,0.852881
6,0,T4a,MIDD,-0.001862,-0.001900,0.189787,-0.000038,-0.000200,-0.000200,0.397955,0.703503
7,0,T4a,propeller,9.756061,8.184284,10.712049,-1.571777,-0.146730,0.146730,0.397955,0.703503
8,0,T4a,edge,0.832073,0.395950,1.153256,-0.436123,-0.378167,0.378167,0.397955,0.703503
9,0,T4b,MIDD,-0.001862,-0.005152,0.189787,-0.003290,-0.017334,-0.017334,0.975361,0.490710
10,0,T4b,propeller,9.756061,7.910101,10.712049,-1.845960,-0.172326,0.172326,0.975361,0.490710
11,0,T4b,edge,0.832073,0.856499,1.153256,0.024426,0.021180,-0.021180,0.975361,0.490710
12,0,all_input,MIDD,-0.001862,0.000000,0.189787,0.001862,0.009811,0.009811,0.000000,1.000000
13,0,all_input,propeller,9.756061,0.000000,10.712049,-9.756061,-0.910756,0.910756,0.000000,1.000000
14,0,all_input,edge,0.832073,0.000000,1.153256,-0.832073,-0.721499,0.721499,0.000000,1.000000
15,0,sham,MIDD,-0.001862,-0.001553,0.189787,0.000309,0.001631,0.001631,0.986491,0.075495
16,0,sham,propeller,9.756061,8.906586,10.712049,-0.849475,-0.079301,0.079301,0.986491,0.075495
17,0,sham,edge,0.832073,0.692714,1.153256,-0.139359,-0.120840,0.120840,0.986491,0.075495
18,1,T4,MIDD,-0.001428,-0.000064,0.154596,0.001364,0.008823,0.008823,0.243796,0.764560
19,1,T4,propeller,10.720002,2.583221,11.467406,-8.136781,-0.709557,0.709557,0.243796,0.764560

data/precomputed/fig06/robust_intervention_summary.csv

,intervention,condition,metric,mean,median,ci_low,ci_high
0,T4,MIDD,normalized_change,0.054487,0.049030,0.013611,0.100006
1,T4,MIDD,baseline_aligned_attenuation,0.051874,0.049030,0.010934,0.098355
2,T4,MIDD,raw_delta,0.007052,0.007322,0.001366,0.012364
3,T4,MIDD,projected_MIDD_gain,0.147913,0.219336,-0.177908,0.405746
4,T4,MIDD,RMS_normalized_difference,1.073006,0.842099,0.800362,1.536004
5,T4,edge,normalized_change,-0.344956,-0.450122,-0.572562,-0.065389
6,T4,edge,baseline_aligned_attenuation,0.344956,0.450122,0.064527,0.574440
7,T4,edge,raw_delta,-0.438624,-0.488432,-0.702564,-0.157349
8,T4,edge,projected_MIDD_gain,0.147913,0.219336,-0.183183,0.400032
9,T4,edge,RMS_normalized_difference,1.073006,0.842099,0.801035,1.532324
10,T4,propeller,normalized_change,-0.561353,-0.565466,-0.620647,-0.488791
11,T4,propeller,baseline_aligned_attenuation,0.561353,0.565466,0.489892,0.621270
12,T4,propeller,raw_delta,-6.390817,-6.328147,-7.348119,-5.379763
13,T4,propeller,projected_MIDD_gain,0.147913,0.219336,-0.189237,0.400130
14,T4,propeller,RMS_normalized_difference,1.073006,0.842099,0.800587,1.539613
15,T4_T5,MIDD,normalized_change,0.066961,0.055970,0.030516,0.110402
16,T4_T5,MIDD,baseline_aligned_attenuation,0.064112,0.055970,0.026616,0.107839
17,T4_T5,MIDD,raw_delta,0.009058,0.008949,0.004815,0.013936
18,T4_T5,MIDD,projected_MIDD_gain,0.268099,0.195025,0.142934,0.461740
19,T4_T5,MIDD,RMS_normalized_difference,0.905201,0.856730,0.809103,1.030693

data/precomputed/fig06/denominator_audit.csv

,intervention,condition,q0,q5,q25,q50,q75,q95,q100,n,excluded
0,T4,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
1,T4,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
2,T4,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
3,T4_T5,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
4,T4_T5,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
5,T4_T5,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
6,T4a,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
7,T4a,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
8,T4a,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
9,T4b,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
10,T4b,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
11,T4b,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
12,all_input,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
13,all_input,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
14,all_input,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
15,sham,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
16,sham,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
17,sham,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0

data/precomputed/fig06/replacement_metrics.csv

,model_id,condition,intervention,mean_flow_magnitude,mean_signed_tangent,mean_abs_tangent,signed_tangent_ratio,rotation_coherence,mean_signed_radial,annulus_positions,annulus_receptors,mean_u
0,0,Static,noop,0.275658,-0.107649,0.139993,-0.390517,0.768963,0.178290,698,698,-0.076315
1,0,Static,T4a,0.387465,-0.099979,0.189618,-0.258034,0.527265,0.174250,698,698,-0.008540
2,0,Static,T4b,0.500321,-0.024984,0.304798,-0.049936,0.081969,0.160870,698,698,-0.400876
3,0,Static,T4,1.616435,0.149755,0.996580,0.092645,0.150269,0.386532,698,698,-0.743651
4,0,Static,T4_T5,1.354645,-0.021478,0.803792,-0.015855,0.026721,0.611023,698,698,-0.493896
5,0,Static,sham,0.269857,-0.085025,0.137967,-0.315075,0.616273,0.144984,698,698,-0.153208
6,0,Static,all_input,0.148397,0.032469,0.075630,0.218801,0.429321,0.084941,698,698,-0.092684
7,0,CW,noop,10.784526,9.815791,9.960090,0.910174,0.985512,1.365292,698,698,0.445993
8,0,CW,T4a,10.126642,8.102660,8.523523,0.800133,0.950623,1.450428,698,698,3.169957
9,0,CW,T4b,11.227115,7.922450,9.241721,0.705653,0.857248,1.789472,698,698,-3.540715
10,0,CW,T4,8.688635,6.609141,7.221971,0.760665,0.915144,1.609094,698,698,-1.281635
11,0,CW,T4_T5,5.594470,4.031019,4.333545,0.720536,0.930190,0.550387,698,698,1.222162
12,0,CW,sham,9.932143,8.967919,9.116608,0.902919,0.983690,1.249587,698,698,-0.065840
13,0,CW,all_input,0.148397,0.032469,0.075630,0.218801,0.429321,0.084941,698,698,-0.092684
14,0,CCW,noop,10.639571,-9.696330,9.766401,-0.911346,0.992825,-0.189845,698,698,0.032985
15,0,CCW,T4a,10.111106,-8.265908,8.604373,-0.817508,0.960664,-0.430680,698,698,2.759341
16,0,CCW,T4b,10.844828,-7.897752,8.839176,-0.728251,0.893494,-0.814654,698,698,-3.762819
17,0,CCW,T4,8.479799,-6.616747,7.069857,-0.780295,0.935910,-0.183567,698,698,-1.357840
18,0,CCW,T4_T5,5.345282,-3.981132,4.220748,-0.744794,0.943229,0.514173,698,698,1.141540
19,0,CCW,sham,9.796504,-8.845252,8.936096,-0.902899,0.989834,-0.098964,698,698,-0.417888

### A. Common-baseline controls
The matched-control analysis uses the same gray decoder-input replacement for MIDD, propeller, and moving edge. Model-wise paired losses remain the primary comparison.

In [7]:
for suffix in ['paired_losses.csv']:
    print(suffix)
    display(table(tables, suffix).head(20))

paired_losses.csv

,model_id,intervention,A_C48_noop,A_C48_intervention,MIDD_loss,propeller_loss,edge_loss,propeller_magnitude_loss,MIDD_absolute_loss,projected_MIDD_loss,D_primary,D_edge,D_projected,denominators_valid,A_sign_flip
0,0,T4,-0.001862,-0.013206,-6.092053,0.322171,0.022406,0.198639,-6.092053,2.112365,-6.414224,-6.114460,1.790194,True,False
1,0,T4_T5,-0.001862,-0.001399,0.248546,0.589376,0.084651,0.489372,0.248546,0.816166,-0.340830,0.163895,0.226791,True,False
2,0,T4a,-0.001862,-0.001900,-0.020419,0.161108,0.524140,0.055375,-0.020419,0.602045,-0.181527,-0.544560,0.440937,True,False
3,0,T4b,-0.001862,-0.005152,-1.766716,0.189212,-0.029355,-0.030239,-1.766716,0.024639,-1.955928,-1.737361,-0.164573,True,False
4,0,all_input,-0.001862,0.000000,1.000000,1.000000,1.000000,0.986147,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
5,0,sham,-0.001862,-0.001553,0.166192,0.087072,0.167484,0.079138,0.166192,0.013509,0.079120,-0.001293,-0.073562,True,False
6,1,T4,-0.001428,-0.000064,0.955027,0.759028,0.788907,0.298910,0.955027,0.756204,0.196000,0.166121,-0.002824,True,False
7,1,T4_T5,-0.001428,0.000092,1.064399,0.919804,0.853966,0.606969,0.935601,0.871811,0.144596,0.210434,-0.047993,True,True
8,1,T4a,-0.001428,-0.001835,-0.284621,0.190935,1.045217,0.021094,-0.284621,0.155034,-0.475556,-1.329838,-0.035901,True,False
9,1,T4b,-0.001428,-0.001422,0.004366,0.215717,0.021275,-0.017355,0.004366,0.316807,-0.211351,-0.016909,0.101089,True,False
10,1,all_input,-0.001428,0.000000,1.000000,1.000000,1.000000,0.982540,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
11,1,sham,-0.001428,-0.001424,0.003298,-0.034341,-0.018691,-0.031616,0.003298,0.000256,0.037639,0.021989,0.034597,True,False
12,2,T4,-0.011689,-0.000197,0.983119,0.692448,0.595581,0.472069,0.983119,0.959445,0.290672,0.387538,0.266998,True,False
13,2,T4_T5,-0.011689,-0.000422,0.963900,0.778919,0.861892,0.690834,0.963900,0.932324,0.184981,0.102008,0.153406,True,False
14,2,T4a,-0.011689,-0.008286,0.291120,0.245263,0.512111,0.040560,0.291120,0.255725,0.045857,-0.220991,0.010462,True,False
15,2,T4b,-0.011689,-0.010896,0.067844,0.098277,-0.212452,0.077199,0.067844,0.029200,-0.030432,0.280296,-0.069077,True,False
16,2,all_input,-0.011689,0.000000,1.000000,1.000000,1.000000,0.985785,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
17,2,sham,-0.011689,-0.009669,0.172802,-0.002202,0.029208,-0.000896,0.172802,0.147645,0.175004,0.143594,0.149848,True,False
18,3,T4,-0.030285,-0.006838,0.774211,0.700633,0.328959,0.381318,0.774211,0.744413,0.073578,0.445252,0.043780,True,False
19,3,T4_T5,-0.030285,-0.005673,0.812665,0.786315,0.855051,0.284888,0.812665,0.793785,0.026350,-0.042386,0.007470,True,False

### B. Historical activity association
Activity associations are observational and are separate from the matched-control intervention contract.

In [8]:
for suffix in ['exp09_coupling_by_model.csv', 'exp09_activity_by_model_luminance.csv']:
    print(suffix)
    display(table(tables, suffix).head(20))

exp09_coupling_by_model.csv

,model_id,cell_type,rho_signed,rho_absolute,sign_agreement,zero_nearest_cell,zero_nearest_flow,response_identifiable,mean_spatial_cosine,mean_mirror_antisymmetry,intercept,slope,r2,rmse
0,0,T2,0.785714,0.785714,0.428571,207,143,False,0.008348,0.005282,-0.062251,22.834915,0.766712,0.023847
1,0,T2a,0.857143,0.857143,0.857143,175,143,False,0.000289,0.000000,-0.008741,471.754256,0.814226,0.021280
2,0,T3,-0.250000,0.250000,0.571429,207,143,True,-0.011495,0.764770,-0.073103,-55.310784,0.104602,0.046718
3,0,T4a,0.892857,0.892857,0.428571,207,143,True,0.008624,0.839443,-0.144155,64.849776,0.984945,0.006058
4,0,T4b,0.964286,0.964286,0.857143,143,143,False,0.002643,0.438709,-0.010330,30.666586,0.988440,0.005308
5,0,T4c,-0.964286,0.964286,0.000000,112,143,True,0.001340,0.616878,0.015980,-19.653853,0.978976,0.007159
6,0,T4d,-0.500000,0.500000,0.142857,80,143,True,0.001852,0.100442,0.038032,-81.765858,0.369083,0.039216
7,0,T5a,0.892857,0.892857,0.857143,175,143,False,0.006010,0.057686,-0.023540,30.474208,0.900375,0.015583
8,0,T5b,0.892857,0.892857,1.000000,207,143,False,0.001883,0.003325,-0.006605,50.245194,0.908673,0.014920
9,0,T5c,-0.892857,0.892857,0.571429,207,143,True,-0.018344,0.815446,-0.084743,-28.133462,0.994235,0.003749
10,0,T5d,0.892857,0.892857,0.857143,112,143,False,-0.001746,0.453025,0.028334,42.634271,0.855326,0.018779
11,0,Tm1,-0.928571,0.928571,0.000000,112,143,True,0.002913,0.325273,0.018777,-275.698209,0.968915,0.008705
12,0,Tm16,0.785714,0.785714,0.714286,48,143,False,-0.002311,0.339583,0.073038,319.823443,0.774681,0.023436
13,0,Tm2,0.392857,0.392857,0.571429,48,143,True,-0.007856,0.744632,0.102001,114.844815,0.342629,0.040030
14,0,Tm20,-0.785714,0.785714,0.571429,207,143,False,-0.016649,0.192305,-0.081281,-218.961145,0.708281,0.026666
15,0,Tm28,-0.785714,0.785714,0.571429,207,143,True,-0.003124,0.651276,-0.080138,-164.389230,0.732043,0.025557
16,0,Tm3,-0.928571,0.928571,0.000000,112,143,False,0.000126,0.279921,0.013634,-195.702445,0.962355,0.009579
17,0,Tm30,0.464286,0.464286,0.428571,207,143,False,0.002976,0.000000,-0.056600,19604.491143,0.144439,0.045667
18,0,Tm4,-0.892857,0.892857,0.142857,80,143,True,0.016477,0.814698,0.044359,-34.861977,0.877787,0.017260
19,0,Tm5Y,-0.857143,0.857143,0.428571,191,143,True,-0.002918,0.463241,-0.045729,-208.008579,0.830473,0.020328

exp09_activity_by_model_luminance.csv

,model_id,cell_type,c,e_raw,e_original_projected,e_mirror_projected,e_negative_control,spatial_cosine,mirror_antisymmetry,n_global_positions,pd_resultant_lomo,response_scale_rms,control_response_threshold,e_normalized,response_identifiable
0,0,T2,48,0.003588,-0.005247,-0.012423,-0.008992,0.009928,0.000000,2790,0.887383,0.003620,0.008992,0.991050,False
1,0,T2,80,0.005556,-0.001726,-0.012838,-0.007416,0.015170,0.000000,2790,0.887383,0.003620,0.008992,1.534648,False
2,0,T2,112,0.005586,0.000207,-0.010966,-0.005422,0.015070,0.036975,2790,0.887383,0.003620,0.008992,1.542938,False
3,0,T2,143,0.003459,-0.000352,-0.007271,-0.003407,0.009241,0.000000,2790,0.887383,0.003620,0.008992,0.955423,False
4,0,T2,175,0.001772,-0.000586,-0.004131,-0.001517,0.004697,0.000000,2790,0.887383,0.003620,0.008992,0.489562,False
5,0,T2,191,0.001240,-0.000483,-0.002962,-0.000903,0.003275,0.000000,2790,0.887383,0.003620,0.008992,0.342399,False
6,0,T2,207,0.000401,-0.000744,-0.001545,-0.000284,0.001055,0.000000,2790,0.887383,0.003620,0.008992,0.110626,False
7,0,T2a,48,0.000141,0.000376,0.000095,0.000353,0.001127,0.000000,2790,0.369438,0.000101,0.000379,1.393276,False
8,0,T2a,80,0.000205,0.000461,0.000051,0.000312,0.001627,0.000000,2790,0.369438,0.000101,0.000379,2.024293,False
9,0,T2a,112,0.000017,0.000223,0.000188,0.000359,0.000138,0.000000,2790,0.369438,0.000101,0.000379,0.172571,False
10,0,T2a,143,0.000026,0.000224,0.000173,0.000379,0.000202,0.000000,2790,0.369438,0.000101,0.000379,0.253788,False
11,0,T2a,175,-0.000014,0.000190,0.000217,0.000313,-0.000107,0.000000,2790,0.369438,0.000101,0.000379,-0.135259,False
12,0,T2a,191,-0.000038,0.000128,0.000205,0.000248,-0.000302,0.000000,2790,0.369438,0.000101,0.000379,-0.380674,False
13,0,T2a,207,-0.000085,0.000049,0.000219,0.000186,-0.000665,0.000000,2790,0.369438,0.000101,0.000379,-0.837995,False
14,0,T3,48,-0.001174,-0.001670,0.000677,-0.000558,-0.009447,0.576974,2790,0.724851,0.001498,0.000558,-0.783401,True
15,0,T3,80,-0.001696,-0.002130,0.001262,-0.000401,-0.013457,0.744262,2790,0.724851,0.001498,0.000558,-1.131891,True
16,0,T3,112,-0.001774,-0.002070,0.001478,-0.000281,-0.013888,0.833266,2790,0.724851,0.001498,0.000558,-1.184050,True
17,0,T3,143,-0.001814,-0.002080,0.001547,-0.000152,-0.014065,0.853203,2790,0.724851,0.001498,0.000558,-1.210478,True
18,0,T3,175,-0.001514,-0.001796,0.001231,-0.000035,-0.011688,0.813499,2790,0.724851,0.001498,0.000558,-1.010257,True
19,0,T3,191,-0.001302,-0.001578,0.001026,0.000009,-0.010053,0.787858,2790,0.724851,0.001498,0.000558,-0.868986,True

### C. Historical replacement
The historical 21-condition replacement has a different baseline and is not pooled with common-gray paired losses.

In [9]:
for suffix in ['exp10_model_level_statistics_corrected.csv']:
    print(suffix)
    display(table(tables, suffix).head(20))

exp10_model_level_statistics_corrected.csv

,intervention_id,mean_loss,ci95_low,ci95_high,median_loss,sd_loss,n_loss_positive,p_signflip,mean_shape_residual,mean_propeller_loss,mean_specificity,kind,method,cell_types,family,inference_family,q_prespecified_family
0,control__all34__baseline,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,10,0.001951,0.000000e+00,1.000000,0.000000e+00,control,baseline,T1|T2|T2a|T3|T4a|T4b|T4c|T4d|T5a|T5b|T5c|T5d|T...,controls,controls,0.001951
1,control__all34__zero,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,10,0.001951,0.000000e+00,1.000000,0.000000e+00,control,zero,T1|T2|T2a|T3|T4a|T4b|T4c|T4d|T5a|T5b|T5c|T5d|T...,controls,controls,0.001951
2,control__noop,1.365574e-15,9.214851e-16,1.876277e-15,1.276756e-15,8.242778e-16,10,0.001951,8.918803e-16,0.000000,1.365574e-15,control,noop,NaN,controls,controls,0.001951
3,control__sham,1.365574e-15,9.214851e-16,1.876277e-15,1.276756e-15,8.242778e-16,10,0.001951,8.918803e-16,0.000000,1.365574e-15,control,sham,NaN,controls,controls,0.001951
4,group__T4_T5__baseline,6.281187e-01,2.636447e-01,9.094720e-01,8.146622e-01,5.613993e-01,9,0.006829,3.482151e-01,0.608594,1.952503e-02,group,baseline,T4a|T4b|T4c|T4d|T5a|T5b|T5c|T5d,groups,prespecified_groups,0.017073
5,group__T4_family__baseline,3.867609e-01,8.699287e-02,6.602980e-01,4.854555e-01,4.897838e-01,8,0.018537,4.633981e-01,0.523298,-1.365375e-01,group,baseline,T4a|T4b|T4c|T4d,groups,prespecified_groups,0.030894
6,group__T5_family__baseline,3.903721e-02,-7.895861e-02,1.805629e-01,1.367888e-02,2.212674e-01,5,0.323902,2.460667e-01,0.117896,-7.885919e-02,group,baseline,T5a|T5b|T5c|T5d,groups,prespecified_groups,0.323902
7,group__formal_candidates__baseline,1.310806e-01,-1.185251e-01,3.689800e-01,2.067920e-01,4.142433e-01,7,0.170732,3.661687e-01,0.296926,-1.658458e-01,group,baseline,T4a|TmY14|T2a|Tm16,groups,prespecified_groups,0.213415
8,group__formal_candidates_plus_T4b__baseline,4.943027e-01,2.894050e-01,7.101164e-01,4.870294e-01,3.597412e-01,10,0.001951,4.499603e-01,0.375332,1.189704e-01,group,baseline,T4a|TmY14|T2a|Tm16|T4b,groups,prespecified_groups,0.009756
9,single__T1__baseline,-2.943943e-01,-7.379929e-01,2.432923e-02,-2.709533e-02,6.672882e-01,3,0.887805,3.719104e-01,0.067833,-3.622274e-01,single,baseline,T1,screen,exploratory_34_screen,0.986341
10,single__T2__baseline,1.170653e-03,-2.614709e-02,3.210142e-02,-8.203483e-03,4.981455e-02,5,0.476098,1.257776e-01,0.128307,-1.271365e-01,single,baseline,T2,screen,exploratory_34_screen,0.986341
11,single__T2a__baseline,-3.522023e-02,-1.170210e-01,3.892998e-02,6.790363e-03,1.330694e-01,6,0.774634,1.140357e-01,0.029449,-6.466924e-02,single,baseline,T2a,screen,secondary_3,0.774634
12,single__T2a__constant_tonic,-2.946972e-02,-1.109115e-01,4.260353e-02,7.087847e-03,1.313758e-01,6,0.739512,1.130423e-01,0.029449,-5.891873e-02,sensitivity,constant_tonic,T2a,sensitivity,sensitivity,0.987317
13,single__T2a__zero,-3.027464e+00,-5.864787e+00,-8.288166e-01,-1.672529e+00,4.380446e+00,1,0.987317,1.016838e+00,-0.121423,-2.906041e+00,sensitivity,zero,T2a,sensitivity,sensitivity,0.987317
14,single__T3__baseline,-9.952616e-05,-4.205123e-02,5.470998e-02,-5.658525e-03,8.352308e-02,4,0.502439,8.478030e-02,-0.029016,2.891608e-02,single,baseline,T3,screen,exploratory_34_screen,0.986341
15,single__T4a__baseline,5.172520e-02,-9.341165e-02,1.868751e-01,8.584934e-02,2.394808e-01,6,0.253659,2.930976e-01,0.177149,-1.254237e-01,single,baseline,T4a,screen,confirmatory_T4a,0.253659
16,single__T4a__constant_tonic,5.432499e-02,-9.245053e-02,1.905573e-01,8.982091e-02,2.409729e-01,6,0.249756,2.948046e-01,0.177149,-1.228239e-01,sensitivity,constant_tonic,T4a,sensitivity,sensitivity,0.624390
17,single__T4a__zero,4.426202e-02,-1.517688e-01,2.246771e-01,7.330721e-02,3.206012e-01,7,0.333659,3.622707e-01,0.193522,-1.492604e-01,sensitivity,zero,T4a,sensitivity,sensitivity,0.629268
18,single__T4b__baseline,2.620879e-01,1.558132e-01,3.665609e-01,2.842981e-01,1.807230e-01,10,0.001951,3.079083e-01,0.106334,1.557535e-01,single,baseline,T4b,screen,exploratory_34_screen,0.029268
19,single__T4b__constant_tonic,2.592955e-01,1.555195e-01,3.618506e-01,2.834578e-01,1.762032e-01,10,0.001951,3.087535e-01,0.106334,1.529612e-01,sensitivity,constant_tonic,T4b,sensitivity,sensitivity,0.019512

### D. Recurrent subtype intervention
Recurrent interventions and their Sintel comparison are a separate manipulation, not the decoder-input replacement.

In [10]:
for suffix in ['mve02_sintel_specificity.csv', 'mve02_midd_matched_random.csv']:
    print(suffix)
    display(table(tables, suffix).head(20))

mve02_sintel_specificity.csv

,seed,cohort,set_name,delta_EPE,random_mean_delta_EPE,Z_flow,p_flow,Z_MIDD,relative_Z
0,0,comparator,T4c,0.563759,0.381060,5.462674,0.005,-11.987567,-17.450241
1,0,comparator,T4d,0.542505,0.382145,4.924041,0.005,-5.926494,-10.850535
2,1,established,T4c,0.542732,0.078055,62.987739,0.005,-13.645825,-76.633564
3,1,established,T4d,0.112637,0.078289,4.422555,0.005,-0.154693,-4.577248
4,2,established,T4c,1.087386,0.281102,25.814712,0.005,0.296080,-25.518632
5,2,established,T4d,3.546385,0.277982,118.479367,0.005,8.341981,-110.137386
6,3,established,T4c,0.056825,0.061723,-1.055224,0.855,-6.036686,-4.981462
7,3,established,T4d,0.092492,0.061263,6.312921,0.005,-1.811946,-8.124867
8,8,comparator,T4c,0.622449,0.204442,16.097437,0.005,-8.904868,-25.002305
9,8,comparator,T4d,0.287763,0.205160,3.094434,0.010,-2.047371,-5.141805
10,10,established,T4c,0.819493,0.121738,47.067294,0.005,10.373470,-36.693824
11,10,established,T4d,0.738360,0.123194,45.976744,0.005,-11.778059,-57.754803

mve02_midd_matched_random.csv

,seed,cohort,holdout,optimizer_step,phase_deg,set_name,control,draw,n_nodes,baseline_A,...,delta_M,E_reference,E_abs_A,T_original,T_mirror,A,abs_A,S,M,actual_reversal
0,1,established,False,250000,0.0,T4c,baseline,-2,0,-0.006627,...,0.000000,0.000000,0.000000,-0.000537,0.012716,-0.006627,0.006627,0.006090,0.000537,True
1,1,established,False,250000,0.0,T4c,target,-1,721,-0.006627,...,0.012812,-0.009518,-0.009518,-0.018941,0.013349,-0.016145,0.016145,-0.002796,0.013349,True
2,1,established,False,250000,0.0,T4c,matched_random,0,721,-0.006627,...,0.001165,0.008796,0.004457,0.001702,-0.002638,0.002170,0.002170,-0.000468,0.001702,True
3,1,established,False,250000,0.0,T4c,matched_random,1,721,-0.006627,...,0.002253,0.001099,0.001099,-0.002790,0.008266,-0.005528,0.005528,0.002738,0.002790,True
4,1,established,False,250000,0.0,T4c,matched_random,2,721,-0.006627,...,-0.000726,0.007112,0.006142,0.001159,0.000189,0.000485,0.000485,0.000674,-0.000189,False
5,1,established,False,250000,0.0,T4c,matched_random,3,721,-0.006627,...,0.000967,0.015169,-0.001915,0.015580,-0.001504,0.008542,0.008542,0.007038,0.001504,True
6,1,established,False,250000,0.0,T4c,matched_random,4,721,-0.006627,...,-0.001769,0.007082,0.006172,0.002142,0.001232,0.000455,0.000455,0.001687,-0.001232,False
7,1,established,False,250000,0.0,T4c,matched_random,5,721,-0.006627,...,0.000115,0.004305,0.004305,-0.003992,0.000652,-0.002322,0.002322,-0.001670,0.000652,True
8,1,established,False,250000,0.0,T4c,matched_random,6,721,-0.006627,...,-0.007592,0.011226,0.002028,0.016252,0.007055,0.004599,0.004599,0.011653,-0.007055,False
9,1,established,False,250000,0.0,T4c,matched_random,7,721,-0.006627,...,-0.013356,0.006893,0.006360,0.013352,0.012819,0.000266,0.000266,0.013086,-0.012819,False
10,1,established,False,250000,0.0,T4c,matched_random,8,721,-0.006627,...,-0.002627,0.009402,0.003852,0.007641,0.002090,0.002775,0.002775,0.004865,-0.002090,False
11,1,established,False,250000,0.0,T4c,matched_random,9,721,-0.006627,...,0.002810,0.012278,0.000975,0.007957,-0.003347,0.005652,0.005652,0.002305,0.003347,True
12,1,established,False,250000,0.0,T4c,matched_random,10,721,-0.006627,...,0.001264,0.002460,0.002460,-0.006532,0.001801,-0.004166,0.004166,-0.002366,0.001801,True
13,1,established,False,250000,0.0,T4c,matched_random,11,721,-0.006627,...,-0.005899,0.003514,0.003514,0.005362,0.011588,-0.003113,0.003113,0.008475,-0.005362,False
14,1,established,False,250000,0.0,T4c,matched_random,12,721,-0.006627,...,0.004238,0.015251,-0.001998,0.012474,-0.004775,0.008625,0.008625,0.003850,0.004775,True
15,1,established,False,250000,0.0,T4c,matched_random,13,721,-0.006627,...,-0.004953,0.005236,0.005236,-0.007198,-0.004416,-0.001391,0.001391,-0.005807,-0.004416,False
16,1,established,False,250000,0.0,T4c,matched_random,14,721,-0.006627,...,-0.003907,0.005792,0.005792,0.003370,0.005039,-0.000835,0.000835,0.004205,-0.003370,False
17,1,established,False,250000,0.0,T4c,matched_random,15,721,-0.006627,...,-0.003196,0.016402,-0.003149,0.022210,0.002659,0.009775,0.009775,0.012435,-0.002659,False
18,1,established,False,250000,0.0,T4c,matched_random,16,721,-0.006627,...,0.003355,-0.006451,-0.006451,-0.022264,0.003892,-0.013078,0.013078,-0.009186,0.003892,True
19,1,established,False,250000,0.0,T4c,matched_random,17,721,-0.006627,...,-0.003142,0.007172,0.006082,0.003695,0.002605,0.000545,0.000545,0.003150,-0.002605,False

## 7. Statistics
Model/seed is the unit. Stored intervals retain the original inference choices. Fig3/S7 additionally replay the exact original bootstrap seed and RNG consumption order; cached null draws are not regenerated or tuned.

In [11]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

data/precomputed/fig06/exp10_model_level_statistics_corrected.csv

,intervention_id,mean_loss,ci95_low,ci95_high,median_loss,sd_loss,n_loss_positive,p_signflip,mean_shape_residual,mean_propeller_loss,mean_specificity,kind,method,cell_types,family,inference_family,q_prespecified_family
0,control__all34__baseline,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,10,0.001951,0.000000e+00,1.000000,0.000000e+00,control,baseline,T1|T2|T2a|T3|T4a|T4b|T4c|T4d|T5a|T5b|T5c|T5d|T...,controls,controls,0.001951
1,control__all34__zero,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,10,0.001951,0.000000e+00,1.000000,0.000000e+00,control,zero,T1|T2|T2a|T3|T4a|T4b|T4c|T4d|T5a|T5b|T5c|T5d|T...,controls,controls,0.001951
2,control__noop,1.365574e-15,9.214851e-16,1.876277e-15,1.276756e-15,8.242778e-16,10,0.001951,8.918803e-16,0.000000,1.365574e-15,control,noop,NaN,controls,controls,0.001951
3,control__sham,1.365574e-15,9.214851e-16,1.876277e-15,1.276756e-15,8.242778e-16,10,0.001951,8.918803e-16,0.000000,1.365574e-15,control,sham,NaN,controls,controls,0.001951
4,group__T4_T5__baseline,6.281187e-01,2.636447e-01,9.094720e-01,8.146622e-01,5.613993e-01,9,0.006829,3.482151e-01,0.608594,1.952503e-02,group,baseline,T4a|T4b|T4c|T4d|T5a|T5b|T5c|T5d,groups,prespecified_groups,0.017073
5,group__T4_family__baseline,3.867609e-01,8.699287e-02,6.602980e-01,4.854555e-01,4.897838e-01,8,0.018537,4.633981e-01,0.523298,-1.365375e-01,group,baseline,T4a|T4b|T4c|T4d,groups,prespecified_groups,0.030894
6,group__T5_family__baseline,3.903721e-02,-7.895861e-02,1.805629e-01,1.367888e-02,2.212674e-01,5,0.323902,2.460667e-01,0.117896,-7.885919e-02,group,baseline,T5a|T5b|T5c|T5d,groups,prespecified_groups,0.323902
7,group__formal_candidates__baseline,1.310806e-01,-1.185251e-01,3.689800e-01,2.067920e-01,4.142433e-01,7,0.170732,3.661687e-01,0.296926,-1.658458e-01,group,baseline,T4a|TmY14|T2a|Tm16,groups,prespecified_groups,0.213415
8,group__formal_candidates_plus_T4b__baseline,4.943027e-01,2.894050e-01,7.101164e-01,4.870294e-01,3.597412e-01,10,0.001951,4.499603e-01,0.375332,1.189704e-01,group,baseline,T4a|TmY14|T2a|Tm16|T4b,groups,prespecified_groups,0.009756
9,single__T1__baseline,-2.943943e-01,-7.379929e-01,2.432923e-02,-2.709533e-02,6.672882e-01,3,0.887805,3.719104e-01,0.067833,-3.622274e-01,single,baseline,T1,screen,exploratory_34_screen,0.986341
10,single__T2__baseline,1.170653e-03,-2.614709e-02,3.210142e-02,-8.203483e-03,4.981455e-02,5,0.476098,1.257776e-01,0.128307,-1.271365e-01,single,baseline,T2,screen,exploratory_34_screen,0.986341
11,single__T2a__baseline,-3.522023e-02,-1.170210e-01,3.892998e-02,6.790363e-03,1.330694e-01,6,0.774634,1.140357e-01,0.029449,-6.466924e-02,single,baseline,T2a,screen,secondary_3,0.774634
12,single__T2a__constant_tonic,-2.946972e-02,-1.109115e-01,4.260353e-02,7.087847e-03,1.313758e-01,6,0.739512,1.130423e-01,0.029449,-5.891873e-02,sensitivity,constant_tonic,T2a,sensitivity,sensitivity,0.987317
13,single__T2a__zero,-3.027464e+00,-5.864787e+00,-8.288166e-01,-1.672529e+00,4.380446e+00,1,0.987317,1.016838e+00,-0.121423,-2.906041e+00,sensitivity,zero,T2a,sensitivity,sensitivity,0.987317
14,single__T3__baseline,-9.952616e-05,-4.205123e-02,5.470998e-02,-5.658525e-03,8.352308e-02,4,0.502439,8.478030e-02,-0.029016,2.891608e-02,single,baseline,T3,screen,exploratory_34_screen,0.986341
15,single__T4a__baseline,5.172520e-02,-9.341165e-02,1.868751e-01,8.584934e-02,2.394808e-01,6,0.253659,2.930976e-01,0.177149,-1.254237e-01,single,baseline,T4a,screen,confirmatory_T4a,0.253659
16,single__T4a__constant_tonic,5.432499e-02,-9.245053e-02,1.905573e-01,8.982091e-02,2.409729e-01,6,0.249756,2.948046e-01,0.177149,-1.228239e-01,sensitivity,constant_tonic,T4a,sensitivity,sensitivity,0.624390
17,single__T4a__zero,4.426202e-02,-1.517688e-01,2.246771e-01,7.330721e-02,3.206012e-01,7,0.333659,3.622707e-01,0.193522,-1.492604e-01,sensitivity,zero,T4a,sensitivity,sensitivity,0.629268
18,single__T4b__baseline,2.620879e-01,1.558132e-01,3.665609e-01,2.842981e-01,1.807230e-01,10,0.001951,3.079083e-01,0.106334,1.557535e-01,single,baseline,T4b,screen,exploratory_34_screen,0.029268
19,single__T4b__constant_tonic,2.592955e-01,1.555195e-01,3.618506e-01,2.834578e-01,1.762032e-01,10,0.001951,3.087535e-01,0.106334,1.529612e-01,sensitivity,constant_tonic,T4b,sensitivity,sensitivity,0.019512
20,single__T4b__zero,-2.951825e-01,-7.554522e-01,1.119987e-01,9.407919e-03,7.514794e-01,5,0.878049,4.728672e-01,0.040884,-3.360668e-01,sensitivity,zero,T4b,sensitivity,sensitivity,0.987317
21,single__T4c__baseline,-1.290953e-01,-4.708532e-01,1.309169e-01,-3.108046e-02,5.222369e-01,5,0.720976,2.918010e-01,0.179470,-3.085656e-01,single,baseline,T4c,screen,exploratory_34_screen,0.986341
22,single__T4d__baseline,-1.731106e-01,-6.835951e-01,1.558449e-01,1.001475e-01,7.707684e-01,6,0.609756,4.131287e-01,0.146967,-3.200775e-01,single,baseline,T4d,screen,exploratory_34_screen,0.986341
23,single__T5a__baseline,4.120990e-02,-4.221134e-02,1.447508e-01,9.703960e-04,1.602463e-01,6,0.261463,6.785401e-02,0.025651,1.555903e-02,single,baseline,T5a,screen,exploratory_34_screen,0.871545
24,single__T5b__baseline,2.576693e-02,-4.735582e-03,5.877832e-02,3.569899e-03,5.467420e-02,6,0.083902,4.062667e-02,0.018940,6.826468e-03,single,baseline,T5b,screen,exploratory_34_screen,0.393031
25,single__T5c__baseline,-4.440880e-02,-1.169549e-01,2.677271e-02,-3.186659e-02,1.219779e-01,4,0.859512,1.452157e-01,0.077632,-1.220404e-01,single,baseline,T5c,screen,exploratory_34_screen,0.986341
26,single__T5d__baseline,-9.425214e-03,-6.177385e-02,4.117223e-02,-1.155033e-02,8.618420e-02,3,0.707317,6.565436e-02,0.011414,-2.083900e-02,single,baseline,T5d,screen,exploratory_34_screen,0.986341
27,single__Tm16__baseline,6.887865e-02,2.410418e-02,1.169376e-01,5.190950e-02,7.909277e-02,7,0.012683,4.996566e-02,0.024884,4.399481e-02,single,baseline,Tm16,screen,secondary_3,0.038049
28,single__Tm16__constant_tonic,6.893086e-02,2.415952e-02,1.172428e-01,5.170090e-02,7.949762e-02,7,0.012683,4.992451e-02,0.024884,4.404702e-02,sensitivity,constant_tonic,Tm16,sensitivity,sensitivity,0.042276
29,single__Tm16__zero,1.167048e-01,4.639748e-02,1.890982e-01,9.564206e-02,1.218663e-01,8,0.008780,4.860803e-02,0.098243,1.846158e-02,sensitivity,zero,Tm16,sensitivity,sensitivity,0.042276
30,single__Tm1__baseline,4.189077e-02,1.675440e-03,8.542239e-02,1.806357e-02,7.120435e-02,8,0.041951,6.722776e-02,-0.013643,5.553387e-02,single,baseline,Tm1,screen,exploratory_34_screen,0.314634
31,single__Tm20__baseline,-1.343912e-01,-3.177693e-01,-5.112412e-04,-6.151960e-02,2.761089e-01,4,0.945366,1.137331e-01,0.023639,-1.580306e-01,single,baseline,Tm20,screen,exploratory_34_screen,0.986341
32,single__Tm28__baseline,-8.131864e-02,-2.466618e-01,3.954648e-02,1.913912e-03,2.484761e-01,5,0.775610,1.648646e-01,0.030978,-1.122964e-01,single,baseline,Tm28,screen,exploratory_34_screen,0.986341
33,single__Tm2__baseline,-1.216027e-01,-4.445737e-01,6.757875e-02,-5.349304e-03,4.881458e-01,4,0.573659,1.337419e-01,0.017537,-1.391393e-01,single,baseline,Tm2,screen,exploratory_34_screen,0.986341
34,single__Tm30__baseline,-1.049869e-04,-2.767007e-04,4.410013e-05,-2.028753e-05,2.749340e-04,3,0.866341,2.304647e-04,-0.000128,2.306069e-05,single,baseline,Tm30,screen,exploratory_34_screen,0.986341
35,single__Tm3__baseline,-3.437912e-03,-1.071558e-01,9.159523e-02,8.334071e-03,1.685760e-01,5,0.537561,2.152081e-01,0.001737,-5.175326e-03,single,baseline,Tm3,screen,exploratory_34_screen,0.986341
36,single__Tm4__baseline,-2.508534e-02,-4.594032e-02,-6.330373e-03,-1.704403e-02,3.398487e-02,2,0.976585,4.734220e-02,0.034631,-5.971627e-02,single,baseline,Tm4,screen,exploratory_34_screen,0.986341
37,single__Tm5Y__baseline,8.536539e-04,-4.613185e-02,4.193041e-02,3.115655e-03,7.544934e-02,5,0.488780,1.453867e-01,0.005803,-4.949732e-03,single,baseline,Tm5Y,screen,exploratory_34_screen,0.986341
38,single__Tm5a__baseline,-6.544337e-02,-1.772845e-01,5.373894e-02,-2.053011e-02,1.937692e-01,2,0.861463,2.248154e-01,0.062886,-1.283294e-01,single,baseline,Tm5a,screen,exploratory_34_screen,0.986341
39,single__Tm5b__baseline,-1.331571e-01,-2.633586e-01,-1.032644e-03,-8.393048e-02,2.244020e-01,3,0.958049,1.669027e-01,0.156472,-2.896291e-01,single,baseline,Tm5b,screen,exploratory_34_screen,0.986341
40,single__Tm5c__baseline,-7.688511e-01,-1.486581e+00,-2.189896e-01,-5.010339e-01,1.088713e+00,3,0.986341,3.600368e-01,0.106523,-8.753745e-01,single,baseline,Tm5c,screen,exploratory_34_screen,0.986341
41,single__Tm9__baseline,-4.532532e-02,-1.276732e-01,2.568322e-02,-5.839970e-03,1.314600e-01,4,0.827317,7.597682e-02,0.025975,-7.129997e-02,single,baseline,Tm9,screen,exploratory_34_screen,0.986341
42,single__TmY10__baseline,5.468253e-02,-6.657233e-03,1.252169e-01,1.293186e-02,1.132976e-01,7,0.085854,8.481179e-02,-0.012657,6.733996e-02,single,baseline,TmY10,screen,exploratory_34_screen,0.393031
43,single__TmY13__baseline,-7.061181e-02,-1.736668e-01,3.727382e-03,-1.040845e-02,1.558709e-01,3,0.893659,8.450841e-02,0.021229,-9.184076e-02,single,baseline,TmY13,screen,exploratory_34_screen,0.986341
44,single__TmY14__baseline,3.797460e-02,-1.197504e-01,1.785945e-01,1.089939e-02,2.526378e-01,7,0.322927,1.177102e-01,0.083179,-4.520416e-02,single,baseline,TmY14,screen,secondary_3,0.484390
45,single__TmY14__constant_tonic,2.915308e-02,-1.242847e-01,1.580567e-01,1.027627e-02,2.434507e-01,7,0.377561,1.206823e-01,0.083179,-5.402568e-02,sensitivity,constant_tonic,TmY14,sensitivity,sensitivity,0.629268
46,single__TmY14__zero,-9.924848e-01,-2.398007e+00,-1.632394e-02,-1.792826e-02,2.099005e+00,4,0.925854,4.463523e-01,0.075310,-1.067795e+00,sensitivity,zero,TmY14,sensitivity,sensitivity,0.987317
47,single__TmY15__baseline,3.861331e-02,1.209403e-02,6.510348e-02,4.768082e-02,4.499259e-02,8,0.014634,7.097978e-02,0.049850,-1.123716e-02,single,baseline,TmY15,screen,exploratory_34_screen,0.146341
48,single__TmY18__baseline,3.145657e-02,-1.972138e-02,7.878146e-02,3.267006e-02,8.421484e-02,8,0.124878,2.719968e-01,0.077160,-4.570382e-02,single,baseline,TmY18,screen,exploratory_34_screen,0.468293
49,single__TmY3__baseline,5.379331e-02,2.608463e-02,8.470377e-02,3.858688e-02,5.038271e-02,10,0.001951,7.301352e-02,0.111252,-5.745892e-02,single,baseline,TmY3,screen,exploratory_34_screen,0.029268
50,single__TmY4__baseline,-1.357354e-02,-6.529393e-02,3.752343e-02,-1.254351e-02,8.748166e-02,4,0.684878,8.017013e-02,0.032020,-4.559305e-02,single,baseline,TmY4,screen,exploratory_34_screen,0.986341
51,single__TmY5a__baseline,-4.099500e-02,-1.989704e-01,9.620544e-02,3.442331e-02,2.540745e-01,6,0.693659,1.954343e-01,0.034357,-7.535205e-02,single,baseline,TmY5a,screen,exploratory_34_screen,0.986341
52,single__TmY9__baseline,7.155020e-03,-2.698593e-03,1.631876e-02,7.751850e-03,1.627025e-02,7,0.091707,3.044865e-02,-0.002513,9.667885e-03,single,baseline,TmY9,screen,exploratory_34_screen,0.393031

data/precomputed/fig06/replacement_bootstrap.csv

,intervention,metric,n_models,mean,median,ci_low,ci_high
0,T4,MIDD_loss,10,-0.819937,0.864619,-3.453122,1.103754
1,T4,propeller_loss,10,0.596824,0.599281,0.520820,0.661208
2,T4,edge_loss,10,0.458687,0.566652,0.100500,0.752396
3,T4,propeller_magnitude_loss,10,0.286890,0.261829,0.216857,0.360765
4,T4,D_primary,10,-1.416760,0.203123,-3.987315,0.479301
5,T4,D_edge,10,-1.278624,0.291629,-3.951124,0.735470
6,T4,D_projected,10,0.255264,0.179512,-0.019905,0.638554
7,T4,MIDD_absolute_loss,10,-1.042770,0.742496,-3.582718,0.790762
8,T4_T5,MIDD_loss,10,-0.147103,1.014150,-2.753953,1.327386
9,T4_T5,propeller_loss,10,0.709927,0.696193,0.649792,0.776163
10,T4_T5,edge_loss,10,0.816967,0.854508,0.596886,1.035659
11,T4_T5,propeller_magnitude_loss,10,0.444166,0.460585,0.342795,0.542837
12,T4_T5,D_primary,10,-0.857030,0.196899,-3.450746,0.616261
13,T4_T5,D_edge,10,-0.964070,0.134982,-3.538832,0.473123
14,T4_T5,D_projected,10,0.021974,0.068554,-0.146255,0.143973
15,T4_T5,MIDD_absolute_loss,10,-0.544858,0.816775,-3.029925,0.814393
16,T4a,MIDD_loss,10,0.424107,0.174111,0.016532,1.049922
17,T4a,propeller_loss,10,0.181795,0.176829,0.156547,0.207859
18,T4a,edge_loss,10,0.450430,0.518126,0.230587,0.662403
19,T4a,propeller_magnitude_loss,10,0.051751,0.030827,0.011005,0.098153
20,T4a,D_primary,10,0.242312,0.006166,-0.178983,0.868450
21,T4a,D_edge,10,-0.026323,-0.236827,-0.559519,0.685460
22,T4a,D_projected,10,0.098914,-0.005867,-0.036604,0.252894
23,T4a,MIDD_absolute_loss,10,0.025919,0.073919,-0.255813,0.274519
24,T4b,MIDD_loss,10,0.261734,-0.019376,-0.735994,1.695205
25,T4b,propeller_loss,10,0.166224,0.202464,0.100516,0.223476
26,T4b,edge_loss,10,0.177969,0.013778,-0.020066,0.398039
27,T4b,propeller_magnitude_loss,10,0.044319,0.054025,-0.008048,0.101765
28,T4b,D_primary,10,0.095510,-0.169917,-0.908685,1.502857
29,T4b,D_edge,10,0.083765,-0.033154,-0.895945,1.435022
30,T4b,D_projected,10,-0.066772,-0.076240,-0.154121,0.023470
31,T4b,MIDD_absolute_loss,10,-0.765922,-0.070437,-1.670958,-0.060932

data/precomputed/fig06/denominator_audit.csv

,intervention,condition,q0,q5,q25,q50,q75,q95,q100,n,excluded
0,T4,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
1,T4,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
2,T4,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
3,T4_T5,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
4,T4_T5,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
5,T4_T5,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
6,T4a,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
7,T4a,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
8,T4a,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
9,T4b,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
10,T4b,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
11,T4b,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
12,all_input,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
13,all_input,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
14,all_input,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
15,sham,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
16,sham,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
17,sham,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0

## 8. Figure generation
The shared plotting source preserves the adopted layout and labels; no manual PDF editing.

In [12]:
fig = render(FIGURE)
display(fig)

Saved S9 inputs 7 checks 2

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [13]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: S9 primary tables: 1 adopted tables: 7

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [14]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/supplementary/fig_S9.ipynb
Model inference: False