# Figure 2

Matched controls use the same full-image/reflection half-difference for canonical and shuffled patterns in all 50 official models. This differs from the canonical Original/Mirror pair.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [name for name in ("numpy", "pandas", "matplotlib")
               if importlib.util.find_spec(name) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = '2'

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/fig01/fig1_midd_per_model.csv,ea64ba2c8b5d1bee163f70c30901bf6063849957771137...,28361
1,data/precomputed/fig02/fig2B_luminance_A_per_m...,5e187be7968ec50782ee7f9a127cf31eeb95a374131474...,77426
2,data/stimuli/fig1B_boxeye_input/midd_source_im...,6ee2369c10677f3f9e8a5ee0d8081a849fb81efd3a6c1b...,39016
3,data/precomputed/fig02/...,9710de8c00486c3893aa07a50b46db579d0a12a3bd7bcf...,8680
4,data/precomputed/fig02/...,3fd2de4b6f4c9a0d5f0ca278d24304733c128049edf5a1...,1522
5,data/precomputed/fig02/official50...,6812c7d5121a127dd5b732eec9daaec2a37374bc8ae1c9...,23822
6,data/precomputed/fig02/official50...,0d10976a4a7fcecc8952348a688b388c75fe3ab387b0c5...,1693

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 6

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

                                               check  passed
0  A/S identity: data/precomputed/fig01/fig1_midd...    True

## 5. Primary analysis
For Fig3/S7, affine fits and both held-out splits are recomputed from saved A3/A4. Native and multi-field definitions remain separate.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig01/fig1_midd_per_model.csv

,model_id,group,T_original,T_mirror,A,abs_A,S,abs_S,M,actual_reversal,T_negative
0,flow/0000/000,3MIDD_048,-0.001514,0.002210,-0.001862,0.001862,0.000348,0.000348,0.001514,True,-0.007603
1,flow/0000/001,3MIDD_048,-0.002747,0.000110,-0.001428,0.001428,-0.001318,0.001318,0.000110,True,-0.006701
2,flow/0000/002,3MIDD_048,0.000588,0.023965,-0.011689,0.011689,0.012277,0.012277,-0.000588,False,-0.008894
3,flow/0000/003,3MIDD_048,-0.020133,0.040437,-0.030285,0.030285,0.010152,0.010152,0.020133,True,0.001233
4,flow/0000/004,3MIDD_048,-0.016458,-0.017092,0.000317,0.000317,-0.016775,0.016775,-0.016458,False,-0.016692
5,flow/0000/005,3MIDD_048,-0.016402,-0.000890,-0.007756,0.007756,-0.008646,0.008646,-0.000890,False,-0.020464
6,flow/0000/006,3MIDD_048,-0.013238,0.028473,-0.020855,0.020855,0.007618,0.007618,0.013238,True,0.001450
7,flow/0000/007,3MIDD_048,-0.006693,-0.004285,-0.001204,0.001204,-0.005489,0.005489,-0.004285,False,-0.012261
8,flow/0000/008,3MIDD_048,-0.008909,0.003964,-0.006437,0.006437,-0.002472,0.002472,0.003964,True,0.006007
9,flow/0000/009,3MIDD_048,0.001899,0.018121,-0.008111,0.008111,0.010010,0.010010,-0.001899,False,-0.006446
10,flow/0000/010,3MIDD_048,0.001475,0.000174,0.000650,0.000650,0.000824,0.000824,-0.000174,False,-0.028208
11,flow/0000/011,3MIDD_048,-0.024322,-0.019623,-0.002349,0.002349,-0.021973,0.021973,-0.019623,False,-0.027084
12,flow/0000/012,3MIDD_048,0.005698,0.045626,-0.019964,0.019964,0.025662,0.025662,-0.005698,False,0.007971
13,flow/0000/013,3MIDD_048,-0.009534,0.007469,-0.008501,0.008501,-0.001033,0.001033,0.007469,True,0.001073
14,flow/0000/014,3MIDD_048,-0.001403,0.034734,-0.018068,0.018068,0.016666,0.016666,0.001403,True,-0.010783
15,flow/0000/015,3MIDD_048,-0.006977,0.010960,-0.008969,0.008969,0.001992,0.001992,0.006977,True,0.003051
16,flow/0000/016,3MIDD_048,-0.013195,0.002489,-0.007842,0.007842,-0.005353,0.005353,0.002489,True,-0.031118
17,flow/0000/017,3MIDD_048,-0.039079,0.027331,-0.033205,0.033205,-0.005874,0.005874,0.027331,True,-0.012105
18,flow/0000/018,3MIDD_048,-0.018108,0.005678,-0.011893,0.011893,-0.006215,0.006215,0.005678,True,-0.014659
19,flow/0000/019,3MIDD_048,0.017761,0.044987,-0.013613,0.013613,0.031374,0.031374,-0.017761,False,0.014519

data/precomputed/fig02/fig2B_luminance_A_per_model.csv

,model_id,C,mirror,original,A,abs_A,actual_reversal
0,flow/0000/000,16,0.000393,-0.007925,-0.004159,0.004159,True
1,flow/0000/000,32,0.001477,-0.005716,-0.003596,0.003596,True
2,flow/0000/000,48,0.002210,-0.001514,-0.001862,0.001862,True
3,flow/0000/000,64,0.002353,0.001880,-0.000236,0.000236,False
4,flow/0000/000,80,0.002274,0.004545,0.001135,0.001135,False
5,flow/0000/000,96,0.000841,0.008069,0.003614,0.003614,False
6,flow/0000/000,112,0.000652,0.013490,0.006419,0.006419,False
7,flow/0000/000,128,0.001996,0.016493,0.007249,0.007249,False
8,flow/0000/000,143,0.003758,0.018100,0.007171,0.007171,False
9,flow/0000/000,159,0.005058,0.019854,0.007398,0.007398,False
10,flow/0000/000,175,0.007356,0.020153,0.006398,0.006398,False
11,flow/0000/000,191,0.007309,0.019485,0.006088,0.006088,False
12,flow/0000/000,207,0.008342,0.017992,0.004825,0.004825,False
13,flow/0000/000,223,0.010589,0.015401,0.002406,0.002406,False
14,flow/0000/000,239,0.013123,0.012782,-0.000171,0.000171,False
15,flow/0000/001,16,-0.001002,-0.002676,-0.000837,0.000837,False
16,flow/0000/001,32,-0.000547,-0.002794,-0.001123,0.001123,False
17,flow/0000/001,48,0.000110,-0.002747,-0.001428,0.001428,True
18,flow/0000/001,64,0.000563,-0.002493,-0.001528,0.001528,True
19,flow/0000/001,80,0.000585,-0.001989,-0.001287,0.001287,True

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig02/matched_control_specificity_modelwise.csv

,model_id,group,A,S,M,canonical_abs_A,canonical_abs_A_norm,original_image_reflection_A,negative_reflection_A,mean_random_reflection_abs_A,mean_random_normalized_abs_A,D_canonical_vs_random,D_reflection_matched,D_normalized
0,flow/0000/000,3MIDD_048,-0.001862,0.000348,0.001514,0.001862,0.009811,-0.001129,-0.004856,0.016890,0.082904,-0.015027,-0.015760,-0.073092
1,flow/0000/000,3MIDD_207,0.004825,0.013167,-0.008342,0.004825,0.033447,0.003804,0.007657,0.011317,0.069437,-0.006492,-0.007512,-0.035990
2,flow/0000/000,4MIDD_085_170,0.000724,0.007647,-0.006922,0.000724,0.004940,-0.002237,-0.002025,0.007703,0.045530,-0.006979,-0.005466,-0.040590
3,flow/0000/001,3MIDD_048,-0.001428,-0.001318,0.000110,0.001428,0.009239,-0.001365,-0.003875,0.005610,0.038850,-0.004182,-0.004245,-0.029611
4,flow/0000/001,3MIDD_207,0.008649,0.002362,0.006287,0.008649,0.053990,0.008472,0.003068,0.009948,0.065124,-0.001299,-0.001477,-0.011134
5,flow/0000/001,4MIDD_085_170,0.001099,-0.002203,-0.001104,0.001099,0.006962,0.000385,-0.002212,0.003599,0.024981,-0.002500,-0.003214,-0.018018
6,flow/0000/002,3MIDD_048,-0.011689,0.012277,-0.000588,0.011689,0.098050,-0.011630,-0.014156,0.010369,0.089339,0.001320,0.001261,0.008711
7,flow/0000/002,3MIDD_207,-0.001831,0.023789,-0.021958,0.001831,0.011482,-0.002170,0.003559,0.010202,0.074818,-0.008370,-0.008031,-0.063336
8,flow/0000/002,4MIDD_085_170,0.004159,0.007152,-0.002993,0.004159,0.034038,-0.003178,-0.010449,0.009466,0.068540,-0.005307,-0.006288,-0.034502
9,flow/0000/003,3MIDD_048,-0.030285,0.010152,0.020133,0.030285,0.262899,-0.030787,-0.005580,0.011831,0.086862,0.018454,0.018957,0.176037
10,flow/0000/003,3MIDD_207,0.016339,0.035065,-0.018726,0.016339,0.112074,0.017174,0.020664,0.015283,0.091273,0.001056,0.001891,0.020801
11,flow/0000/003,4MIDD_085_170,0.011651,0.022976,-0.011325,0.011651,0.085324,0.010300,-0.001328,0.011364,0.066526,0.000287,-0.001064,0.018798
12,flow/0000/004,3MIDD_048,0.000317,-0.016775,-0.016458,0.000317,0.001254,0.000079,-0.009725,0.014133,0.053799,-0.013815,-0.014054,-0.052545
13,flow/0000/004,3MIDD_207,0.012545,-0.012279,0.000265,0.012545,0.063492,0.012500,0.003891,0.014525,0.072135,-0.001981,-0.002025,-0.008642
14,flow/0000/004,4MIDD_085_170,-0.000782,-0.016950,-0.016168,0.000782,0.003370,0.000070,-0.025599,0.013541,0.063385,-0.012759,-0.013471,-0.060015
15,flow/0000/005,3MIDD_048,-0.007756,-0.008646,-0.000890,0.007756,0.065963,-0.009125,-0.016058,0.014500,0.088211,-0.006744,-0.005375,-0.022248
16,flow/0000/005,3MIDD_207,0.051553,-0.005572,0.045981,0.051553,0.290323,0.052997,0.006845,0.013287,0.076805,0.038266,0.039711,0.213518
17,flow/0000/005,4MIDD_085_170,-0.003303,-0.000900,0.002403,0.003303,0.023170,0.001193,0.002324,0.014022,0.092239,-0.010719,-0.012829,-0.069069
18,flow/0000/006,3MIDD_048,-0.020855,0.007618,0.013238,0.020855,0.160581,-0.021635,-0.005382,0.009947,0.079754,0.010908,0.011688,0.080827
19,flow/0000/006,3MIDD_207,0.006052,0.015287,-0.009236,0.006052,0.036751,0.005593,0.009665,0.013953,0.086541,-0.007902,-0.008361,-0.049790

data/precomputed/fig02/matched_control_bootstrap_summary.csv

,group,metric,mean,ci_low,ci_high,n_models
0,3MIDD_048,D_canonical_vs_random,-0.003473,-0.009431,0.003662,10
1,3MIDD_048,D_reflection_matched,-0.003265,-0.009456,0.003833,10
2,3MIDD_048,D_normalized,-0.001336,-0.041024,0.048952,10
3,3MIDD_048,canonical_abs_A,0.008979,0.003860,0.015081,10
4,3MIDD_048,mean_random_reflection_abs_A,0.012452,0.010301,0.014496,10
5,3MIDD_207,D_canonical_vs_random,-0.001748,-0.008364,0.008143,10
6,3MIDD_207,D_reflection_matched,-0.001670,-0.008413,0.008699,10
7,3MIDD_207,D_normalized,-0.007924,-0.045112,0.046552,10
8,3MIDD_207,canonical_abs_A,0.010494,0.003534,0.020799,10
9,3MIDD_207,mean_random_reflection_abs_A,0.012243,0.010540,0.013734,10
10,4MIDD_085_170,D_canonical_vs_random,-0.007615,-0.010706,-0.004469,10
11,4MIDD_085_170,D_reflection_matched,-0.008295,-0.011227,-0.005347,10
12,4MIDD_085_170,D_normalized,-0.040011,-0.057464,-0.020275,10
13,4MIDD_085_170,canonical_abs_A,0.003702,0.001336,0.006678,10
14,4MIDD_085_170,mean_random_reflection_abs_A,0.011317,0.009055,0.013245,10

data/precomputed/fig02/official50_shuffle_model_metrics.csv

,model_id,group,canonical_reflection_abs_A,canonical_reflection_abs_A_norm,shuffle_mean_abs_A,shuffle_median_abs_A,difference_mean,difference_median,canonical_rank,canonical_percentile
0,flow/0000/000,3MIDD_048,0.001129,0.005921,0.016890,0.013699,-0.015760,-0.012569,2,0.1
1,flow/0000/000,3MIDD_207,0.003804,0.026482,0.011317,0.010707,-0.007512,-0.006902,2,0.1
2,flow/0000/000,4MIDD_085_170,0.002237,0.014680,0.007703,0.006916,-0.005466,-0.004679,4,0.3
3,flow/0000/001,3MIDD_048,0.001365,0.008860,0.005610,0.004597,-0.004245,-0.003232,4,0.3
4,flow/0000/001,3MIDD_207,0.008472,0.052923,0.009948,0.009221,-0.001477,-0.000749,4,0.3
5,flow/0000/001,4MIDD_085_170,0.000385,0.002440,0.003599,0.002283,-0.003214,-0.001898,4,0.3
6,flow/0000/002,3MIDD_048,0.011630,0.097368,0.010369,0.008548,0.001261,0.003081,7,0.6
7,flow/0000/002,3MIDD_207,0.002170,0.013541,0.010202,0.008948,-0.008031,-0.006778,2,0.1
8,flow/0000/002,4MIDD_085_170,0.003178,0.024694,0.009466,0.009506,-0.006288,-0.006328,3,0.2
9,flow/0000/003,3MIDD_048,0.030787,0.267082,0.011831,0.010455,0.018957,0.020333,10,0.9
10,flow/0000/003,3MIDD_207,0.017174,0.117331,0.015283,0.014025,0.001891,0.003149,7,0.6
11,flow/0000/003,4MIDD_085_170,0.010300,0.075201,0.011364,0.009140,-0.001064,0.001160,7,0.6
12,flow/0000/004,3MIDD_048,0.000079,0.000312,0.014133,0.010652,-0.014054,-0.010573,1,0.0
13,flow/0000/004,3MIDD_207,0.012500,0.063237,0.014525,0.012045,-0.002025,0.000455,6,0.5
14,flow/0000/004,4MIDD_085_170,0.000070,0.000302,0.013541,0.012979,-0.013471,-0.012909,1,0.0
15,flow/0000/005,3MIDD_048,0.009125,0.077788,0.014500,0.017206,-0.005375,-0.008081,5,0.4
16,flow/0000/005,3MIDD_207,0.052997,0.294728,0.013287,0.010307,0.039711,0.042690,11,1.0
17,flow/0000/005,4MIDD_085_170,0.001193,0.008190,0.014022,0.012153,-0.012829,-0.010961,2,0.1
18,flow/0000/006,3MIDD_048,0.021635,0.166304,0.009947,0.009266,0.011688,0.012369,11,1.0
19,flow/0000/006,3MIDD_207,0.005593,0.034598,0.013953,0.009561,-0.008361,-0.003968,4,0.3

data/precomputed/fig02/official50_shuffle_summary.csv

,group,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,canonical_reflection_abs_A,50,0.010622,0.007087,0.007419,0.014431
1,3MIDD_048,shuffle_mean_abs_A,50,0.013307,0.012147,0.011744,0.015031
2,3MIDD_048,difference_mean,50,-0.002685,-0.003728,-0.005633,0.000589
3,3MIDD_048,difference_median,50,-0.001072,-0.003075,-0.004060,0.002438
4,3MIDD_048,canonical_percentile,50,0.390000,0.400000,0.312000,0.468000
5,3MIDD_207,canonical_reflection_abs_A,50,0.009395,0.006050,0.006979,0.012295
6,3MIDD_207,shuffle_mean_abs_A,50,0.012602,0.011247,0.010980,0.014304
7,3MIDD_207,difference_mean,50,-0.003206,-0.003694,-0.005870,-0.000308
8,3MIDD_207,difference_median,50,-0.001762,-0.001721,-0.004551,0.001175
9,3MIDD_207,canonical_percentile,50,0.414000,0.400000,0.334000,0.498000
10,4MIDD_085_170,canonical_reflection_abs_A,50,0.003400,0.002620,0.002584,0.004369
11,4MIDD_085_170,shuffle_mean_abs_A,50,0.011699,0.011433,0.010312,0.013183
12,4MIDD_085_170,difference_mean,50,-0.008299,-0.007550,-0.009766,-0.006922
13,4MIDD_085_170,difference_median,50,-0.007135,-0.006648,-0.008669,-0.005730
14,4MIDD_085_170,canonical_percentile,50,0.176000,0.100000,0.130000,0.228000

## 7. Statistics
Model/seed is the unit. Stored intervals retain the original inference choices. Fig3/S7 additionally replay the exact original bootstrap seed and RNG consumption order; cached null draws are not regenerated or tuned.

In [7]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

data/precomputed/fig02/matched_control_bootstrap_summary.csv

,group,metric,mean,ci_low,ci_high,n_models
0,3MIDD_048,D_canonical_vs_random,-0.003473,-0.009431,0.003662,10
1,3MIDD_048,D_reflection_matched,-0.003265,-0.009456,0.003833,10
2,3MIDD_048,D_normalized,-0.001336,-0.041024,0.048952,10
3,3MIDD_048,canonical_abs_A,0.008979,0.003860,0.015081,10
4,3MIDD_048,mean_random_reflection_abs_A,0.012452,0.010301,0.014496,10
5,3MIDD_207,D_canonical_vs_random,-0.001748,-0.008364,0.008143,10
6,3MIDD_207,D_reflection_matched,-0.001670,-0.008413,0.008699,10
7,3MIDD_207,D_normalized,-0.007924,-0.045112,0.046552,10
8,3MIDD_207,canonical_abs_A,0.010494,0.003534,0.020799,10
9,3MIDD_207,mean_random_reflection_abs_A,0.012243,0.010540,0.013734,10
10,4MIDD_085_170,D_canonical_vs_random,-0.007615,-0.010706,-0.004469,10
11,4MIDD_085_170,D_reflection_matched,-0.008295,-0.011227,-0.005347,10
12,4MIDD_085_170,D_normalized,-0.040011,-0.057464,-0.020275,10
13,4MIDD_085_170,canonical_abs_A,0.003702,0.001336,0.006678,10
14,4MIDD_085_170,mean_random_reflection_abs_A,0.011317,0.009055,0.013245,10

data/precomputed/fig02/official50_shuffle_summary.csv

,group,metric,n_models,mean,median,ci_low,ci_high
0,3MIDD_048,canonical_reflection_abs_A,50,0.010622,0.007087,0.007419,0.014431
1,3MIDD_048,shuffle_mean_abs_A,50,0.013307,0.012147,0.011744,0.015031
2,3MIDD_048,difference_mean,50,-0.002685,-0.003728,-0.005633,0.000589
3,3MIDD_048,difference_median,50,-0.001072,-0.003075,-0.004060,0.002438
4,3MIDD_048,canonical_percentile,50,0.390000,0.400000,0.312000,0.468000
5,3MIDD_207,canonical_reflection_abs_A,50,0.009395,0.006050,0.006979,0.012295
6,3MIDD_207,shuffle_mean_abs_A,50,0.012602,0.011247,0.010980,0.014304
7,3MIDD_207,difference_mean,50,-0.003206,-0.003694,-0.005870,-0.000308
8,3MIDD_207,difference_median,50,-0.001762,-0.001721,-0.004551,0.001175
9,3MIDD_207,canonical_percentile,50,0.414000,0.400000,0.334000,0.498000
10,4MIDD_085_170,canonical_reflection_abs_A,50,0.003400,0.002620,0.002584,0.004369
11,4MIDD_085_170,shuffle_mean_abs_A,50,0.011699,0.011433,0.010312,0.013183
12,4MIDD_085_170,difference_mean,50,-0.008299,-0.007550,-0.009766,-0.006922
13,4MIDD_085_170,difference_median,50,-0.007135,-0.006648,-0.008669,-0.005730
14,4MIDD_085_170,canonical_percentile,50,0.176000,0.100000,0.130000,0.228000

## 8. Figure generation
The shared plotting source preserves the adopted layout and labels; no manual PDF editing.

In [8]:
fig = render(FIGURE)
display(fig)

Saved 2 inputs 4 checks 4

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [9]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: 2 primary tables: 2 adopted tables: 4

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [10]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/fig02/fig_2.ipynb
Model inference: False

## Historical acquisition source (disabled during reproduction)
The cells below document original inference and must not be run during artifact-only figure regeneration. They are preserved for audit.

In [11]:
if False:  # acquisition archive; no new inference
    ## #cell 001
    import os
    import importlib
    import site
    import subprocess
    import sys
    from pathlib import Path
    from typing import List
    
    try:
        import google.colab
        IN_COLAB = True
    except ImportError:
        IN_COLAB = False
    
    if IN_COLAB:
        os.environ["FLYVIS_ROOT_DIR"] = "/content/flyvis_data"
    
        flyvis_checkout = Path("/content/flyvis")
        if not flyvis_checkout.exists():
            subprocess.run(
                ["git", "clone", "--branch", "v1.2.0", "--depth", "1",
                 "--single-branch", "https://github.com/TuragaLab/flyvis.git",
                 str(flyvis_checkout)],
                check=True,
            )
        else:
            if not (flyvis_checkout / "pyproject.toml").is_file():
                raise RuntimeError("/content/flyvis exists but is not a FlyVis checkout.")
            head = subprocess.check_output(
                ["git", "-C", str(flyvis_checkout), "rev-parse", "HEAD"], text=True
            ).strip()
            release = subprocess.check_output(
                ["git", "-C", str(flyvis_checkout), "rev-parse", "v1.2.0^{commit}"], text=True
            ).strip()
            if head != release:
                raise RuntimeError("Existing /content/flyvis is not at v1.2.0. Start a fresh Colab runtime.")
            print("Reusing existing FlyVis v1.2.0 checkout.")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-e", ".[examples]"],
            cwd=flyvis_checkout,
            check=True,
        )
    
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install",
             "flyvis-midd[figures,notebooks] @ git+https://github.com/poxsalop5029/flyvis-midd.git"],
            capture_output=True,
            text=True,
        )
        if result.returncode:
            raise RuntimeError((result.stderr or result.stdout)[-5000:])
        print("Installed flyvis-midd from the public GitHub repository.")
        REPO_ROOT = Path("/content")
    
        # Editable installs made by pip must also be visible to this running kernel.
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
        # Official examples run inside the checkout; make the same source visible
        # without changing where this notebook saves its figures and data.
        checkout_path = str(flyvis_checkout)
        if checkout_path not in sys.path:
            sys.path.insert(0, checkout_path)
        importlib.invalidate_caches()
        # A previous import from /content can cache the checkout directory as a
        # namespace package before the editable installation becomes visible.
        cached_flyvis = sys.modules.get("flyvis")
        if cached_flyvis is not None and getattr(cached_flyvis, "__file__", None) is None:
            for module_name in list(sys.modules):
                if module_name == "flyvis" or module_name.startswith("flyvis."):
                    del sys.modules[module_name]
    else:
        REPO_ROOT = next(
            path for path in (Path.cwd(), *Path.cwd().parents)
            if (path / "pyproject.toml").is_file()
        )
        sys.path.insert(0, str(REPO_ROOT / "src"))
    
    import flyvis
    model_ids = [f"flow/0000/{i:03d}" for i in range(50)]
    if not all((flyvis.results_dir / name).is_dir() for name in model_ids):
        print("Downloading FlyVis pretrained models...")
        subprocess.run(["flyvis", "download-pretrained"], check=True)
    if not all((flyvis.results_dir / name).is_dir() for name in model_ids):
        raise RuntimeError(f"The 50 pretrained models are not available under {flyvis.results_dir}.")
    
    print("FlyVis:", flyvis.__file__)
    print("FlyVis version:", flyvis.__version__)
    print("FlyVis data root:", flyvis.root_dir)
    print("FlyVis results:", flyvis.results_dir)
    print("Pretrained models: 50/50")

In [12]:
if False:  # acquisition archive; no new inference
    ## #cell 002
    # Fig. 2A — 3MIDD luminance conditions
    # Original stimuli only; Original/Mirror comparison is shown in Fig. 2C.
    
    import numpy as np
    import matplotlib.pyplot as plt
    
    from flyvis_midd import build_3midd_sequences, render_sector_image
    
    LUMINANCE_LEVELS = [
        16, 32, 48, 64, 80,
        96, 112, 128, 143, 159,
        175, 191, 207, 223, 239,
    ]
    assert len(LUMINANCE_LEVELS) == 15
    
    images = [
        render_sector_image(
            build_3midd_sequences(c)["original"],
            image_size=382,
            inner_diameter=55,
            outer_diameter=382,
            phase_deg=0.0,
        )[0]
        for c in LUMINANCE_LEVELS
    ]
    images = np.stack(images)
    assert images.shape == (15, 382, 382)
    assert np.isfinite(images).all()
    
    fig, axes = plt.subplots(3, 5, figsize=(8.0, 5.0), constrained_layout=True)
    for ax, image, c in zip(axes.flat, images, LUMINANCE_LEVELS):
        ax.imshow(image, cmap="gray", vmin=0, vmax=255)
        suffix = "\n(Fig. 1)" if c in (48, 207) else ""
        ax.set_title(f"C = {c}{suffix}", fontsize=9)
        ax.axis("off")
    
    fig.suptitle(r"3MIDD luminance sweep: $[0,\ C,\ 255]$", fontsize=11)
    plt.show()
    
    print("Luminance levels:", LUMINANCE_LEVELS)
    print("Number of conditions:", len(images))
    print("Fixed Fig. 1 conditions:", [c for c in LUMINANCE_LEVELS if c in (48, 207)])

In [13]:
if False:  # acquisition archive; no new inference
    ## #cell 003
    # Re-infer the 50 official networks × 15 luminance levels × Original/Mirror.
    # Uses the same 50-frame static input, BoxEye, fade-in, stable window, and CW-positive metric as Appendix 01.
    
    import gc
    from pathlib import Path
    import numpy as np
    import pandas as pd
    import torch
    import flyvis
    from flyvis.datasets.rendering import BoxEye
    from flyvis_midd import build_3midd_sequences, render_sector_image
    from flyvis_midd.flow import run_flow_inference
    from flyvis_midd.evaluation import CANONICAL_MIDD, analyze_midd_flow, aggregate_midd_metrics
    CONFIG = CANONICAL_MIDD
    
    REPO_ROOT = Path(REPO_ROOT) if "REPO_ROOT" in globals() else next(
        p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents, Path("/content/flyvis-midd"), Path("/content"))
        if (p / "pyproject.toml").is_file() and (p / "src" / "flyvis_midd").is_dir()
    )
    DEVICE = torch.device("cpu")
    LEVELS = [16, 32, 48, 64, 80, 96, 112, 128, 143, 159, 175, 191, 207, 223, 239]
    VARIANTS = ("original", "mirror")
    MODEL_IDS = [f"flow/0000/{i:03d}" for i in range(50)]
    N_FRAMES, DT, FADE = CONFIG.n_frames, CONFIG.dt, CONFIG.fade_seconds
    
    output_dir = REPO_ROOT / "data/precomputed/fig02"
    output_dir.mkdir(parents=True, exist_ok=True)
    raw_path = output_dir / "fig2B_luminance_tangent_per_model_condition.csv"
    summary_path = output_dir / "fig2B_luminance_A_per_model.csv"
    model_paths = {name: flyvis.results_dir / name for name in MODEL_IDS}
    missing = [str(path) for path in model_paths.values() if not path.is_dir()]
    if missing:
        raise FileNotFoundError(
            f"Missing {len(missing)} pretrained models. Run the FlyVis setup/download cell first; "
            f"examples: {missing[:3]}"
        )
    
    eye = BoxEye(extent=CONFIG.eye_extent, kernel_size=CONFIG.eye_kernel_size)
    centers_yx = eye.receptor_centers.detach().cpu().numpy()
    inputs = {}
    for c in LEVELS:
        sequences = build_3midd_sequences(c)
        for variant in VARIANTS:
            image, _ = render_sector_image(
                sequences[variant], image_size=382, inner_diameter=55,
                outer_diameter=382, phase_deg=0.0,
            )
            movie = np.repeat((image.astype(np.float32) / 255)[None, None], N_FRAMES, axis=1)
            inputs[(c, variant)] = eye(torch.as_tensor(movie, dtype=torch.float32)).cpu()
    assert all(tuple(x.shape) == (1, N_FRAMES, 1, 721) for x in inputs.values())
    
    columns = ["model_id", "C", "variant", "T_cw_positive", "mean_flow_magnitude"]
    lum_raw = pd.read_csv(raw_path) if raw_path.is_file() else pd.DataFrame(columns=columns)
    if len(lum_raw):
        lum_raw["C"] = lum_raw["C"].astype(int)
    done = set(map(tuple, lum_raw[["model_id", "C", "variant"]].itertuples(index=False, name=None)))
    
    for model_number, model_id in enumerate(MODEL_IDS, 1):
        pending = [(c, v) for c in LEVELS for v in VARIANTS if (model_id, c, v) not in done]
        if not pending:
            print(f"[{model_number:02d}/50] {model_id}: complete")
            continue
        view = flyvis.NetworkView(model_paths[model_id])
        network = view.init_network().to(DEVICE).eval()
        decoder = view.init_decoder()["flow"].to(DEVICE).eval()
        for c, variant in pending:
            result = run_flow_inference(
                inputs[(c, variant)], network, decoder, dt=DT, fade=FADE, device=DEVICE,
            )
            flow = result["flow"][0].numpy()
            assert flow.shape == (N_FRAMES, 2, 721) and np.isfinite(flow).all()
            metric = analyze_midd_flow(result["flow"], centers_yx, config=CONFIG)
            lum_raw.loc[len(lum_raw)] = [model_id, c, variant,
                                         metric["mean_signed_tangent"], metric["mean_flow_magnitude"]]
            done.add((model_id, c, variant))
            print(f"[{model_number:02d}/50] C={c:03d} {variant}")
        temp_path = raw_path.with_suffix(".tmp")
        lum_raw.sort_values(["model_id", "C", "variant"]).to_csv(temp_path, index=False)
        temp_path.replace(raw_path)
        del decoder, network, view
        gc.collect()
    
    assert len(lum_raw) == 1500 and not lum_raw.duplicated(["model_id", "C", "variant"]).any()
    assert lum_raw["model_id"].nunique() == 50
    lum_a = lum_raw.pivot(index=["model_id", "C"], columns="variant", values="T_cw_positive").reset_index()
    pair_metrics = aggregate_midd_metrics({"original": lum_a["original"], "mirror": lum_a["mirror"]})
    for key in ("A", "abs_A", "actual_reversal"):
        lum_a[key] = pair_metrics[key]
    lum_a.sort_values(["model_id", "C"]).to_csv(summary_path, index=False)
    print(f"Inference complete: {len(lum_raw)}/1500; saved {raw_path.name} and {summary_path.name}")

In [14]:
if False:  # acquisition archive; no new inference
    ## #cell 004
    # Fig. 2B — 3MIDD luminance dose-response
    
    from pathlib import Path
    import pandas as pd
    import matplotlib.pyplot as plt
    
    repo_root = Path(REPO_ROOT)
    lum_a = pd.read_csv(
        repo_root / "data/precomputed/fig02/fig2B_luminance_A_per_model.csv"
    )
    
    levels = [16, 32, 48, 64, 80, 96, 112, 128, 143, 159, 175, 191, 207, 223, 239]
    
    assert len(lum_a) == 50 * len(levels)
    assert lum_a["model_id"].nunique() == 50
    assert sorted(lum_a["C"].unique()) == levels
    assert (
        lum_a["A"] - (lum_a["original"] - lum_a["mirror"]) / 2
    ).abs().max() < 1e-10
    
    summary = lum_a.groupby("C")["A"].agg(["mean", "sem"]).reindex(levels)
    
    fig, ax = plt.subplots(figsize=(4.6, 3.6))
    
    for _, q in lum_a.groupby("model_id"):
        q = q.sort_values("C")
        ax.plot(q["C"], q["A"], color="0.55", alpha=0.22, linewidth=0.8)
    
    ax.fill_between(
        levels,
        summary["mean"] - summary["sem"],
        summary["mean"] + summary["sem"],
        color="black",
        alpha=0.15,
    )
    ax.plot(
        levels,
        summary["mean"],
        "-o",
        color="black",
        linewidth=2,
        markersize=4,
        label="50-model mean",
    )
    
    ax.axhline(0, color="0.4", linewidth=0.8)
    for c in (48, 207):
        ax.axvline(c, color="0.45", linestyle="--", linewidth=0.9)
    
    ax.set_xlabel("3MIDD middle luminance, C")
    ax.set_ylabel(r"$A=(T_O-T_M)/2$  (CW positive)")
    ax.set_xticks([16, 48, 80, 112, 143, 175, 207, 239])
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(frameon=False, fontsize=8)
    
    fig.tight_layout()
    plt.show()
    
    print("Models:", lum_a["model_id"].nunique())
    print("Luminance levels:", lum_a["C"].nunique())
    for c in (48, 207):
        q = lum_a[lum_a["C"] == c]
        print(f"C={c:3d}: mean A={q['A'].mean():+.6f}, SEM={q['A'].sem():.6f}")

In [15]:
if False:  # acquisition archive; no new inference
    ## #cell 005
    # Fig. 2C — Original / Mirror decoded rotation at the two fixed luminance levels
    
    import numpy as np
    import matplotlib.pyplot as plt
    
    fixed_conditions = [48, 207]
    paired = lum_a[lum_a["C"].isin(fixed_conditions)].copy()
    paired["actual_reversal"] = aggregate_midd_metrics({"original": paired["original"], "mirror": paired["mirror"]})["actual_reversal"]
    assert paired.groupby("C")["model_id"].nunique().eq(50).all()
    
    limit = 1.05 * np.abs(paired[["original", "mirror"]].to_numpy()).max()
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.4), sharex=True, sharey=True)
    for ax, c in zip(axes, fixed_conditions):
        q = paired[paired["C"] == c]
        reversal = q["actual_reversal"]
        ax.scatter(q.loc[~reversal, "original"], q.loc[~reversal, "mirror"],
                   color="0.65", s=28, alpha=0.8, label="Same sign")
        ax.scatter(q.loc[reversal, "original"], q.loc[reversal, "mirror"],
                   color="tab:blue", s=30, alpha=0.9, label="Actual reversal")
        ax.axhline(0, color="0.5", linewidth=0.8)
        ax.axvline(0, color="0.5", linewidth=0.8)
        ax.plot([-limit, limit], [-limit, limit], "--", color="0.8", linewidth=0.8)
        ax.set(xlim=(-limit, limit), ylim=(-limit, limit), aspect="equal", title=f"3MIDD  C = {c}")
        ax.set_xlabel(r"$T_{\mathrm{Original}}$ (CW positive)")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[0].set_ylabel(r"$T_{\mathrm{Mirror}}$ (CW positive)")
    axes[1].legend(frameon=False, fontsize=8, loc="best")
    fig.tight_layout()
    plt.show()
    
    for c in fixed_conditions:
        q = paired[paired["C"] == c]
        n_reversal = int(q["actual_reversal"].sum())
        print(f"C={c}: Actual reversal = {n_reversal}/{len(q)}")

In [16]:
if False:  # acquisition archive; no new inference
    ## #cell 006
    # Fig. 2D — 4MIDD response across the official-50 ensemble
    # Same cohort / BoxEye / timing / CW-positive metric as Fig. 2B–C.
    # Fixed condition: 4MIDD C1=85, C2=170.
    #
    # Core operations are reused from flyvis_midd:
    #   build_4midd_sequences
    #   render_sector_image
    #   run_flow_inference
    #   analyze_midd_flow / aggregate_midd_metrics
    
    import gc
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import torch
    import flyvis
    
    from flyvis_midd import build_4midd_sequences, render_sector_image
    from flyvis_midd.flow import run_flow_inference
    from flyvis_midd.evaluation import CANONICAL_MIDD, analyze_midd_flow, aggregate_midd_metrics
    CONFIG = CANONICAL_MIDD
    
    
    # ---------------------------------------------------------------------
    # 1. Fixed 4MIDD condition used in Appendix 01 / official-50 analysis
    # ---------------------------------------------------------------------
    
    C1, C2 = 85, 170
    
    from pathlib import Path
    from flyvis.datasets.rendering import BoxEye
    
    # Keep this cell runnable after a kernel restart, using the same settings as Fig. 2B.
    DEVICE = torch.device("cpu")
    MODEL_IDS = [f"flow/0000/{i:03d}" for i in range(50)]
    N_FRAMES, DT, FADE = CONFIG.n_frames, CONFIG.dt, CONFIG.fade_seconds
    REPO_ROOT = Path(REPO_ROOT) if "REPO_ROOT" in globals() else next(
        p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents, Path("/content/flyvis-midd"), Path("/content"))
        if (p / "pyproject.toml").is_file() and (p / "src" / "flyvis_midd").is_dir()
    )
    output_dir = REPO_ROOT / "data/precomputed/fig02"
    output_dir.mkdir(parents=True, exist_ok=True)
    model_paths = {name: flyvis.results_dir / name for name in MODEL_IDS}
    missing = [str(path) for path in model_paths.values() if not path.is_dir()]
    if missing:
        raise FileNotFoundError(
            f"Missing {len(missing)} pretrained models. Run the FlyVis setup/download cell first; "
            f"examples: {missing[:3]}"
        )
    eye = BoxEye(extent=CONFIG.eye_extent, kernel_size=CONFIG.eye_kernel_size)
    centers_yx = eye.receptor_centers.detach().cpu().numpy()
    VARIANTS_4MIDD = ("original", "mirror")
    
    # Resolve the paths explicitly so this cell also works when run on its own.
    REPO_ROOT = Path(REPO_ROOT) if "REPO_ROOT" in globals() else next(
        p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents, Path("/content/flyvis-midd"), Path("/content"))
        if (p / "pyproject.toml").is_file() and (p / "src" / "flyvis_midd").is_dir()
    )
    output_dir = REPO_ROOT / "data/precomputed/fig02"
    output_dir.mkdir(parents=True, exist_ok=True)
    raw_path_4 = output_dir / "fig2D_4MIDD_tangent_per_model_condition.csv"
    summary_path_4 = output_dir / "fig2D_4MIDD_A_per_model.csv"
    
    
    # ---------------------------------------------------------------------
    # 2. Build Original / Mirror with the existing flyvis_midd API
    # ---------------------------------------------------------------------
    
    sequences_4 = build_4midd_sequences(C1, C2)
    
    inputs_4 = {}
    
    for variant in VARIANTS_4MIDD:
        image, _ = render_sector_image(
            sequences_4[variant],
            image_size=382,
            inner_diameter=55,
            outer_diameter=382,
            phase_deg=0.0,
        )
    
        movie = np.repeat(
            (image.astype(np.float32) / 255.0)[None, None],
            N_FRAMES,
            axis=1,
        )
    
        inputs_4[variant] = eye(
            torch.as_tensor(movie, dtype=torch.float32)
        ).cpu()
    
    assert all(
        tuple(x.shape) == (1, N_FRAMES, 1, 721)
        for x in inputs_4.values()
    )
    
    
    # ---------------------------------------------------------------------
    # 3. Official-50 inference
    # ---------------------------------------------------------------------
    
    columns = [
        "model_id",
        "variant",
        "T_cw_positive",
        "mean_flow_magnitude",
    ]
    
    four_raw = (
        pd.read_csv(raw_path_4)
        if raw_path_4.is_file()
        else pd.DataFrame(columns=columns)
    )
    
    done = set(
        map(
            tuple,
            four_raw[["model_id", "variant"]]
            .itertuples(index=False, name=None),
        )
    )
    
    
    for model_number, model_id in enumerate(MODEL_IDS, 1):
    
        pending = [
            variant
            for variant in VARIANTS_4MIDD
            if (model_id, variant) not in done
        ]
    
        if not pending:
            print(f"[{model_number:02d}/50] {model_id}: complete")
            continue
    
        view = flyvis.NetworkView(model_paths[model_id])
        network = view.init_network().to(DEVICE).eval()
        decoder = view.init_decoder()["flow"].to(DEVICE).eval()
    
        for variant in pending:
    
            result = run_flow_inference(
                inputs_4[variant],
                network,
                decoder,
                dt=DT,
                fade=FADE,
                device=DEVICE,
            )
    
            flow = result["flow"][0].numpy()
    
            assert flow.shape == (N_FRAMES, 2, 721)
            assert np.isfinite(flow).all()
    
            metric = analyze_midd_flow(result["flow"], centers_yx, config=CONFIG)
    
            four_raw.loc[len(four_raw)] = [
                model_id,
                variant,
                metric["mean_signed_tangent"],
                metric["mean_flow_magnitude"],
            ]
    
            done.add((model_id, variant))
    
            print(
                f"[{model_number:02d}/50] "
                f"4MIDD {C1}/{C2} {variant}"
            )
    
        temp_path = raw_path_4.with_suffix(".tmp")
    
        four_raw.sort_values(
            ["model_id", "variant"]
        ).to_csv(temp_path, index=False)
    
        temp_path.replace(raw_path_4)
    
        del decoder, network, view
        gc.collect()
    
    
    # ---------------------------------------------------------------------
    # 4. Model-wise Original / Mirror summary
    # ---------------------------------------------------------------------
    
    assert len(four_raw) == 50 * 2
    assert four_raw["model_id"].nunique() == 50
    assert not four_raw.duplicated(["model_id", "variant"]).any()
    
    four_a = (
        four_raw
        .pivot(
            index="model_id",
            columns="variant",
            values="T_cw_positive",
        )
        .reset_index()
    )
    
    pair_metrics = aggregate_midd_metrics({"original": four_a["original"], "mirror": four_a["mirror"]})
    for key in ("A", "abs_A", "actual_reversal"):
        four_a[key] = pair_metrics[key]
    
    four_a.sort_values("model_id").to_csv(
        summary_path_4,
        index=False,
    )
    
    
    # ---------------------------------------------------------------------
    # 5. Fig. 2D
    # ---------------------------------------------------------------------
    
    reversal = four_a["actual_reversal"]
    
    limit = (
        1.05
        * np.abs(
            four_a[["original", "mirror"]].to_numpy()
        ).max()
    )
    
    fig, ax = plt.subplots(figsize=(3.8, 3.6))
    
    ax.scatter(
        four_a.loc[~reversal, "original"],
        four_a.loc[~reversal, "mirror"],
        color="0.65",
        s=28,
        alpha=0.8,
        label="Same sign",
    )
    
    ax.scatter(
        four_a.loc[reversal, "original"],
        four_a.loc[reversal, "mirror"],
        color="tab:blue",
        s=30,
        alpha=0.9,
        label="Actual reversal",
    )
    
    ax.axhline(0, color="0.5", linewidth=0.8)
    ax.axvline(0, color="0.5", linewidth=0.8)
    
    # A = 0 line: Original = Mirror
    ax.plot(
        [-limit, limit],
        [-limit, limit],
        "--",
        color="0.8",
        linewidth=0.8,
    )
    
    ax.set(
        xlim=(-limit, limit),
        ylim=(-limit, limit),
        aspect="equal",
        title="4MIDD  C1 = 85, C2 = 170",
    )
    
    ax.set_xlabel(
        r"$T_{\mathrm{Original}}$ (CW positive)"
    )
    ax.set_ylabel(
        r"$T_{\mathrm{Mirror}}$ (CW positive)"
    )
    
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    
    ax.legend(
        frameon=False,
        fontsize=8,
        loc="best",
    )
    
    fig.tight_layout()
    plt.show()
    
    
    # ---------------------------------------------------------------------
    # 6. Numerical QA against Appendix 01
    # ---------------------------------------------------------------------
    
    print("Models:", four_a["model_id"].nunique())
    print(f"Mean A: {four_a['A'].mean():+.8f}")
    print(f"SEM A : {four_a['A'].sem():.8f}")
    print(
        "Actual reversal:",
        f"{int(four_a['actual_reversal'].sum())}/50",
    )

In [17]:
if False:  # acquisition archive; no new inference
    ## #cell 007
    # Fig. 2E — Matched negative-control responses across the official-50 ensemble
    #
    # New matched control inference:
    #   3MIDD C=48 negative
    #   3MIDD C=207 negative
    #   4MIDD C1=85, C2=170 negative
    #
    # Same official-50 cohort, BoxEye, timing, stable window,
    # and CW-positive metric as Fig. 2B–D.
    #
    # NOTE:
    # The legacy Experiment07 negative-control analysis is NOT reused here
    # because it used a different analysis contract / model cohort.
    
    import gc
    from pathlib import Path
    
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import torch
    import flyvis
    
    from flyvis.datasets.rendering import BoxEye
    from flyvis_midd import (
        build_3midd_sequences,
        build_4midd_sequences,
        render_sector_image,
    )
    from flyvis_midd.flow import run_flow_inference
    from flyvis_midd.evaluation import CANONICAL_MIDD, analyze_midd_flow, aggregate_midd_metrics
    CONFIG = CANONICAL_MIDD
    
    
    # ---------------------------------------------------------------------
    # 1. Same inference contract as Fig. 2B–D
    # ---------------------------------------------------------------------
    
    DEVICE = torch.device("cpu")
    
    MODEL_IDS = [
        f"flow/0000/{i:03d}"
        for i in range(50)
    ]
    
    N_FRAMES = CONFIG.n_frames
    DT = CONFIG.dt
    FADE = CONFIG.fade_seconds
    
    REPO_ROOT = (
        Path(REPO_ROOT)
        if "REPO_ROOT" in globals()
        else next(
            p
            for p in (
                Path.cwd().resolve(),
                *Path.cwd().resolve().parents,
                Path("/content/flyvis-midd"),
                Path("/content"),
            )
            if (
                (p / "pyproject.toml").is_file()
                and (p / "src" / "flyvis_midd").is_dir()
            )
        )
    )
    
    output_dir = REPO_ROOT / "data/precomputed/fig02"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    negative_path = (
        output_dir
        / "fig2E_negative_control_per_model.csv"
    )
    
    model_paths = {
        model_id: flyvis.results_dir / model_id
        for model_id in MODEL_IDS
    }
    
    missing = [
        str(path)
        for path in model_paths.values()
        if not path.is_dir()
    ]
    
    if missing:
        raise FileNotFoundError(
            f"Missing {len(missing)} pretrained models. "
            f"Examples: {missing[:3]}"
        )
    
    eye = BoxEye(
        extent=CONFIG.eye_extent,
        kernel_size=CONFIG.eye_kernel_size,
    )
    
    centers_yx = (
        eye.receptor_centers
        .detach()
        .cpu()
        .numpy()
    )
    
    
    # ---------------------------------------------------------------------
    # 2. Build matched negative-control stimuli
    # ---------------------------------------------------------------------
    
    CONTROL_SPECS = {
        "3MIDD 48": (
            build_3midd_sequences(48)["negative"]
        ),
        "3MIDD 207": (
            build_3midd_sequences(207)["negative"]
        ),
        "4MIDD 85/170": (
            build_4midd_sequences(
                85,
                170,
            )["negative"]
        ),
    }
    
    negative_inputs = {}
    
    for condition, sequence in CONTROL_SPECS.items():
    
        image, _ = render_sector_image(
            sequence,
            image_size=382,
            inner_diameter=55,
            outer_diameter=382,
            phase_deg=0.0,
        )
    
        movie = np.repeat(
            (
                image.astype(np.float32)
                / 255.0
            )[None, None],
            N_FRAMES,
            axis=1,
        )
    
        rendered = eye(
            torch.as_tensor(
                movie,
                dtype=torch.float32,
            )
        ).cpu()
    
        assert tuple(rendered.shape) == (
            1,
            N_FRAMES,
            1,
            721,
        )
    
        negative_inputs[condition] = rendered
    
    
    print(
        "Negative-control conditions:",
        list(negative_inputs),
    )
    
    
    # ---------------------------------------------------------------------
    # 3. Official-50 inference
    # ---------------------------------------------------------------------
    
    columns = [
        "model_id",
        "condition",
        "T_negative",
        "mean_flow_magnitude",
    ]
    
    negative_df = (
        pd.read_csv(negative_path)
        if negative_path.is_file()
        else pd.DataFrame(columns=columns)
    )
    
    done = set(
        map(
            tuple,
            negative_df[
                ["model_id", "condition"]
            ].itertuples(
                index=False,
                name=None,
            ),
        )
    )
    
    
    for model_number, model_id in enumerate(
        MODEL_IDS,
        1,
    ):
    
        pending = [
            condition
            for condition in negative_inputs
            if (
                model_id,
                condition,
            ) not in done
        ]
    
        if not pending:
            print(
                f"[{model_number:02d}/50] "
                f"{model_id}: complete"
            )
            continue
    
        view = flyvis.NetworkView(
            model_paths[model_id]
        )
    
        network = (
            view.init_network()
            .to(DEVICE)
            .eval()
        )
    
        decoder = (
            view.init_decoder()["flow"]
            .to(DEVICE)
            .eval()
        )
    
        for condition in pending:
    
            result = run_flow_inference(
                negative_inputs[condition],
                network,
                decoder,
                dt=DT,
                fade=FADE,
                device=DEVICE,
            )
    
            flow = (
                result["flow"][0]
                .numpy()
            )
    
            assert flow.shape == (
                N_FRAMES,
                2,
                721,
            )
    
            assert np.isfinite(flow).all()
    
            metric = analyze_midd_flow(result["flow"], centers_yx, config=CONFIG)
    
            negative_df.loc[
                len(negative_df)
            ] = [
                model_id,
                condition,
                metric["mean_signed_tangent"],
                metric["mean_flow_magnitude"],
            ]
    
            done.add(
                (
                    model_id,
                    condition,
                )
            )
    
            print(
                f"[{model_number:02d}/50] "
                f"{condition} negative"
            )
    
        temp_path = (
            negative_path
            .with_suffix(".tmp")
        )
    
        (
            negative_df
            .sort_values(
                [
                    "model_id",
                    "condition",
                ]
            )
            .to_csv(
                temp_path,
                index=False,
            )
        )
    
        temp_path.replace(
            negative_path
        )
    
        del decoder, network, view
        gc.collect()
    
    
    # ---------------------------------------------------------------------
    # 4. QA
    # ---------------------------------------------------------------------
    
    assert len(negative_df) == 50 * 3
    
    assert (
        negative_df["model_id"]
        .nunique()
        == 50
    )
    
    assert (
        negative_df["condition"]
        .nunique()
        == 3
    )
    
    assert not negative_df.duplicated(
        [
            "model_id",
            "condition",
        ]
    ).any()
    
    
    # ---------------------------------------------------------------------
    # 5. Load the already-computed matched Original / Mirror results
    # ---------------------------------------------------------------------
    
    lum_a = pd.read_csv(
        output_dir
        / "fig2B_luminance_A_per_model.csv"
    )
    
    four_a = pd.read_csv(
        output_dir
        / "fig2D_4MIDD_A_per_model.csv"
    )
    
    assert lum_a["model_id"].nunique() == 50
    assert four_a["model_id"].nunique() == 50
    
    
    # ---------------------------------------------------------------------
    # 6. Assemble Original / Mirror / Negative in one long table
    # ---------------------------------------------------------------------
    
    records = []
    
    for c, label in [
        (48, "3MIDD 48"),
        (207, "3MIDD 207"),
    ]:
    
        q = (
            lum_a[
                lum_a["C"] == c
            ]
            .copy()
        )
    
        assert len(q) == 50
    
        for _, row in q.iterrows():
    
            records.extend(
                [
                    {
                        "model_id": row["model_id"],
                        "condition": label,
                        "variant": "Original",
                        "T": row["original"],
                    },
                    {
                        "model_id": row["model_id"],
                        "condition": label,
                        "variant": "Mirror",
                        "T": row["mirror"],
                    },
                ]
            )
    
    
    for _, row in four_a.iterrows():
    
        records.extend(
            [
                {
                    "model_id": row["model_id"],
                    "condition": "4MIDD 85/170",
                    "variant": "Original",
                    "T": row["original"],
                },
                {
                    "model_id": row["model_id"],
                    "condition": "4MIDD 85/170",
                    "variant": "Mirror",
                    "T": row["mirror"],
                },
            ]
        )
    
    
    structured_df = pd.DataFrame(records)
    
    negative_long = (
        negative_df[
            [
                "model_id",
                "condition",
                "T_negative",
            ]
        ]
        .rename(
            columns={
                "T_negative": "T",
            }
        )
    )
    
    negative_long["variant"] = "Negative"
    
    panel_df = pd.concat(
        [
            structured_df,
            negative_long[
                [
                    "model_id",
                    "condition",
                    "variant",
                    "T",
                ]
            ],
        ],
        ignore_index=True,
    )
    
    assert len(panel_df) == (
        50
        * 3
        * 3
    )
    
    
    # ---------------------------------------------------------------------
    # 7. Fig. 2E
    #    Raw signed tangential response for Original / Mirror / Negative
    # ---------------------------------------------------------------------
    
    condition_order = [
        "3MIDD 48",
        "3MIDD 207",
        "4MIDD 85/170",
    ]
    
    variant_order = [
        "Original",
        "Mirror",
        "Negative",
    ]
    
    colors = {
        "Original": "tab:blue",
        "Mirror": "tab:orange",
        "Negative": "0.45",
    }
    
    offsets = {
        "Original": -0.22,
        "Mirror": 0.00,
        "Negative": +0.22,
    }
    
    rng = np.random.default_rng(0)
    
    fig, ax = plt.subplots(
        figsize=(6.2, 3.8)
    )
    
    for condition_index, condition in enumerate(
        condition_order
    ):
    
        for variant in variant_order:
    
            q = panel_df[
                (
                    panel_df["condition"]
                    == condition
                )
                & (
                    panel_df["variant"]
                    == variant
                )
            ].copy()
    
            assert len(q) == 50
    
            x_center = (
                condition_index
                + offsets[variant]
            )
    
            jitter = rng.normal(
                loc=0,
                scale=0.025,
                size=len(q),
            )
    
            ax.scatter(
                np.full(
                    len(q),
                    x_center,
                )
                + jitter,
                q["T"],
                s=16,
                alpha=0.28,
                color=colors[variant],
                edgecolors="none",
            )
    
            mean = q["T"].mean()
            sem = q["T"].sem()
    
            ax.errorbar(
                x_center,
                mean,
                yerr=sem,
                fmt="o",
                color=colors[variant],
                markersize=6,
                linewidth=1.5,
                capsize=3,
                label=(
                    variant
                    if condition_index == 0
                    else None
                ),
                zorder=5,
            )
    
    
    ax.axhline(
        0,
        color="0.4",
        linewidth=0.8,
    )
    
    ax.set_xticks(
        range(
            len(condition_order)
        )
    )
    
    ax.set_xticklabels(
        condition_order
    )
    
    ax.set_ylabel(
        r"Signed tangential flow $T$ (CW positive)"
    )
    
    ax.set_xlabel("Stimulus")
    
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    
    ax.legend(
        frameon=False,
        fontsize=8,
        ncol=3,
    )
    
    fig.tight_layout()
    plt.show()
    
    
    # ---------------------------------------------------------------------
    # 8. Numerical summary
    # ---------------------------------------------------------------------
    
    summary = (
        panel_df
        .groupby(
            [
                "condition",
                "variant",
            ]
        )["T"]
        .agg(
            mean="mean",
            sem="sem",
        )
        .reindex(
            pd.MultiIndex.from_product(
                [
                    condition_order,
                    variant_order,
                ],
                names=[
                    "condition",
                    "variant",
                ],
            )
        )
    )
    
    print(summary)
    
    print("\nNegative controls:")
    for condition in condition_order:
    
        q = negative_df[
            negative_df["condition"]
            == condition
        ]
    
        print(
            f"{condition:14s}: "
            f"mean T={q['T_negative'].mean():+.6f}, "
            f"SEM={q['T_negative'].sem():.6f}"
        )
    
    print(
        "\nSaved:",
        negative_path,
    )

In [18]:
if False:  # acquisition archive; no new inference
    ## #cell 008
    # Fig. 2F — Direction agreement across the official-50 ensemble
    #
    # Reference direction:
    #   sign of the 50-model mean A for each stimulus.
    #
    # This is an ensemble-internal direction measure.
    # It is NOT a comparison with human perceptual direction.
    #
    # Shows:
    #   1. all 50 models
    #   2. models showing Actual reversal only
    
    from pathlib import Path
    
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    
    
    # ---------------------------------------------------------------------
    # 1. Load the matched official-50 results
    # ---------------------------------------------------------------------
    
    repo_root = Path(REPO_ROOT)
    data_dir = repo_root / "data/precomputed/fig02"
    
    lum_a = pd.read_csv(
        data_dir / "fig2B_luminance_A_per_model.csv"
    )
    
    four_a = pd.read_csv(
        data_dir / "fig2D_4MIDD_A_per_model.csv"
    )
    
    assert lum_a["model_id"].nunique() == 50
    assert four_a["model_id"].nunique() == 50
    
    
    # ---------------------------------------------------------------------
    # 2. Assemble the three fixed MIDD conditions
    # ---------------------------------------------------------------------
    
    groups = {
        "3MIDD 48": (
            lum_a[lum_a["C"] == 48]
            .copy()
        ),
        "3MIDD 207": (
            lum_a[lum_a["C"] == 207]
            .copy()
        ),
        "4MIDD 85/170": (
            four_a.copy()
        ),
    }
    
    rows = []
    
    for condition, q in groups.items():
    
        assert len(q) == 50
        assert q["model_id"].nunique() == 50
    
        # Ensemble reference direction for this stimulus
        mean_A = q["A"].mean()
        reference_sign = np.sign(mean_A)
    
        assert reference_sign != 0
    
        same_direction = (
            np.sign(q["A"])
            == reference_sign
        )
    
        # Actual reversal:
        # Original and Mirror have opposite signed rotation
        actual_reversal = aggregate_midd_metrics({"original": q["original"], "mirror": q["mirror"]})["actual_reversal"]
    
        reversal_q = q.loc[actual_reversal]
    
        reversal_same_direction = (
            np.sign(reversal_q["A"])
            == reference_sign
        )
    
        rows.append(
            {
                "condition": condition,
                "mean_A": mean_A,
                "reference_sign": int(reference_sign),
    
                "n_all": len(q),
                "n_same_all": int(
                    same_direction.sum()
                ),
                "agreement_all": float(
                    same_direction.mean()
                ),
    
                "n_reversal": len(reversal_q),
                "n_same_reversal": int(
                    reversal_same_direction.sum()
                ),
                "agreement_reversal": float(
                    reversal_same_direction.mean()
                ),
            }
        )
    
    
    agreement = pd.DataFrame(rows)
    
    
    # ---------------------------------------------------------------------
    # 3. Reproduction QA against Appendix 01
    # ---------------------------------------------------------------------
    
    expected = {
        "3MIDD 48": {
            "all": (43, 50),
            "reversal": (20, 21),
        },
        "3MIDD 207": {
            "all": (40, 50),
            "reversal": (17, 18),
        },
        "4MIDD 85/170": {
            "all": (34, 50),
            "reversal": (7, 12),
        },
    }
    
    for _, row in agreement.iterrows():
    
        exp = expected[row["condition"]]
    
        assert (
            int(row["n_same_all"]),
            int(row["n_all"]),
        ) == exp["all"]
    
        assert (
            int(row["n_same_reversal"]),
            int(row["n_reversal"]),
        ) == exp["reversal"]
    
    
    # ---------------------------------------------------------------------
    # 4. Fig. 2F
    # ---------------------------------------------------------------------
    
    condition_order = [
        "3MIDD 48",
        "3MIDD 207",
        "4MIDD 85/170",
    ]
    
    plot_df = (
        agreement
        .set_index("condition")
        .loc[condition_order]
        .reset_index()
    )
    
    x = np.arange(
        len(condition_order)
    )
    
    width = 0.34
    
    fig, ax = plt.subplots(
        figsize=(5.4, 3.7)
    )
    
    bars_all = ax.bar(
        x - width / 2,
        100 * plot_df["agreement_all"],
        width,
        color="0.65",
        label="All models",
    )
    
    bars_reversal = ax.bar(
        x + width / 2,
        100 * plot_df["agreement_reversal"],
        width,
        color="tab:blue",
        label="Actual-reversal models",
    )
    
    # 50% descriptive reference
    ax.axhline(
        50,
        color="0.55",
        linestyle="--",
        linewidth=0.9,
    )
    
    ax.set_xticks(x)
    ax.set_xticklabels(
        condition_order
    )
    
    ax.set_ylim(
        0,
        105,
    )
    
    ax.set_ylabel(
        "Direction agreement (%)"
    )
    
    ax.set_xlabel(
        "Stimulus"
    )
    
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    
    ax.legend(
        frameon=False,
        fontsize=8,
    )
    
    
    # Counts above bars
    for bar, (_, row) in zip(
        bars_all,
        plot_df.iterrows(),
    ):
        ax.text(
            bar.get_x()
            + bar.get_width() / 2,
            bar.get_height() + 2,
            f"{int(row['n_same_all'])}/{int(row['n_all'])}",
            ha="center",
            va="bottom",
            fontsize=8,
        )
    
    for bar, (_, row) in zip(
        bars_reversal,
        plot_df.iterrows(),
    ):
        ax.text(
            bar.get_x()
            + bar.get_width() / 2,
            bar.get_height() + 2,
            (
                f"{int(row['n_same_reversal'])}/"
                f"{int(row['n_reversal'])}"
            ),
            ha="center",
            va="bottom",
            fontsize=8,
        )
    
    fig.tight_layout()
    plt.show()
    
    
    # ---------------------------------------------------------------------
    # 5. Numerical summary
    # ---------------------------------------------------------------------
    
    display_columns = [
        "condition",
        "mean_A",
        "n_same_all",
        "n_all",
        "agreement_all",
        "n_same_reversal",
        "n_reversal",
        "agreement_reversal",
    ]
    
    print(
        agreement[
            display_columns
        ].to_string(
            index=False
        )
    )

In [19]:
if False:  # acquisition archive; no new inference
    ## #cell 009
    # Assemble the current manuscript-plan Fig. 2 panels A–F from the results above.
    
    import matplotlib.pyplot as plt
    
    plt.rcParams.update({"font.size": 8, "axes.spines.top": False, "axes.spines.right": False, "figure.dpi": 140})
    fig = plt.figure(figsize=(11.5, 12.0))
    grid = fig.add_gridspec(3, 2, hspace=0.42, wspace=0.34)
    
    # A — luminance conditions
    axes_a = grid[0, 0].subgridspec(3, 5, wspace=0.06, hspace=0.25)
    for ax, image, c in zip([fig.add_subplot(axes_a[r, col]) for r in range(3) for col in range(5)], images, LUMINANCE_LEVELS):
        ax.imshow(image, cmap="gray", vmin=0, vmax=255)
        ax.set_title(f"C = {c}", fontsize=7)
        ax.axis("off")
    ax_a0 = fig.axes[-15]
    ax_a0.text(-0.18, 1.20, "A", transform=ax_a0.transAxes, fontsize=12, fontweight="bold", va="top")
    
    # B — A(C) dose-response
    levels = [16, 32, 48, 64, 80, 96, 112, 128, 143, 159, 175, 191, 207, 223, 239]
    summary_b = lum_a.groupby("C")["A"].agg(["mean", "sem"]).reindex(levels)
    ax_b = fig.add_subplot(grid[0, 1])
    for _, q in lum_a.groupby("model_id"):
        q = q.sort_values("C")
        ax_b.plot(q["C"], q["A"], color="0.55", alpha=0.22, linewidth=0.7)
    ax_b.fill_between(levels, summary_b["mean"] - summary_b["sem"], summary_b["mean"] + summary_b["sem"], color="black", alpha=0.15)
    ax_b.plot(levels, summary_b["mean"], "-o", color="black", linewidth=2, markersize=3.5, label="50-model mean")
    ax_b.axhline(0, color="0.4", linewidth=0.8)
    for c in (48, 207):
        ax_b.axvline(c, color="0.45", linestyle="--", linewidth=0.8)
    ax_b.set(xlabel="3MIDD middle luminance, C", ylabel=r"$A=(T_O-T_M)/2$ (CW positive)")
    ax_b.set_xticks([16, 48, 80, 112, 143, 175, 207, 239])
    ax_b.legend(frameon=False, fontsize=7)
    ax_b.text(-0.12, 1.10, "B", transform=ax_b.transAxes, fontsize=12, fontweight="bold", va="top")
    
    # C — Original/Mirror at C=48 and C=207
    fixed_conditions = [48, 207]
    paired_main = lum_a[lum_a["C"].isin(fixed_conditions)].copy()
    paired_main["actual_reversal"] = aggregate_midd_metrics({"original": paired_main["original"], "mirror": paired_main["mirror"]})["actual_reversal"]
    limit_c = 1.05 * np.abs(paired_main[["original", "mirror"]].to_numpy()).max()
    axes_c = grid[1, 0].subgridspec(1, 2, wspace=0.20)
    for j, c in enumerate(fixed_conditions):
        ax = fig.add_subplot(axes_c[0, j])
        q = paired_main[paired_main["C"] == c]
        rev = q["actual_reversal"]
        ax.scatter(q.loc[~rev, "original"], q.loc[~rev, "mirror"], color="0.65", s=17, alpha=0.8, label="Same sign")
        ax.scatter(q.loc[rev, "original"], q.loc[rev, "mirror"], color="tab:blue", s=19, alpha=0.9, label="Actual reversal")
        ax.axhline(0, color="0.5", linewidth=0.7)
        ax.axvline(0, color="0.5", linewidth=0.7)
        ax.plot([-limit_c, limit_c], [-limit_c, limit_c], "--", color="0.8", linewidth=0.7)
        ax.set(xlim=(-limit_c, limit_c), ylim=(-limit_c, limit_c), aspect="equal", title=f"3MIDD  C = {c}")
        ax.set_xlabel(r"$T_{Original}$ (CW +)", fontsize=7)
        if j == 0:
            ax.set_ylabel(r"$T_{Mirror}$ (CW +)", fontsize=7)
            ax.legend(frameon=False, fontsize=6, loc="best")
            ax.text(-0.18, 1.18, "C", transform=ax.transAxes, fontsize=12, fontweight="bold", va="top")
    
    # D — 4MIDD Original/Mirror
    ax_d = fig.add_subplot(grid[1, 1])
    reversal_d = four_a["actual_reversal"]
    limit_d = 1.05 * np.abs(four_a[["original", "mirror"]].to_numpy()).max()
    ax_d.scatter(four_a.loc[~reversal_d, "original"], four_a.loc[~reversal_d, "mirror"], color="0.65", s=22, alpha=0.8, label="Same sign")
    ax_d.scatter(four_a.loc[reversal_d, "original"], four_a.loc[reversal_d, "mirror"], color="tab:blue", s=24, alpha=0.9, label="Actual reversal")
    ax_d.axhline(0, color="0.5", linewidth=0.8)
    ax_d.axvline(0, color="0.5", linewidth=0.8)
    ax_d.plot([-limit_d, limit_d], [-limit_d, limit_d], "--", color="0.8", linewidth=0.8)
    ax_d.set(xlim=(-limit_d, limit_d), ylim=(-limit_d, limit_d), aspect="equal", title="4MIDD  C1 = 85, C2 = 170",
             xlabel=r"$T_{Original}$ (CW +)", ylabel=r"$T_{Mirror}$ (CW +)")
    ax_d.legend(frameon=False, fontsize=7, loc="best")
    ax_d.text(-0.12, 1.10, "D", transform=ax_d.transAxes, fontsize=12, fontweight="bold", va="top")
    
    # E — matched Original/Mirror/Negative population comparison
    ax_e = fig.add_subplot(grid[2, 0])
    condition_order_e = ["3MIDD 48", "3MIDD 207", "4MIDD 85/170"]
    variant_order_e = ["Original", "Mirror", "Negative"]
    colors_e = {"Original": "tab:blue", "Mirror": "tab:orange", "Negative": "0.45"}
    offsets_e = {"Original": -0.22, "Mirror": 0.0, "Negative": 0.22}
    rng_e = np.random.default_rng(0)
    for ci, condition in enumerate(condition_order_e):
        for variant in variant_order_e:
            q = panel_df[(panel_df["condition"] == condition) & (panel_df["variant"] == variant)]
            x_center = ci + offsets_e[variant]
            jitter_e = rng_e.normal(0, 0.025, size=len(q))
            ax_e.scatter(np.full(len(q), x_center) + jitter_e, q["T"], s=12, alpha=0.28,
                         color=colors_e[variant], edgecolors="none")
            ax_e.errorbar(x_center, q["T"].mean(), yerr=q["T"].sem(), fmt="o", color=colors_e[variant],
                          markersize=5, linewidth=1.3, capsize=2.5,
                          label=variant if ci == 0 else None, zorder=5)
    ax_e.axhline(0, color="0.4", linewidth=0.8)
    ax_e.set_xticks(range(3), condition_order_e, rotation=8)
    ax_e.set_ylabel(r"Signed tangential flow $T$ (CW positive)")
    ax_e.legend(frameon=False, fontsize=7, ncol=3)
    ax_e.text(-0.12, 1.10, "E", transform=ax_e.transAxes, fontsize=12, fontweight="bold", va="top")
    
    # F — direction agreement across the ensemble
    ax_f = fig.add_subplot(grid[2, 1])
    condition_order_f = ["3MIDD 48", "3MIDD 207", "4MIDD 85/170"]
    plot_f = agreement.set_index("condition").loc[condition_order_f].reset_index()
    x_f = np.arange(len(condition_order_f))
    width_f = 0.34
    bars_all = ax_f.bar(x_f - width_f/2, 100 * plot_f["agreement_all"], width_f, color="0.65", label="All models")
    bars_rev = ax_f.bar(x_f + width_f/2, 100 * plot_f["agreement_reversal"], width_f, color="tab:blue", label="Actual-reversal models")
    ax_f.axhline(50, color="0.55", linestyle="--", linewidth=0.9)
    ax_f.set_xticks(x_f, condition_order_f, rotation=8)
    ax_f.set_ylim(0, 110)
    ax_f.set_ylabel("Direction agreement (%)")
    ax_f.legend(frameon=False, fontsize=7)
    for bar, (_, row) in zip(bars_all, plot_f.iterrows()):
        ax_f.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1.5, f"{int(row['n_same_all'])}/{int(row['n_all'])}", ha="center", va="bottom", fontsize=6)
    for bar, (_, row) in zip(bars_rev, plot_f.iterrows()):
        ax_f.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1.5, f"{int(row['n_same_reversal'])}/{int(row['n_reversal'])}", ha="center", va="bottom", fontsize=6)
    ax_f.text(-0.12, 1.10, "F", transform=ax_f.transAxes, fontsize=12, fontweight="bold", va="top")
    
    fig.tight_layout()
    OUT = REPO_ROOT / "figures" / "fig02"
    OUT.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT / "fig02_main.pdf", bbox_inches="tight")
    fig.savefig(OUT / "fig02_main.png", dpi=300, bbox_inches="tight")
    plt.show()
    print("Saved:", OUT / "fig02_main.png", "and", OUT / "fig02_main.pdf")