# Figure 6

Primary signed intervention change is normalized by paired noop mean flow magnitude. Broad T4 and T4+T5 effects support generic motion-readout dependence.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [distribution for module, distribution in required_modules.items()
               if importlib.util.find_spec(module) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = '6'

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/fig06/replacement_paired_loss...,e3ec244647fb0594d99b3c77763414b9ebfd3cdedfe3a7...,13238
1,data/precomputed/fig06/replacement_bootstrap.csv,e1ea0c57a146da3423ca47a0a7715ee107d40116e883a4...,3249
2,data/precomputed/fig06/replacement_qa.csv,12f2b7195d111615289cad69ad4311af12cf563f4608df...,5329
3,data/precomputed/fig06/robust_intervention_mod...,af9bcc64596db095eb3198ee30c11b2e4a120e988f4370...,29693
4,data/precomputed/fig06/robust_intervention_sum...,ac03e9ec916b620975ac2b2132b72eb302221ab9b3d477...,9804
5,data/precomputed/fig06/denominator_audit.csv,9a47b34f9aaa631b25a39d3a351c789f3905fc43a05cfb...,2767
6,data/precomputed/fig06/replacement_metrics.csv,36a4f61de1accd16dec753caa53a78e4ebb075658b85f2...,233951
7,data/precomputed/fig06/crossswap_metrics.csv,2f07747574d790cdb625646c5c6c810c05ce133ae6bde7...,165672
8,data/precomputed/fig06/crossswap_direction_acc...,a727a67ac7e8c6e46b1507eb14f851ce325d4089f3bed9...,6679
9,data/precomputed/fig06/crossswap_matched_model...,2bb6b32a3e77302db0339806a33ad3d09d449cfc337d53...,6850
10,data/precomputed/fig06/crossswap_direction_sum...,76285f6dd77fcec198dda6eb086195550d362069790a6a...,106

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 11

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

                                               check  passed
0  A/S identity: data/precomputed/fig06/crossswap...    True

## 5. Primary analysis
The shared analysis module deterministically derives the five panel datasets from the canonical compact tables and stops if source coverage or saved-table regression checks fail. No model inference or new statistics are run.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

panel_b_intervention

,model_id,intervention,condition,baseline,intervention_value,G_noop,raw_delta,normalized_change,baseline_aligned_attenuation,projected_MIDD_gain,RMS_normalized_difference
0,0,T4,MIDD,-0.001862,-0.013206,0.189787,-0.011344,-0.059772,-0.059772,-1.112365,3.048947
1,1,T4,MIDD,-0.001428,-0.000064,0.154596,0.001364,0.008823,0.008823,0.243796,0.764560
2,2,T4,MIDD,-0.011689,-0.000197,0.119211,0.011491,0.096395,0.096395,0.040555,0.977489
3,3,T4,MIDD,-0.030285,-0.006838,0.115196,0.023447,0.203540,0.203540,0.255587,0.762993
4,4,T4,MIDD,0.000317,0.003623,0.253071,0.003306,0.013063,-0.013063,0.236080,0.812302
5,5,T4,MIDD,-0.007756,-0.002067,0.117582,0.005689,0.048380,0.048380,0.128516,0.871896
6,6,T4,MIDD,-0.020855,-0.005142,0.129875,0.015713,0.120987,0.120987,0.181378,0.951815
7,7,T4,MIDD,-0.001204,0.000571,0.214629,0.001775,0.008271,0.008271,0.202591,0.802331
8,8,T4,MIDD,-0.006437,0.002518,0.161334,0.008955,0.055503,0.055503,0.871799,1.060493
9,9,T4,MIDD,-0.008111,0.002015,0.203824,0.010126,0.049681,0.049681,0.431188,0.677234
10,0,T4_T5,MIDD,-0.001862,-0.001399,0.189787,0.000463,0.002439,0.002439,0.183834,0.852881
11,1,T4_T5,MIDD,-0.001428,0.000092,0.154596,0.001520,0.009834,0.009834,0.128189,0.878877
12,2,T4_T5,MIDD,-0.011689,-0.000422,0.119211,0.011267,0.094510,0.094510,0.067676,0.944123
13,3,T4_T5,MIDD,-0.030285,-0.005673,0.115196,0.024612,0.213649,0.213649,0.206215,0.809737
14,4,T4_T5,MIDD,0.000317,0.003921,0.253071,0.003604,0.014242,-0.014242,0.214483,0.834830
15,5,T4_T5,MIDD,-0.007756,0.000579,0.117582,0.008335,0.070886,0.070886,0.233160,0.768516
16,6,T4_T5,MIDD,-0.020855,-0.002587,0.129875,0.018268,0.140659,0.140659,0.074676,1.026986
17,7,T4_T5,MIDD,-0.001204,0.001253,0.214629,0.002457,0.011448,0.011448,0.149769,0.860579
18,8,T4_T5,MIDD,-0.006437,0.004053,0.161334,0.010490,0.065019,0.065019,1.052165,1.391510
19,9,T4_T5,MIDD,-0.008111,0.001453,0.203824,0.009564,0.046921,0.046921,0.370829,0.683970

panel_c_physical

,model_id,intervention,condition,baseline,intervention_value,G_noop,raw_delta,normalized_change,baseline_aligned_attenuation,projected_MIDD_gain,RMS_normalized_difference
0,0,T4,edge,0.832073,0.813430,1.153256,-0.018644,-0.016166,0.016166,-1.112365,3.048947
1,1,T4,edge,0.685189,0.144639,0.879305,-0.540550,-0.614747,0.614747,0.243796,0.764560
2,2,T4,edge,0.983300,0.397665,1.267674,-0.585635,-0.461976,0.461976,0.040555,0.977489
3,3,T4,edge,0.959282,0.643717,1.240754,-0.315565,-0.254333,0.254333,0.255587,0.762993
4,4,T4,edge,0.863282,0.051593,1.115413,-0.811689,-0.727703,0.727703,0.236080,0.812302
5,5,T4,edge,0.768365,0.355197,0.919789,-0.413168,-0.449198,0.449198,0.128516,0.871896
6,6,T4,edge,1.371338,0.870816,1.857701,-0.500522,-0.269431,0.269431,0.181378,0.951815
7,7,T4,edge,0.742026,0.265684,1.056080,-0.476341,-0.451046,0.451046,0.202591,0.802331
8,8,T4,edge,0.639217,1.150480,0.759230,0.511263,0.673397,-0.673397,0.871799,1.060493
9,9,T4,edge,1.059555,-0.175832,1.406483,-1.235388,-0.878352,0.878352,0.431188,0.677234
10,0,T4_T5,edge,0.832073,0.761638,1.153256,-0.070436,-0.061075,0.061075,0.183834,0.852881
11,1,T4_T5,edge,0.685189,0.100061,0.879305,-0.585128,-0.665444,0.665444,0.128189,0.878877
12,2,T4_T5,edge,0.983300,0.135801,1.267674,-0.847499,-0.668546,0.668546,0.067676,0.944123
13,3,T4_T5,edge,0.959282,0.139047,1.240754,-0.820235,-0.661078,0.661078,0.206215,0.809737
14,4,T4_T5,edge,0.863282,0.130735,1.115413,-0.732547,-0.656750,0.656750,0.214483,0.834830
15,5,T4_T5,edge,0.768365,0.433206,0.919789,-0.335159,-0.364386,0.364386,0.233160,0.768516
16,6,T4_T5,edge,1.371338,0.356614,1.857701,-1.014725,-0.546226,0.546226,0.074676,1.026986
17,7,T4_T5,edge,0.742026,0.105284,1.056080,-0.636742,-0.602929,0.602929,0.149769,0.860579
18,8,T4_T5,edge,0.639217,-0.316839,0.759230,-0.956056,-1.259244,1.259244,1.052165,1.391510
19,9,T4_T5,edge,1.059555,-0.143698,1.406483,-1.203253,-0.855505,0.855505,0.370829,0.683970

panel_d_pairing

   network_id  matched_abs_A  mismatched_mean_abs_A  n_mismatched_decoders
0           0       0.002927               0.002357                      9
1           5       0.011335               0.010572                      9
2          10       0.002620               0.074533                      9
3          15       0.006022               0.032642                      9
4          20       0.010386               0.034526                      9
5          25       0.003518               0.014074                      9
6          30       0.030538               0.014847                      9
7          35       0.009825               0.009984                      9
8          40       0.007590               0.052751                      9
9          45       0.005404               0.033289                      9

panel_e_direction

    network_id  decoder_id  both_correct
0            0           0          True
1            0           5         False
2            0          10         False
3            0          15         False
4            0          20         False
5            0          25         False
6            0          30         False
7            0          35         False
8            0          40         False
9            0          45         False
10           5           0         False
11           5           5          True
12           5          10         False
13           5          15         False
14           5          20         False
15           5          25          True
16           5          30         False
17           5          35         False
18           5          40         False
19           5          45         False

fig6_QA

                                                check  passed
0               intervention cohort is models 000-009    True
1           intervention source has no duplicate keys    True
2   intervention source has complete required cond...    True
3               intervention source values are finite    True
4         Panel B contains 10 models for T4 and T4+T5    True
5   Panel C contains propeller and moving-edge dat...    True
6            Panels B/C normalized endpoint is finite    True
7                intervention derived-table agreement    True
8   Panel D uses complete 10 by 10 stable C48 cros...    True
9                     cross-swap pair keys are unique    True
10          cross-swap stable C48 A values are finite    True
11              cross-swap matrix has no missing pair    True
12  each Panel D network has exactly nine mismatch...    True
13           matched/mismatch derived-table agreement    True
14  direction table contains unique complete 10 by...    True
15  direction saved correctness definition is pres...    True
16    Panel E is a complete 10 by 10 direction matrix    True
17  direction counts match prespecified 10/10 and ...    True
18          direction-summary derived-table agreement    True
19          direction matched both-correct count = 10    True

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig06/replacement_paired_losses.csv

,model_id,intervention,A_C48_noop,A_C48_intervention,MIDD_loss,propeller_loss,edge_loss,propeller_magnitude_loss,MIDD_absolute_loss,projected_MIDD_loss,D_primary,D_edge,D_projected,denominators_valid,A_sign_flip
0,0,T4,-0.001862,-0.013206,-6.092053,0.322171,0.022406,0.198639,-6.092053,2.112365,-6.414224,-6.114460,1.790194,True,False
1,0,T4_T5,-0.001862,-0.001399,0.248546,0.589376,0.084651,0.489372,0.248546,0.816166,-0.340830,0.163895,0.226791,True,False
2,0,T4a,-0.001862,-0.001900,-0.020419,0.161108,0.524140,0.055375,-0.020419,0.602045,-0.181527,-0.544560,0.440937,True,False
3,0,T4b,-0.001862,-0.005152,-1.766716,0.189212,-0.029355,-0.030239,-1.766716,0.024639,-1.955928,-1.737361,-0.164573,True,False
4,0,all_input,-0.001862,0.000000,1.000000,1.000000,1.000000,0.986147,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
5,0,sham,-0.001862,-0.001553,0.166192,0.087072,0.167484,0.079138,0.166192,0.013509,0.079120,-0.001293,-0.073562,True,False
6,1,T4,-0.001428,-0.000064,0.955027,0.759028,0.788907,0.298910,0.955027,0.756204,0.196000,0.166121,-0.002824,True,False
7,1,T4_T5,-0.001428,0.000092,1.064399,0.919804,0.853966,0.606969,0.935601,0.871811,0.144596,0.210434,-0.047993,True,True
8,1,T4a,-0.001428,-0.001835,-0.284621,0.190935,1.045217,0.021094,-0.284621,0.155034,-0.475556,-1.329838,-0.035901,True,False
9,1,T4b,-0.001428,-0.001422,0.004366,0.215717,0.021275,-0.017355,0.004366,0.316807,-0.211351,-0.016909,0.101089,True,False
10,1,all_input,-0.001428,0.000000,1.000000,1.000000,1.000000,0.982540,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
11,1,sham,-0.001428,-0.001424,0.003298,-0.034341,-0.018691,-0.031616,0.003298,0.000256,0.037639,0.021989,0.034597,True,False
12,2,T4,-0.011689,-0.000197,0.983119,0.692448,0.595581,0.472069,0.983119,0.959445,0.290672,0.387538,0.266998,True,False
13,2,T4_T5,-0.011689,-0.000422,0.963900,0.778919,0.861892,0.690834,0.963900,0.932324,0.184981,0.102008,0.153406,True,False
14,2,T4a,-0.011689,-0.008286,0.291120,0.245263,0.512111,0.040560,0.291120,0.255725,0.045857,-0.220991,0.010462,True,False
15,2,T4b,-0.011689,-0.010896,0.067844,0.098277,-0.212452,0.077199,0.067844,0.029200,-0.030432,0.280296,-0.069077,True,False
16,2,all_input,-0.011689,0.000000,1.000000,1.000000,1.000000,0.985785,1.000000,1.000000,0.000000,0.000000,0.000000,True,False
17,2,sham,-0.011689,-0.009669,0.172802,-0.002202,0.029208,-0.000896,0.172802,0.147645,0.175004,0.143594,0.149848,True,False
18,3,T4,-0.030285,-0.006838,0.774211,0.700633,0.328959,0.381318,0.774211,0.744413,0.073578,0.445252,0.043780,True,False
19,3,T4_T5,-0.030285,-0.005673,0.812665,0.786315,0.855051,0.284888,0.812665,0.793785,0.026350,-0.042386,0.007470,True,False

data/precomputed/fig06/replacement_bootstrap.csv

,intervention,metric,n_models,mean,median,ci_low,ci_high
0,T4,MIDD_loss,10,-0.819937,0.864619,-3.453122,1.103754
1,T4,propeller_loss,10,0.596824,0.599281,0.520820,0.661208
2,T4,edge_loss,10,0.458687,0.566652,0.100500,0.752396
3,T4,propeller_magnitude_loss,10,0.286890,0.261829,0.216857,0.360765
4,T4,D_primary,10,-1.416760,0.203123,-3.987315,0.479301
5,T4,D_edge,10,-1.278624,0.291629,-3.951124,0.735470
6,T4,D_projected,10,0.255264,0.179512,-0.019905,0.638554
7,T4,MIDD_absolute_loss,10,-1.042770,0.742496,-3.582718,0.790762
8,T4_T5,MIDD_loss,10,-0.147103,1.014150,-2.753953,1.327386
9,T4_T5,propeller_loss,10,0.709927,0.696193,0.649792,0.776163
10,T4_T5,edge_loss,10,0.816967,0.854508,0.596886,1.035659
11,T4_T5,propeller_magnitude_loss,10,0.444166,0.460585,0.342795,0.542837
12,T4_T5,D_primary,10,-0.857030,0.196899,-3.450746,0.616261
13,T4_T5,D_edge,10,-0.964070,0.134982,-3.538832,0.473123
14,T4_T5,D_projected,10,0.021974,0.068554,-0.146255,0.143973
15,T4_T5,MIDD_absolute_loss,10,-0.544858,0.816775,-3.029925,0.814393
16,T4a,MIDD_loss,10,0.424107,0.174111,0.016532,1.049922
17,T4a,propeller_loss,10,0.181795,0.176829,0.156547,0.207859
18,T4a,edge_loss,10,0.450430,0.518126,0.230587,0.662403
19,T4a,propeller_magnitude_loss,10,0.051751,0.030827,0.011005,0.098153

data/precomputed/fig06/replacement_qa.csv

    model_id          group     max_error  passed                    check
0          0      3MIDD_048  6.355295e-08    True  pre_extension_canonical
1          0      3MIDD_207  2.538126e-08    True  pre_extension_canonical
2          0  4MIDD_085_170  2.009836e-08    True  pre_extension_canonical
3          0            NaN           NaN    True              noop_Static
4          0            NaN           NaN    True                  noop_CW
5          0            NaN           NaN    True                 noop_CCW
6          0            NaN           NaN    True               noop_Right
7          0            NaN           NaN    True                noop_Left
8          0            NaN           NaN    True     noop_MIDD_0_original
9          0            NaN           NaN    True       noop_MIDD_0_mirror
10         0            NaN           NaN    True    noop_MIDD_48_original
11         0            NaN           NaN    True      noop_MIDD_48_mirror
12         0            NaN           NaN    True    noop_MIDD_85_original
13         0            NaN           NaN    True      noop_MIDD_85_mirror
14         0            NaN           NaN    True   noop_MIDD_128_original
15         0            NaN           NaN    True     noop_MIDD_128_mirror
16         0            NaN           NaN    True   noop_MIDD_170_original
17         0            NaN           NaN    True     noop_MIDD_170_mirror
18         0            NaN           NaN    True   noop_MIDD_207_original
19         0            NaN           NaN    True     noop_MIDD_207_mirror

data/precomputed/fig06/robust_intervention_model_metrics.csv

,model_id,intervention,condition,baseline,intervention_value,G_noop,raw_delta,normalized_change,baseline_aligned_attenuation,projected_MIDD_gain,RMS_normalized_difference
0,0,T4,MIDD,-0.001862,-0.013206,0.189787,-0.011344,-0.059772,-0.059772,-1.112365,3.048947
1,0,T4,propeller,9.756061,6.612944,10.712049,-3.143117,-0.293419,0.293419,-1.112365,3.048947
2,0,T4,edge,0.832073,0.813430,1.153256,-0.018644,-0.016166,0.016166,-1.112365,3.048947
3,0,T4_T5,MIDD,-0.001862,-0.001399,0.189787,0.000463,0.002439,0.002439,0.183834,0.852881
4,0,T4_T5,propeller,9.756061,4.006075,10.712049,-5.749985,-0.536777,0.536777,0.183834,0.852881
5,0,T4_T5,edge,0.832073,0.761638,1.153256,-0.070436,-0.061075,0.061075,0.183834,0.852881
6,0,T4a,MIDD,-0.001862,-0.001900,0.189787,-0.000038,-0.000200,-0.000200,0.397955,0.703503
7,0,T4a,propeller,9.756061,8.184284,10.712049,-1.571777,-0.146730,0.146730,0.397955,0.703503
8,0,T4a,edge,0.832073,0.395950,1.153256,-0.436123,-0.378167,0.378167,0.397955,0.703503
9,0,T4b,MIDD,-0.001862,-0.005152,0.189787,-0.003290,-0.017334,-0.017334,0.975361,0.490710
10,0,T4b,propeller,9.756061,7.910101,10.712049,-1.845960,-0.172326,0.172326,0.975361,0.490710
11,0,T4b,edge,0.832073,0.856499,1.153256,0.024426,0.021180,-0.021180,0.975361,0.490710
12,0,all_input,MIDD,-0.001862,0.000000,0.189787,0.001862,0.009811,0.009811,0.000000,1.000000
13,0,all_input,propeller,9.756061,0.000000,10.712049,-9.756061,-0.910756,0.910756,0.000000,1.000000
14,0,all_input,edge,0.832073,0.000000,1.153256,-0.832073,-0.721499,0.721499,0.000000,1.000000
15,0,sham,MIDD,-0.001862,-0.001553,0.189787,0.000309,0.001631,0.001631,0.986491,0.075495
16,0,sham,propeller,9.756061,8.906586,10.712049,-0.849475,-0.079301,0.079301,0.986491,0.075495
17,0,sham,edge,0.832073,0.692714,1.153256,-0.139359,-0.120840,0.120840,0.986491,0.075495
18,1,T4,MIDD,-0.001428,-0.000064,0.154596,0.001364,0.008823,0.008823,0.243796,0.764560
19,1,T4,propeller,10.720002,2.583221,11.467406,-8.136781,-0.709557,0.709557,0.243796,0.764560

data/precomputed/fig06/robust_intervention_summary.csv

,intervention,condition,metric,mean,median,ci_low,ci_high
0,T4,MIDD,normalized_change,0.054487,0.049030,0.013611,0.100006
1,T4,MIDD,baseline_aligned_attenuation,0.051874,0.049030,0.010934,0.098355
2,T4,MIDD,raw_delta,0.007052,0.007322,0.001366,0.012364
3,T4,MIDD,projected_MIDD_gain,0.147913,0.219336,-0.177908,0.405746
4,T4,MIDD,RMS_normalized_difference,1.073006,0.842099,0.800362,1.536004
5,T4,edge,normalized_change,-0.344956,-0.450122,-0.572562,-0.065389
6,T4,edge,baseline_aligned_attenuation,0.344956,0.450122,0.064527,0.574440
7,T4,edge,raw_delta,-0.438624,-0.488432,-0.702564,-0.157349
8,T4,edge,projected_MIDD_gain,0.147913,0.219336,-0.183183,0.400032
9,T4,edge,RMS_normalized_difference,1.073006,0.842099,0.801035,1.532324
10,T4,propeller,normalized_change,-0.561353,-0.565466,-0.620647,-0.488791
11,T4,propeller,baseline_aligned_attenuation,0.561353,0.565466,0.489892,0.621270
12,T4,propeller,raw_delta,-6.390817,-6.328147,-7.348119,-5.379763
13,T4,propeller,projected_MIDD_gain,0.147913,0.219336,-0.189237,0.400130
14,T4,propeller,RMS_normalized_difference,1.073006,0.842099,0.800587,1.539613
15,T4_T5,MIDD,normalized_change,0.066961,0.055970,0.030516,0.110402
16,T4_T5,MIDD,baseline_aligned_attenuation,0.064112,0.055970,0.026616,0.107839
17,T4_T5,MIDD,raw_delta,0.009058,0.008949,0.004815,0.013936
18,T4_T5,MIDD,projected_MIDD_gain,0.268099,0.195025,0.142934,0.461740
19,T4_T5,MIDD,RMS_normalized_difference,0.905201,0.856730,0.809103,1.030693

data/precomputed/fig06/denominator_audit.csv

,intervention,condition,q0,q5,q25,q50,q75,q95,q100,n,excluded
0,T4,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
1,T4,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
2,T4,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
3,T4_T5,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
4,T4_T5,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
5,T4_T5,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
6,T4a,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
7,T4a,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
8,T4a,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
9,T4b,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
10,T4b,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
11,T4b,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
12,all_input,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
13,all_input,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
14,all_input,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
15,sham,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
16,sham,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
17,sham,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0

data/precomputed/fig06/replacement_metrics.csv

,model_id,condition,intervention,mean_flow_magnitude,mean_signed_tangent,mean_abs_tangent,signed_tangent_ratio,rotation_coherence,mean_signed_radial,annulus_positions,annulus_receptors,mean_u
0,0,Static,noop,0.275658,-0.107649,0.139993,-0.390517,0.768963,0.178290,698,698,-0.076315
1,0,Static,T4a,0.387465,-0.099979,0.189618,-0.258034,0.527265,0.174250,698,698,-0.008540
2,0,Static,T4b,0.500321,-0.024984,0.304798,-0.049936,0.081969,0.160870,698,698,-0.400876
3,0,Static,T4,1.616435,0.149755,0.996580,0.092645,0.150269,0.386532,698,698,-0.743651
4,0,Static,T4_T5,1.354645,-0.021478,0.803792,-0.015855,0.026721,0.611023,698,698,-0.493896
5,0,Static,sham,0.269857,-0.085025,0.137967,-0.315075,0.616273,0.144984,698,698,-0.153208
6,0,Static,all_input,0.148397,0.032469,0.075630,0.218801,0.429321,0.084941,698,698,-0.092684
7,0,CW,noop,10.784526,9.815791,9.960090,0.910174,0.985512,1.365292,698,698,0.445993
8,0,CW,T4a,10.126642,8.102660,8.523523,0.800133,0.950623,1.450428,698,698,3.169957
9,0,CW,T4b,11.227115,7.922450,9.241721,0.705653,0.857248,1.789472,698,698,-3.540715
10,0,CW,T4,8.688635,6.609141,7.221971,0.760665,0.915144,1.609094,698,698,-1.281635
11,0,CW,T4_T5,5.594470,4.031019,4.333545,0.720536,0.930190,0.550387,698,698,1.222162
12,0,CW,sham,9.932143,8.967919,9.116608,0.902919,0.983690,1.249587,698,698,-0.065840
13,0,CW,all_input,0.148397,0.032469,0.075630,0.218801,0.429321,0.084941,698,698,-0.092684
14,0,CCW,noop,10.639571,-9.696330,9.766401,-0.911346,0.992825,-0.189845,698,698,0.032985
15,0,CCW,T4a,10.111106,-8.265908,8.604373,-0.817508,0.960664,-0.430680,698,698,2.759341
16,0,CCW,T4b,10.844828,-7.897752,8.839176,-0.728251,0.893494,-0.814654,698,698,-3.762819
17,0,CCW,T4,8.479799,-6.616747,7.069857,-0.780295,0.935910,-0.183567,698,698,-1.357840
18,0,CCW,T4_T5,5.345282,-3.981132,4.220748,-0.744794,0.943229,0.514173,698,698,1.141540
19,0,CCW,sham,9.796504,-8.845252,8.936096,-0.902899,0.989834,-0.098964,698,698,-0.417888

## 7. Statistics
This reconstruction adds no inferential test, confidence interval, bootstrap, or endpoint. Model is the unit in intervention and network-level matched/mismatched displays; the 90 cross-swap mismatches are summarized within their 10 networks.

In [7]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

data/precomputed/fig06/replacement_bootstrap.csv

,intervention,metric,n_models,mean,median,ci_low,ci_high
0,T4,MIDD_loss,10,-0.819937,0.864619,-3.453122,1.103754
1,T4,propeller_loss,10,0.596824,0.599281,0.520820,0.661208
2,T4,edge_loss,10,0.458687,0.566652,0.100500,0.752396
3,T4,propeller_magnitude_loss,10,0.286890,0.261829,0.216857,0.360765
4,T4,D_primary,10,-1.416760,0.203123,-3.987315,0.479301
5,T4,D_edge,10,-1.278624,0.291629,-3.951124,0.735470
6,T4,D_projected,10,0.255264,0.179512,-0.019905,0.638554
7,T4,MIDD_absolute_loss,10,-1.042770,0.742496,-3.582718,0.790762
8,T4_T5,MIDD_loss,10,-0.147103,1.014150,-2.753953,1.327386
9,T4_T5,propeller_loss,10,0.709927,0.696193,0.649792,0.776163
10,T4_T5,edge_loss,10,0.816967,0.854508,0.596886,1.035659
11,T4_T5,propeller_magnitude_loss,10,0.444166,0.460585,0.342795,0.542837
12,T4_T5,D_primary,10,-0.857030,0.196899,-3.450746,0.616261
13,T4_T5,D_edge,10,-0.964070,0.134982,-3.538832,0.473123
14,T4_T5,D_projected,10,0.021974,0.068554,-0.146255,0.143973
15,T4_T5,MIDD_absolute_loss,10,-0.544858,0.816775,-3.029925,0.814393
16,T4a,MIDD_loss,10,0.424107,0.174111,0.016532,1.049922
17,T4a,propeller_loss,10,0.181795,0.176829,0.156547,0.207859
18,T4a,edge_loss,10,0.450430,0.518126,0.230587,0.662403
19,T4a,propeller_magnitude_loss,10,0.051751,0.030827,0.011005,0.098153
20,T4a,D_primary,10,0.242312,0.006166,-0.178983,0.868450
21,T4a,D_edge,10,-0.026323,-0.236827,-0.559519,0.685460
22,T4a,D_projected,10,0.098914,-0.005867,-0.036604,0.252894
23,T4a,MIDD_absolute_loss,10,0.025919,0.073919,-0.255813,0.274519
24,T4b,MIDD_loss,10,0.261734,-0.019376,-0.735994,1.695205
25,T4b,propeller_loss,10,0.166224,0.202464,0.100516,0.223476
26,T4b,edge_loss,10,0.177969,0.013778,-0.020066,0.398039
27,T4b,propeller_magnitude_loss,10,0.044319,0.054025,-0.008048,0.101765
28,T4b,D_primary,10,0.095510,-0.169917,-0.908685,1.502857
29,T4b,D_edge,10,0.083765,-0.033154,-0.895945,1.435022
30,T4b,D_projected,10,-0.066772,-0.076240,-0.154121,0.023470
31,T4b,MIDD_absolute_loss,10,-0.765922,-0.070437,-1.670958,-0.060932

data/precomputed/fig06/denominator_audit.csv

,intervention,condition,q0,q5,q25,q50,q75,q95,q100,n,excluded
0,T4,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
1,T4,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
2,T4,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
3,T4_T5,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
4,T4_T5,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
5,T4_T5,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
6,T4a,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
7,T4a,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
8,T4a,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
9,T4b,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
10,T4b,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
11,T4b,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
12,all_input,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
13,all_input,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
14,all_input,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0
15,sham,MIDD,0.115196,0.116270,0.121877,0.157965,0.200315,0.235772,0.253071,10,0
16,sham,edge,0.759230,0.813264,0.953862,1.134334,1.260944,1.654653,1.857701,10,0
17,sham,propeller,9.085153,9.288611,10.627711,11.237086,11.801027,13.651906,13.796480,10,0

## 8. Figure generation
The shared renderer creates the five-panel Figure 6 from the validated panel datasets. It reads no figure-specific derived CSV for plotting.

In [8]:
fig = render(FIGURE, analysis=primary)
display(fig)

<repository-root>/src/flyvis_midd/figure_rendering.py:50: UserWarning: constrained_layout not applied because axes sizes collapsed to zero.  Try making figure larger or Axes decorations smaller.
  fig.savefig(d/(prefix+'_main.pdf'),bbox_inches='tight');fig.savefig(d/(prefix+'_main.png'),dpi=220,bbox_inches='tight')

Saved 6 inputs 3 checks 22

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [9]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: 6 primary tables: 5 adopted tables: 7

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [10]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/fig06/fig_6.ipynb
Model inference: False