# Figure 3

Stronger comparators exclude the target from the ensemble and use all nine other-model donors. LOLO is conditional held-out affine validation, not independent-stimulus generalization.

## 1. Imports and configuration
Artifact-only replay; no models or acquisition Notebook execution.

In [1]:
# Colab needs the repository's saved analysis inputs, not just the package.
import importlib
import importlib.util
import os
import site
import subprocess
import sys
from pathlib import Path

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    ROOT = Path("/content/flyvis-midd")
    if not (ROOT / "src/flyvis_midd").is_dir():
        if ROOT.exists():
            raise RuntimeError("/content/flyvis-midd exists but is not a repository checkout.")
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", "main",
             "https://github.com/poxsalop5029/flyvis-midd.git", str(ROOT)],
            capture_output=True, text=True,
        )
        if result.returncode:
            message = result.stderr or result.stdout
            raise RuntimeError("Could not clone the public flyvis-midd repository: " + message[-2000:])
    missing = [name for name in ("numpy", "pandas", "matplotlib")
               if importlib.util.find_spec(name) is None]
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        for package_dir in site.getsitepackages():
            site.addsitedir(package_dir)
    importlib.invalidate_caches()
else:
    ROOT = next(
        (p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
         if (p / "src/flyvis_midd").is_dir()), None,
    )
    if ROOT is None:
        raise RuntimeError("Run this notebook from inside the flyvis-midd repository.")
sys.path.insert(0, str(ROOT / "src"))
print("Repository inputs:", ROOT)


from IPython.display import display
from flyvis_midd.figure_analysis import (
    input_manifest, load_tables, validate_inputs, primary_analysis,
    adopted_analysis, statistical_tables, write_reproduction_record,
)
from flyvis_midd.figure_rendering import render
FIGURE = '3'

Repository inputs: <repository-root>

## 2. Input artifact manifest
Source paths and SHA-256 identify the immutable numerical inputs. Bundled precomputed artifacts are numerical inputs.

In [2]:
manifest = input_manifest(FIGURE, ROOT)
display(manifest)

,path,sha256,bytes
0,data/precomputed/fig03/...,0dfb651f163a89dbf56d250787fe4a245f8ff7b2fecbc9...,1180
1,data/precomputed/fig03/...,ffcfd3d8148f4adf4248490208d1a5699da95e86c6acd6...,1392
2,data/precomputed/fig03/...,0bb5e3d0d75ef27d779a27e55c1584fb74846598584faa...,6108
3,data/precomputed/fig03/fig3_3MIDD_components_p...,61cbfbb833fe1ca116b7efd771dbd2e70000448df73184...,6107
4,data/precomputed/fig03/fig3_canonical_pair_pre...,29d63afc77f55ce85ecb440a38e83832cea3b5e4ccee15...,46393
5,data/precomputed/fig03/...,832a2b8988076b2907e8858ce2a4be6cec8922d7e078e1...,6446038
6,data/precomputed/fig03/...,f1e3d075241fc394b60fc6bb54e96c9fbbf4237b4a8d79...,754
7,data/precomputed/fig03/...,44f699c4907e923e9b0d8775478b3a103139b230fdcba3...,859
8,data/precomputed/supplementary/figS1/...,99cd9f86db78bab1da5e8e99a8c9e1970ad01fb2b159bc...,2437
9,data/precomputed/supplementary/figS1/...,b08b8527a45859697490b925e604af55ea5bd0cd32eef2...,229
10,data/precomputed/fig03/...,eea19a9d1e275d097e711c072b8ee4dec21602c3ead5a9...,4721
11,data/precomputed/fig03/...,3a4ee9c4d6b4219d80ff9879b800e3e0c61b4686509333...,1203
12,data/precomputed/fig03/...,7fe748fcf0ed03063ed3731cf85e35f4f1380f2b5f531a...,313

## 3. Canonical data load
Each source keeps its cohort, renderer, operator, temporal support, and metric.

In [3]:
tables = load_tables(manifest, ROOT)
print("Loaded source tables:", len(tables))

Loaded source tables: 13

## 4. QA and assertions
Check within-contract A/S algebra and adopted source equivalence before saving.

In [4]:
integration_checks = validate_inputs(tables)
display(integration_checks)

Empty DataFrame
Columns: [check, passed]
Index: []

## 5. Primary analysis
For Fig3/S7, affine fits and both held-out splits are recomputed from saved A3/A4. Native and multi-field definitions remain separate.

In [5]:
primary = primary_analysis(FIGURE, tables)
for name, frame in primary.items():
    print(name)
    display(frame.head(20))

affine_fit

   model_id     slope  intercept        r2  normalized_rmse  sign_agreement
0         0  0.562523   0.008200  0.926161         0.225593            1.00
1         1  0.791128   0.010205  0.831244         0.143963            1.00
2         2  0.645723   0.003829  0.913902         0.165043            1.00
3         3  0.798766   0.009874  0.984027         0.093705            0.95
4         4  0.842107   0.003533  0.976916         0.081867            1.00
5         5  1.054478   0.009714  0.950136         0.142653            1.00
6         6  0.790570   0.012877  0.948106         0.131468            0.95
7         7  0.859438  -0.000770  0.966668         0.113438            1.00
8         8  1.098226  -0.001381  0.951099         0.125220            1.00
9         9  0.848756   0.017610  0.847075         0.418057            0.75

held_out_prediction

    model_id               split     cv_r2   cv_rmse  sign_accuracy
0          0                LOLO  0.900989  0.008186       0.944444
1          0  leave_one_pair_out  0.911574  0.007736       0.944444
2          1                LOLO  0.762314  0.011052       0.900000
3          1  leave_one_pair_out  0.795503  0.010251       0.900000
4          2                LOLO  0.873427  0.004458       0.925000
5          2  leave_one_pair_out  0.892752  0.004104       0.950000
6          3                LOLO  0.977195  0.006284       0.850000
7          3  leave_one_pair_out  0.980649  0.005789       0.850000
8          4                LOLO  0.967062  0.005553       1.000000
9          4  leave_one_pair_out  0.972405  0.005083       1.000000
10         5                LOLO  0.930512  0.011500       1.000000
11         5  leave_one_pair_out  0.942008  0.010506       1.000000
12         6                LOLO  0.928771  0.007428       0.925000
13         6  leave_one_pair_out  0.935590  0.007064       0.900000
14         7                LOLO  0.954625  0.002326       1.000000
15         7  leave_one_pair_out  0.958097  0.002236       1.000000
16         8                LOLO  0.918712  0.005598       1.000000
17         8  leave_one_pair_out  0.938939  0.004851       1.000000
18         9                LOLO  0.810176  0.007081       0.950000
19         9  leave_one_pair_out  0.817418  0.006945       0.950000

model_bootstrap

      source           metric      mean    ci_low   ci_high
0  in_sample            slope  0.829171  0.735793  0.926342
1  in_sample        intercept  0.007369  0.003912  0.010905
2  in_sample               r2  0.929533  0.896267  0.957286
3  in_sample   sign_agreement  0.965000  0.915000  1.000000
4  in_sample  normalized_rmse  0.164101  0.117946  0.227061
5       LOLO            cv_r2  0.902378  0.858770  0.939922
6       LOLO          cv_rmse  0.006947  0.005280  0.008640
7       LOLO    sign_accuracy  0.949444  0.918889  0.977500

structured_nulls

                        family  delta_r2    ci_low   ci_high
0                          sum  1.199115  1.040639  1.344252
1  luminance_label_permutation  1.174734  1.101558  1.241541
2      smooth_potential_ls0.25  0.885534  0.837294  0.926397
3       smooth_potential_ls0.1  1.193446  1.126214  1.251521
4       smooth_potential_ls0.5  0.769393  0.719931  0.820044

comparator_prediction

,model_id,predictor,cv_r2,cv_rmse,normalized_rmse,sign_accuracy,slope,intercept
0,0,P0,0.900989,0.008186,0.066597,0.944444,0.562523,0.008200
1,0,P1,0.549827,0.017455,0.142005,0.944444,0.886383,0.016002
30,0,P2,0.295981,0.020985,0.170725,0.944444,0.561981,0.023860
2,0,P3,0.309285,0.021621,0.175899,0.944444,-0.000469,0.008384
3,1,P0,0.762314,0.011052,0.144273,0.900000,0.791128,0.010205
4,1,P1,0.520112,0.015703,0.205000,0.900000,0.705148,0.017456
31,1,P2,0.238484,0.019114,0.249519,0.900000,0.435164,0.024808
5,1,P3,0.125872,0.021194,0.276677,0.900000,-0.000374,0.013158
6,2,P0,0.873427,0.004458,0.087671,0.925000,0.645723,0.003829
7,2,P1,0.781763,0.005854,0.115120,0.850000,0.429397,0.002859
32,2,P2,0.478309,0.008538,0.167901,0.847222,0.304427,0.007769
8,2,P3,0.166028,0.011444,0.225041,0.850000,-0.000197,0.003248
9,3,P0,0.977195,0.006284,0.050295,0.850000,0.798766,0.009874
10,3,P1,0.843304,0.016473,0.131837,0.925000,1.681888,0.002194
33,3,P2,0.458165,0.027990,0.224009,0.866667,1.132895,0.019209
11,3,P3,0.300253,0.034812,0.278599,0.800000,-0.000718,0.001422
12,4,P0,0.967062,0.005553,0.053207,1.000000,0.842107,0.003533
13,4,P1,0.917666,0.008780,0.084121,0.950000,1.184908,0.009009
34,4,P2,0.586132,0.017550,0.168150,0.913889,0.866563,0.021140
14,4,P3,0.651187,0.018071,0.173145,0.900000,-0.000640,-0.000662

all_cross_model_donors

,model_id,donor_id,cv_r2,cv_rmse,normalized_rmse,sign_accuracy,slope,intercept
0,0,1,0.850567,0.010057,0.081816,0.944444,0.941578,0.006647
1,0,2,0.456604,0.019177,0.156017,0.944444,1.110901,0.018826
2,0,3,0.575075,0.016959,0.137965,0.944444,0.421299,0.019419
3,0,4,0.524523,0.017939,0.145941,0.944444,0.603233,0.012190
4,0,5,0.366113,0.020713,0.168507,0.944444,0.487365,0.018009
5,0,6,0.475310,0.018845,0.153308,0.944444,0.597702,0.022423
6,0,7,-0.218166,0.028714,0.233597,0.944444,-0.157589,0.042593
7,0,8,-0.024366,0.026331,0.214210,0.944444,0.615434,0.037000
8,0,9,-0.341827,0.030136,0.245167,0.944444,0.437910,0.037634
9,1,0,0.820887,0.009594,0.125242,0.900000,0.473779,0.011441
10,1,2,0.384769,0.017781,0.232115,0.900000,0.935484,0.020393
11,1,3,0.544155,0.015305,0.199799,0.900000,0.358674,0.020680
12,1,4,0.409854,0.017414,0.227334,0.900000,0.500932,0.015159
13,1,5,0.267229,0.019405,0.253320,0.900000,0.406060,0.019924
14,1,6,0.443413,0.016912,0.220776,0.900000,0.508839,0.023238
15,1,7,-0.236964,0.025212,0.329127,0.900000,-0.147231,0.040421
16,1,8,-0.048954,0.023217,0.303084,0.900000,0.522027,0.035664
17,1,9,-0.438037,0.027184,0.354871,0.900000,0.357913,0.036351
18,2,0,0.461183,0.009199,0.180887,0.800000,0.230401,0.003533
19,2,1,0.462291,0.009189,0.180701,0.800000,0.387855,0.002813

## 6. Adopted validation and controls
Use frozen source records for matched controls, geometry, learning, interventions, and duration. Do not substitute historical intervention estimates for the common-gray operation.

In [6]:
adopted = adopted_analysis(FIGURE, tables)
for name, frame in adopted.items():
    print(name)
    display(frame.head(20))

data/precomputed/fig03/composition_model_metrics.csv

,model_id,slope,intercept,r2,identity_rmse,normalized_rmse,sign_agreement,n_sign_evaluable
0,0,0.562523,0.008200,0.926161,0.027730,0.225593,1.00,18
1,1,0.791128,0.010205,0.831244,0.011028,0.143963,1.00,20
2,2,0.645723,0.003829,0.913902,0.008393,0.165043,1.00,20
3,3,0.798766,0.009874,0.984027,0.011709,0.093705,0.95,20
4,4,0.842107,0.003533,0.976916,0.008544,0.081867,1.00,20
5,5,1.054478,0.009714,0.950136,0.015957,0.142653,1.00,19
6,6,0.790570,0.012877,0.948106,0.011229,0.131468,0.95,20
7,7,0.859438,-0.000770,0.966668,0.002805,0.113438,1.00,20
8,8,1.098226,-0.001381,0.951099,0.004695,0.125220,1.00,21
9,9,0.848756,0.017610,0.847075,0.017373,0.418057,0.75,20

data/precomputed/fig03/composition_cv_metrics.csv

,model_id,split,cv_r2,cv_rmse,sign_accuracy,n_test_predictions,n_unique_pairs
0,0,LOLO,0.900989,0.008186,0.944444,42,21
1,0,leave_one_pair_out,0.911574,0.007736,0.944444,21,21
2,1,LOLO,0.762314,0.011052,0.900000,42,21
3,1,leave_one_pair_out,0.795503,0.010251,0.900000,21,21
4,2,LOLO,0.873427,0.004458,0.925000,42,21
5,2,leave_one_pair_out,0.892752,0.004104,0.950000,21,21
6,3,LOLO,0.977195,0.006284,0.850000,42,21
7,3,leave_one_pair_out,0.980649,0.005789,0.850000,21,21
8,4,LOLO,0.967062,0.005553,1.000000,42,21
9,4,leave_one_pair_out,0.972405,0.005083,1.000000,21,21
10,5,LOLO,0.930512,0.011500,1.000000,42,21
11,5,leave_one_pair_out,0.942008,0.010506,1.000000,21,21
12,6,LOLO,0.928771,0.007428,0.925000,42,21
13,6,leave_one_pair_out,0.935590,0.007064,0.900000,21,21
14,7,LOLO,0.954625,0.002326,1.000000,42,21
15,7,leave_one_pair_out,0.958097,0.002236,1.000000,21,21
16,8,LOLO,0.918712,0.005598,1.000000,42,21
17,8,leave_one_pair_out,0.938939,0.004851,1.000000,21,21
18,9,LOLO,0.810176,0.007081,0.950000,42,21
19,9,leave_one_pair_out,0.817418,0.006945,0.950000,21,21

data/precomputed/fig03/composition_null_comparison.csv

,model_id,family,primary_r2,control_r2,delta_r2,delta_rmse,delta_sign_accuracy
0,0,sum,0.900989,-0.626464,1.527453,-0.024992,0.000000
1,0,luminance_label_permutation,0.900989,-0.152023,1.053012,-0.019558,0.008667
2,0,smooth_potential_ls0.25,0.900989,0.081716,0.819273,-0.015959,0.007167
3,0,smooth_potential_ls0.1,0.900989,-0.174284,1.075273,-0.019582,0.012403
4,0,smooth_potential_ls0.5,0.900989,0.151596,0.749393,-0.014770,0.001194
5,1,sum,0.762314,-0.648922,1.411236,-0.018057,0.000000
6,1,luminance_label_permutation,0.762314,-0.163271,0.925586,-0.013231,0.005025
7,1,smooth_potential_ls0.25,0.762314,0.041706,0.720608,-0.010536,0.004000
8,1,smooth_potential_ls0.1,0.762314,-0.192757,0.955071,-0.013330,0.008312
9,1,smooth_potential_ls0.5,0.762314,0.058348,0.703966,-0.010268,0.000987
10,2,sum,0.873427,-0.192569,1.065996,-0.009227,0.075000
11,2,luminance_label_permutation,0.873427,-0.280977,1.154404,-0.009574,0.089163
12,2,smooth_potential_ls0.25,0.873427,-0.033043,0.906470,-0.007853,0.093063
13,2,smooth_potential_ls0.1,0.873427,-0.328265,1.201692,-0.009701,0.097675
14,2,smooth_potential_ls0.5,0.873427,0.072430,0.800997,-0.007266,0.082750
15,3,sum,0.977195,-0.333599,1.310794,-0.041774,0.050000
16,3,luminance_label_permutation,0.977195,-0.216629,1.193824,-0.039204,0.061075
17,3,smooth_potential_ls0.25,0.977195,0.021084,0.956111,-0.033361,0.054100
18,3,smooth_potential_ls0.1,0.977195,-0.278497,1.255692,-0.039871,0.067225
19,3,smooth_potential_ls0.5,0.977195,0.066945,0.910250,-0.032675,0.041325

data/precomputed/fig03/composition_bootstrap_summary.csv

      source           metric      mean    median    ci_low   ci_high
0  in_sample            slope  0.829171  0.820437  0.735793  0.926342
1  in_sample        intercept  0.007369  0.008957  0.003912  0.010905
2  in_sample               r2  0.929533  0.949121  0.896267  0.957286
3  in_sample   sign_agreement  0.965000  1.000000  0.915000  1.000000
4  in_sample  normalized_rmse  0.164101  0.137060  0.117946  0.227061
5       LOLO            cv_r2  0.902378  0.923741  0.858770  0.939922
6       LOLO          cv_rmse  0.006947  0.006683  0.005280  0.008640
7       LOLO    sign_accuracy  0.949444  0.947222  0.918889  0.977500

data/precomputed/fig03/composition_control_summary.csv

,family,delta_r2,ci_low,ci_high,delta_rmse,delta_sign_accuracy,null_rank_p,holm_null_rank_p
0,sum,1.199115,1.040639,1.344252,-0.021617,0.131598,NaN,NaN
1,luminance_label_permutation,1.174734,1.101558,1.241541,-0.020933,0.144382,0.0005,0.001999
2,smooth_potential_ls0.25,0.885534,0.837294,0.926397,-0.017051,0.119677,0.0005,0.001999
3,smooth_potential_ls0.1,1.193446,1.126214,1.251521,-0.021017,0.141876,0.0005,0.001999
4,smooth_potential_ls0.5,0.769393,0.719931,0.820044,-0.015324,0.110515,0.0005,0.001999

data/precomputed/supplementary/figS1/multifield_sign_correspondence.csv

,model_id,renderer,CW_scalar,CCW_scalar,CW_negative,CCW_positive,CW_positive,CCW_negative,CW_ratio,CCW_ratio
0,flow/0000/000,multi,-7.647665,7.691140,True,True,False,False,36.910130,36.624081
1,flow/0000/000,single,9.815791,-9.696330,False,False,True,True,39.122844,38.596992
2,flow/0000/001,multi,-8.443925,8.470246,True,True,False,False,34.875829,34.421583
3,flow/0000/001,single,10.863988,-10.576016,False,False,True,True,79.350296,75.009514
4,flow/0000/002,multi,-9.572545,9.782128,True,True,False,False,48.979591,49.384323
5,flow/0000/002,single,12.580959,-12.986949,False,False,True,True,71.072805,72.595423
6,flow/0000/003,multi,-8.750644,9.007139,True,True,False,False,35.197151,35.591241
7,flow/0000/003,single,10.655712,-11.181517,False,False,True,True,55.355800,56.906250
8,flow/0000/004,multi,-9.226387,9.119997,True,True,False,False,34.723791,34.831075
9,flow/0000/004,single,11.325296,-11.115194,False,False,True,True,36.405540,36.009920
10,flow/0000/005,multi,-7.783455,7.759108,True,True,False,False,37.703580,38.119693
11,flow/0000/005,single,9.033018,-8.993076,False,False,True,True,46.198505,46.195562
12,flow/0000/006,multi,-10.554053,10.874116,True,True,False,False,43.425781,44.228114
13,flow/0000/006,single,12.874547,-13.370454,False,False,True,True,56.521500,57.899982
14,flow/0000/007,multi,-8.862742,9.035148,True,True,False,False,42.765257,42.757004
15,flow/0000/007,single,9.695414,-10.057525,False,False,True,True,35.794423,36.226192
16,flow/0000/008,multi,-6.720412,6.699434,True,True,False,False,34.484259,34.560751
17,flow/0000/008,single,8.615618,-8.621210,False,False,True,True,48.668719,48.951274
18,flow/0000/009,multi,-7.656979,7.751501,True,True,False,False,18.639072,18.653879
19,flow/0000/009,single,10.480329,-10.399835,False,False,True,True,27.999786,27.508370

data/precomputed/supplementary/figS1/multifield_qa.csv

                                               check  pass
0                     cached_MIDD_render_exact_bytes  True
1          geometry_placement_coordinate_exact_match  True
2                      stored_Fig3_scalar_reproduced  True
3              analytic_CW_negative_historical_basis  True
4  new_propeller_physical_phase_verified_S1_defin...  True

data/precomputed/fig03/comparator_model_metrics.csv

,model_id,predictor,cv_r2,cv_rmse,normalized_rmse,sign_accuracy,slope,intercept
0,0,P0,0.900989,0.008186,0.066597,0.944444,0.562523,0.008200
1,0,P1,0.549827,0.017455,0.142005,0.944444,0.886383,0.016002
2,0,P3,0.309285,0.021621,0.175899,0.944444,-0.000469,0.008384
3,1,P0,0.762314,0.011052,0.144273,0.900000,0.791128,0.010205
4,1,P1,0.520112,0.015703,0.205000,0.900000,0.705148,0.017456
5,1,P3,0.125872,0.021194,0.276677,0.900000,-0.000374,0.013158
6,2,P0,0.873427,0.004458,0.087671,0.925000,0.645723,0.003829
7,2,P1,0.781763,0.005854,0.115120,0.850000,0.429397,0.002859
8,2,P3,0.166028,0.011444,0.225041,0.850000,-0.000197,0.003248
9,3,P0,0.977195,0.006284,0.050295,0.850000,0.798766,0.009874
10,3,P1,0.843304,0.016473,0.131837,0.925000,1.681888,0.002194
11,3,P3,0.300253,0.034812,0.278599,0.800000,-0.000718,0.001422
12,4,P0,0.967062,0.005553,0.053207,1.000000,0.842107,0.003533
13,4,P1,0.917666,0.008780,0.084121,0.950000,1.184908,0.009009
14,4,P3,0.651187,0.018071,0.173145,0.900000,-0.000640,-0.000662
15,5,P0,0.930512,0.011500,0.102805,1.000000,1.054478,0.009714
16,5,P1,0.976380,0.006705,0.059937,1.000000,1.758665,0.008022
17,5,P3,0.574389,0.028461,0.254429,0.894737,-0.000874,-0.000811
18,6,P0,0.928771,0.007428,0.086969,0.925000,0.790570,0.012877
19,6,P1,0.879275,0.009671,0.113224,0.850000,1.058946,0.004548

data/precomputed/fig03/comparator_summary.csv

   predictor           metric      mean    ci_low   ci_high
0         P0            cv_r2  0.902378  0.859211  0.939555
1         P0          cv_rmse  0.006947  0.005306  0.008602
2         P0  normalized_rmse  0.100559  0.076943  0.125491
3         P0    sign_accuracy  0.949444  0.919444  0.979444
4         P1            cv_r2  0.539775  0.218948  0.803337
5         P1          cv_rmse  0.012588  0.009497  0.015978
6         P1  normalized_rmse  0.220788  0.122106  0.342450
7         P1    sign_accuracy  0.843373  0.717495  0.933889
8         P2            cv_r2  0.343003  0.170435  0.490226
9         P2          cv_rmse  0.017832  0.014118  0.021471
10        P2  normalized_rmse  0.265898  0.199382  0.350042
11        P2    sign_accuracy  0.837341  0.749405  0.905541
12        P3            cv_r2  0.177182 -0.072193  0.395270
13        P3          cv_rmse  0.020923  0.016769  0.025396
14        P3  normalized_rmse  0.315516  0.235667  0.415220
15        P3    sign_accuracy  0.788442  0.638492  0.898363

data/precomputed/fig03/comparator_contrasts.csv

  comparator  mean_delta    ci_low   ci_high  exact_signflip_p    holm_p
0         P1    0.362603  0.100049  0.689086          0.003906  0.005859
1         P2    0.559375  0.408799  0.741313          0.001953  0.005859
2         P3    0.725196  0.513256  0.978716          0.001953  0.005859

## 7. Statistics
Model/seed is the unit. Stored intervals retain the original inference choices. Fig3/S7 additionally replay the exact original bootstrap seed and RNG consumption order; cached null draws are not regenerated or tuned.

In [7]:
statistics = statistical_tables(tables)
for name, frame in statistics.items():
    print(name)
    display(frame)

data/precomputed/fig03/composition_bootstrap_summary.csv

      source           metric      mean    median    ci_low   ci_high
0  in_sample            slope  0.829171  0.820437  0.735793  0.926342
1  in_sample        intercept  0.007369  0.008957  0.003912  0.010905
2  in_sample               r2  0.929533  0.949121  0.896267  0.957286
3  in_sample   sign_agreement  0.965000  1.000000  0.915000  1.000000
4  in_sample  normalized_rmse  0.164101  0.137060  0.117946  0.227061
5       LOLO            cv_r2  0.902378  0.923741  0.858770  0.939922
6       LOLO          cv_rmse  0.006947  0.006683  0.005280  0.008640
7       LOLO    sign_accuracy  0.949444  0.947222  0.918889  0.977500

data/precomputed/fig03/composition_control_summary.csv

,family,delta_r2,ci_low,ci_high,delta_rmse,delta_sign_accuracy,null_rank_p,holm_null_rank_p
0,sum,1.199115,1.040639,1.344252,-0.021617,0.131598,NaN,NaN
1,luminance_label_permutation,1.174734,1.101558,1.241541,-0.020933,0.144382,0.0005,0.001999
2,smooth_potential_ls0.25,0.885534,0.837294,0.926397,-0.017051,0.119677,0.0005,0.001999
3,smooth_potential_ls0.1,1.193446,1.126214,1.251521,-0.021017,0.141876,0.0005,0.001999
4,smooth_potential_ls0.5,0.769393,0.719931,0.820044,-0.015324,0.110515,0.0005,0.001999

data/precomputed/fig03/comparator_summary.csv

   predictor           metric      mean    ci_low   ci_high
0         P0            cv_r2  0.902378  0.859211  0.939555
1         P0          cv_rmse  0.006947  0.005306  0.008602
2         P0  normalized_rmse  0.100559  0.076943  0.125491
3         P0    sign_accuracy  0.949444  0.919444  0.979444
4         P1            cv_r2  0.539775  0.218948  0.803337
5         P1          cv_rmse  0.012588  0.009497  0.015978
6         P1  normalized_rmse  0.220788  0.122106  0.342450
7         P1    sign_accuracy  0.843373  0.717495  0.933889
8         P2            cv_r2  0.343003  0.170435  0.490226
9         P2          cv_rmse  0.017832  0.014118  0.021471
10        P2  normalized_rmse  0.265898  0.199382  0.350042
11        P2    sign_accuracy  0.837341  0.749405  0.905541
12        P3            cv_r2  0.177182 -0.072193  0.395270
13        P3          cv_rmse  0.020923  0.016769  0.025396
14        P3  normalized_rmse  0.315516  0.235667  0.415220
15        P3    sign_accuracy  0.788442  0.638492  0.898363

data/precomputed/fig03/comparator_contrasts.csv

  comparator  mean_delta    ci_low   ci_high  exact_signflip_p    holm_p
0         P1    0.362603  0.100049  0.689086          0.003906  0.005859
1         P2    0.559375  0.408799  0.741313          0.001953  0.005859
2         P3    0.725196  0.513256  0.978716          0.001953  0.005859

## 8. Figure generation
The shared plotting source preserves the adopted layout and labels; no manual PDF editing.

In [8]:
fig = render(FIGURE)
display(fig)

Saved 3 inputs 6 checks 2

## 9. Numerical summary
Summaries remain labeled by their source; repeated conditions are not independent observations.

In [9]:
print("Figure:", FIGURE, "primary tables:", len(primary), "adopted tables:", len(adopted))

Figure: 3 primary tables: 6 adopted tables: 10

## 10. Reproducibility metadata and hashes
Record inputs, shared source versions, numerical summaries, software, outputs, and limitations.

In [10]:
record = write_reproduction_record(FIGURE, ROOT, manifest, integration_checks, primary, adopted)
print("Canonical notebook:", record["canonical_notebook"])
print("Model inference:", record["inference_performed"])

Canonical notebook: notebooks/fig03/fig_3.ipynb
Model inference: False